const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{JSDOM}=require('../backend/node_modules/jsdom');
const flush=async()=>{for(let n=0;n<10;n++)await new Promise(r=>setImmediate(r));};
const row=(store,spend,sales,from='2026-10-05',to=from)=>({store,from,to,spend,sales,platform:'Shopee',currency:'THB',conversions:10,directConversions:8,views:100,clicks:30,directSales:100,units:10,directUnits:8,file:'ads.xlsx'});
function harness(role='admin',rows=[row('TEST_A',100,500),row('TEST_B',300,600)]){const dom=new JSDOM(fs.readFileSync(require.resolve('../advertising.html'),'utf8'),{url:'https://nakamaauto.com/advertising.html',runScripts:'outside-only'}),w=dom.window;let callback,pending=null,uploads=0,preview=null,retryId=null,uploadOptions=null,workerOptions=null;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.Worker=class {postMessage(data){workerOptions=data.options;queueMicrotask(()=>this.onmessage({data:{rows:preview}}));}terminate(){}};w.cloudMock={start:async cb=>{callback=cb;await cb({user:{uid:'u'},role});},advertising:async()=>pending?await pending:{rows,revision:'r',updatedAt:1},pendingAdsImport:()=>retryId,uploadAds:async(files,progress,options)=>{uploadOptions=options;uploads++;rows=preview;return {changes:{added:2,replaced:0,duplicates:0}};},retryAdsImport:async()=>{uploads++;retryId=null;return {changes:{added:0,replaced:0,duplicates:2}};},authError:e=>e.message,signOut:async()=>callback(null)};
for(const f of ['report.js','date-range.js','store-labels.js','ads-engine.js'])vm.runInContext(fs.readFileSync(require.resolve('../assets/'+f),'utf8'),dom.getInternalVMContext());w.NKMReport.today=()=> '2026-10-06';vm.runInContext(fs.readFileSync(require.resolve('../assets/advertising.js'),'utf8').replace(/import\('\.\/cloud\.js[^']*'\)/,'Promise.resolve(cloudMock)'),dom.getInternalVMContext());return {dom,w,uploadOptions:()=>uploadOptions,workerOptions:()=>workerOptions,uploads:()=>uploads,revoke:()=>callback({blocked:true,user:{uid:'u'},error:'Revoked'}),delay:p=>{pending=p;},preview:r=>{preview=r;},pending:id=>{retryId=id;},upload:()=>{const input=w.document.getElementById('ads-files');Object.defineProperty(input,'files',{configurable:true,value:[{name:'ads.xlsx',size:100,lastModified:0,arrayBuffer:async()=>new ArrayBuffer(1)}]});input.dispatchEvent(new w.Event('change'));}};}
test('advertising shows weighted ROAS, multiple independent stores and real daily coverage',async()=>{const h=harness();await flush();const $=id=>h.w.document.getElementById(id);a.equal($('advertising-workspace').hidden,false);a.equal($('ads-roas').textContent,'2.75×');a.match($('ads-spend').textContent,/400/);a.match($('ads-daily-rows').textContent,/5 Oct 2026/);a.match($('ads-daily-rows').textContent,/2$/);const checks=$('ads-store-options').querySelectorAll('input');checks[0].checked=true;checks[0].dispatchEvent(new h.w.Event('change',{bubbles:true}));a.equal($('ads-roas').textContent,'5.00×');checks[1].checked=true;checks[1].dispatchEvent(new h.w.Event('change',{bubbles:true}));a.equal($('ads-roas').textContent,'2.75×');a.equal($('ads-store-label').textContent,'2 stores selected');h.dom.window.close();});
test('cross-month period export is visible by default, with no invented daily values',async()=>{const h=harness('viewer',[row('TEST_A',100,500,'2026-09-29','2026-10-05')]);await flush();const $=id=>h.w.document.getElementById(id);a.equal($('ads-roas').textContent,'5.00×');a.equal($('ads-partial').hidden,true);a.match($('ads-daily-rows').textContent,/No daily records/);a.equal($('upload-ads').disabled,true);a.equal(h.uploads(),0);h.dom.window.close();});
test('preview requires confirmation, import selects its complete reporting period and clears on revocation',async()=>{const h=harness('admin',[]);await flush();h.preview([row('TEST_A',100,500,'2026-09-29','2026-10-05')]);h.upload();await flush();const $=id=>h.w.document.getElementById(id);a.equal($('ads-preview').open,true);a.match($('ads-preview-summary').textContent,/1 new store-period/);a.equal(h.uploads(),0);$('ads-confirm').click();await flush();a.equal(h.uploads(),1);a.equal($('ads-preview').open,false);a.equal($('ads-roas').textContent,'5.00×');a.equal($('ads-partial').hidden,true);await h.revoke();a.equal($('advertising-workspace').hidden,true);for(const id of ['ads-store-rows','ads-daily-rows','ads-spend-chart','ads-preview-files','ads-spend','ads-store-options'])a.equal($(id).textContent,'');h.dom.window.close();});
test('late requests cannot repopulate a signed-out page; a failed load never enables imports',async()=>{const h=harness();await flush();let finish;h.delay(new Promise(r=>{finish=r;}));h.w.document.getElementById('refresh').click();await flush();await h.revoke();finish({rows:[row('TEST_A',999,999)],revision:'late'});await flush();a.equal(h.w.document.getElementById('ads-store-rows').textContent,'');a.equal(h.w.document.getElementById('advertising-workspace').hidden,true);h.dom.window.close();const failed=harness();failed.delay(Promise.reject(Error('Cannot load reports')));await flush();a.equal(failed.w.document.getElementById('upload-ads').disabled,true);a.match(failed.w.document.getElementById('ads-message').textContent,/Cannot load/);failed.dom.window.close();});
test('advertising navigation is reachable from desktop, mobile and embedded workspace',()=>{const d=new JSDOM(fs.readFileSync(require.resolve('../management.html'),'utf8')).window.document;a.equal(d.querySelectorAll('.sidebar [data-view=ads]').length,1);a.equal(d.querySelectorAll('#navigation-dialog [data-view=ads]').length,1);a.ok(d.getElementById('ads-view'));a.match(fs.readFileSync(require.resolve('../assets/workspace-shell.js'),'utf8'),/view==='ads'\?'advertising.html'/);});

test('Today, Yesterday, Last 7 days and a specific day read the uploaded daily history',async()=>{
 const h=harness('viewer',[row('TEST_A',50,250,'2026-09-30'),row('TEST_A',100,500,'2026-10-05'),row('TEST_A',200,800,'2026-10-06')]);await flush();const $=id=>h.w.document.getElementById(id),pick=key=>{h.w.document.querySelector('.date-range-trigger').click();h.w.document.querySelector('[data-date-preset="'+key+'"]').click();h.w.document.querySelector('[data-range-apply]').click();};
 pick('today');a.match($('ads-spend').textContent,/200/);a.equal($('ads-roas').textContent,'4.00×');pick('yesterday');a.match($('ads-spend').textContent,/100/);pick('last7');a.match($('ads-spend').textContent,/350/);a.match($('ads-day-page').textContent,/3 reported days/);
 h.w.document.querySelector('.date-range-trigger').click();for(const [attr,value] of [['data-range-from','30/09/2026'],['data-range-to','30/09/2026']]){const input=h.w.document.querySelector('['+attr+']');input.value=value;input.dispatchEvent(new h.w.Event('input'));}h.w.document.querySelector('[data-range-apply]').click();a.match($('ads-spend').textContent,/50/);h.dom.window.close();
});
test('platform choice keeps TikTok ROI and SKU orders separate, and the upload store reaches preview and publication',async()=>{
 const tt={...row('TEST_A',300,900),platform:'TikTok',conversions:20,directSales:null,directConversions:null,views:null,clicks:null,units:null,directUnits:null},h=harness('admin',[row('TEST_A',100,500),tt]);await flush();const $=id=>h.w.document.getElementById(id);a.equal($('ads-conversions').textContent,'10 / 20');a.equal($('ads-store-rows').querySelectorAll('tr').length,2);$('ads-platform').value='TikTok';$('ads-platform').dispatchEvent(new h.w.Event('change'));a.equal($('ads-roas').textContent,'3.00×');a.equal($('ads-ratio-label').textContent,'ROI');a.match($('ads-sales-note').textContent,/paid \+ organic/);a.equal($('ads-conversions').textContent,'20');a.match($('ads-store-rows').textContent,/Unavailable/);
 $('upload-ads').click();a.equal($('ads-upload-options').open,true);$('ads-tiktok-store').value='NKM_TT';$('ads-upload-cancel').click();h.preview([{...tt,store:'NKM_TT'}]);h.upload();await flush();a.equal(h.workerOptions().tiktokStore,'NKM_TT');a.match($('ads-preview-files').textContent,/TikTok.*Nakama TikTok Shop.*1 days/);$('ads-confirm').click();await flush();a.equal(h.uploadOptions().tiktokStore,'NKM_TT');a.equal($('ads-platform').value,'TikTok');h.dom.window.close();
});
test('incomplete daily detail does not inflate month-total headlines',async()=>{
 const h=harness('viewer',[row('TEST_A',1000,5000,'2026-10-01','2026-10-06'),row('TEST_A',100,500,'2026-10-05')]);await flush();const $=id=>h.w.document.getElementById(id);a.match($('ads-spend').textContent,/1,000/);a.match($('ads-coverage').textContent,/until every daily report/);a.match($('ads-daily-rows').textContent,/5 Oct 2026/);a.match($('ads-day-page').textContent,/1 reported days/);h.dom.window.close();
});
