const file={name:'ads.csv',size:10,lastModified:1,arrayBuffer:async()=>Uint8Array.from([0,1,2,3,4,5,6,7,8,255]).buffer};
const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function harness(handler){const auth={currentUser:{uid:'owner'}},calls=[],F={initializeApp:()=>({}),initializeAuth:()=>auth,getFunctions:()=>({}),getStorage:()=>({}),getFirestore:()=>({}),onAuthStateChanged:()=>{},httpsCallable:(f,name)=>async data=>{calls.push({name,data});return {data:await handler(data)};},ref:(s,path)=>path,uploadBytesResumable:()=>({on:(event,progress,error,done)=>done()})},ctx=vm.createContext({F,btoa:s=>Buffer.from(s,'binary').toString('base64'),window:{NKM_CLOUD_CONFIG:{firebase:{projectId:'nakama-sales',apiKey:'test'}}},sessionStorage:{getItem:()=>{throw Error('blocked');},setItem:()=>{throw Error('blocked');},removeItem:()=>{throw Error('blocked');}}});vm.runInContext(fs.readFileSync(require.resolve('../assets/cloud.js'),'utf8').replace(/^import[^\n]*\n/gm,'').replace(/mountAuthUI\(/g,'(()=>null)(').replace(/\bexport /g,''),ctx);ctx.file=file;return {ctx,auth,calls,run:code=>vm.runInContext(code,ctx)};}
test('advertising pagination preserves revision and rejects repeated cursors, mismatched totals and incomplete reports',async()=>{
 const h=harness(d=>({rows:d.cursor?[{store:'B'}]:[{store:'A'}],revision:'r1',total:2,nextCursor:d.cursor?null:'1'}));await h.run('start(()=>{},()=>{})');a.equal((await h.run('advertising()')).rows.length,2);a.equal(h.calls[1].data.revision,'r1');a.equal(h.calls[1].name,'nkmProcessImport');a.equal(h.calls[1].data.source,'advertising');
 for(const mode of ['repeat','revision','total','incomplete']){const h=harness(d=>({rows:[{}],revision:mode==='revision'&&d.cursor?'r2':'r1',total:mode==='total'&&d.cursor?3:mode==='incomplete'?3:2,nextCursor:mode==='repeat'?'1':d.cursor?null:'1'}));await h.run('start(()=>{},()=>{})');await a.rejects(h.run('advertising()'));}
});
test('restricted browser uploads still publish, pending retries remain owner-scoped, and timeout recovery is idempotent',async()=>{
 let processFails=false,complete=false;const h=harness(d=>{if(d.op==='begin')return {id:'job1',files:[{index:'0',path:'adUploads/owner/job1/0',contentType:'text/csv'}]};if(d.op==='upload'){a.equal(Buffer.from(d.base64,'base64').length,10);a.equal(d.id,'job1');a.equal(d.index,'0');return {state:'uploaded'};}if(d.op==='process'){if(processFails)throw Object.assign(Error('network timeout'),{code:'functions/deadline-exceeded'});complete=true;return {state:'complete',changes:{added:1}};}if(d.op==='status')return {state:complete?'complete':'uploading',changes:{added:1}};});await h.run('start(()=>{},()=>{})');
 a.equal((await h.run("uploadAds([file])")).state,'complete');a.equal(h.run('pendingAdsImport()'),null);a.equal(h.calls.filter(c=>c.data.op==='upload').length,1);
 processFails=true;complete=false;await a.rejects(h.run("uploadAds([file])"));a.equal(h.run('pendingAdsImport()'),'job1');h.auth.currentUser={uid:'other'};a.equal(h.run('pendingAdsImport()'),null);h.auth.currentUser={uid:'owner'};a.equal(h.run('pendingAdsImport()'),'job1');complete=true;a.equal((await h.run('retryAdsImport()')).state,'complete');a.equal(h.run('pendingAdsImport()'),null);
});
