const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),Ads=require('../assets/ads-engine'),C=require('../backend/functions/lib/core'),X=require('../assets/vendor/xlsx.full.min.js'),create=require('../backend/functions/lib/ads-service');
const header=['BigSeller Store Name','Spend','Sales Amount','Direct Sales Amount','Conversion','Direct Conversion','Views','Clicks','Sold Products','Directly Sold Products'];
const fixture=(from='2026-10-05',to=from)=>[['Shopee Ads Data','Time:'+from+'-'+to,'Currency:THB'],[...header],['Summary',99999,99999,99999,99999,99999,99999,99999,99999,99999],['TEST_A','100.00','500.00','300.00',10,8,1000,100,15,12],['TEST_B','300.00','600.00','400.00',20,12,2000,200,30,20]];
test('BigSeller metadata, numeric strings and Summary exclusion produce weighted ROAS',()=>{const rows=Ads.parse(fixture(),'ads.xlsx'),t=Ads.totals(rows);a.equal(rows.length,2);a.equal(t.spend,400);a.equal(t.sales,1100);a.equal(t.roas,2.75);a.equal(t.conversions,30);a.equal(t.cpa,400/30);a.equal(t.directRoas,1.75);a.notEqual(t.roas,(5+2)/2);a.equal(Ads.daily(rows)[0].stores,2);});
test('bad dates, currency, malformed metrics, duplicate stores and missing fields fail closed',()=>{for(const mutate of [r=>r[0][1]='Time:2026-02-30-2026-03-01',r=>r[0][2]='Currency:USD',r=>r[3][1]='',r=>r[3][1]=-1,r=>r[3][4]=1.5,r=>r[3][1]='=1+1',r=>r[4][0]='TEST_A',r=>r[1][1]='Wrong header']){const rows=fixture();mutate(rows);a.throws(()=>Ads.parse(rows));}});
test('duplicates are ignored, revised store periods replace atomically, conflicting batches are blocked',()=>{const rows=Ads.parse(fixture()),same=Ads.merge(rows,[...rows,...rows]);a.equal(same.rows.length,2);a.equal(same.added,0);a.equal(same.replaced,0);a.equal(same.duplicates,4);const changed={...rows[0],spend:120},update=Ads.merge(rows,[changed]);a.equal(update.replaced,1);a.equal(Ads.totals(update.rows).spend,420);a.throws(()=>Ads.merge(rows,[rows[0],changed]),/disagree/);a.equal(rows[0].spend,100);});
test('overlapping daily and weekly reports never double count; consecutive periods remain allowed',()=>{const weekly=Ads.parse(fixture('2026-10-01','2026-10-07'));a.throws(()=>Ads.merge(weekly,Ads.parse(fixture('2026-10-05'))),/overlaps/);a.equal(Ads.merge(weekly,Ads.parse(fixture('2026-10-08'))).rows.length,4);a.throws(()=>Ads.merge([],Ads.parse(fixture('2026-10-01','2026-10-07')).concat(Ads.parse(fixture('2026-10-04','2026-10-10')))),/overlaps/);});
test('period totals retain their grain and are excluded at partial date boundaries',()=>{const rows=Ads.parse(fixture('2026-09-29','2026-10-05'));a.equal(Ads.daily(rows).length,0);const partial=Ads.select(rows,{from:'2026-10-01',to:'2026-10-05'});a.equal(partial.partial.length,2);a.equal(partial.rows.length,0);a.equal(Ads.select(rows,{from:'2026-09-29',to:'2026-10-05'},['TEST_A']).totals.spend,100);a.equal(Ads.totals([{...rows[0],spend:0,conversions:0}]).roas,null);});
test('server and browser use the same parser; server reads XLSX and CSV without trusting client totals',()=>{a.equal(fs.readFileSync(require.resolve('../assets/ads-engine'),'utf8'),fs.readFileSync(require.resolve('../backend/functions/lib/ads-engine'),'utf8'));const api=create({C}),w=X.utils.book_new();X.utils.book_append_sheet(w,X.utils.aoa_to_sheet(fixture()),'sheet1');a.equal(api.parse(X.write(w,{type:'buffer',bookType:'xlsx'}),'export.xlsx').length,2);a.equal(api.parse(Buffer.from(X.utils.sheet_to_csv(w.Sheets.sheet1)),'export.csv').length,2);});
function harness(){const docs=new Map(),objects=new Map();let enabled=true,beforePublish=null;const stamp=v=>({toMillis:()=>v}),ref=path=>({path,get:async()=>({data:()=>docs.get(path)})}),db={doc:ref,runTransaction:async fn=>{const changes=[];const result=await fn({get:async r=>r.get(),set:(r,d)=>changes.push(()=>docs.set(r.path,d)),create:(r,d)=>{if(docs.has(r.path))throw Error('exists');changes.push(()=>docs.set(r.path,d));},update:(r,d)=>changes.push(()=>docs.set(r.path,{...docs.get(r.path),...d}))});changes.forEach(f=>f());return result;}},bucket={file:(path)=>({name:path,getMetadata:async()=>{const object=objects.get(path);if(!object)throw Object.assign(Error('missing'),{code:404});return [{size:object.bytes.length,contentType:object.contentType,generation:'1'}];},download:async()=>[objects.get(path).bytes],save:async(bytes,options)=>{if(options?.preconditionOpts?.ifGenerationMatch===0&&objects.has(path))throw Object.assign(Error('exists'),{code:412});objects.set(path,{bytes,contentType:options?.metadata?.contentType});beforePublish?.();},setMetadata:async()=>{}})},api=create({db,bucket,C,Timestamp:{fromMillis:stamp,now:()=>stamp(123)},member:async(req,roles)=>C.role(req.auth,{enabled,role:req.auth?.token?.nakamaRole},roles)});
docs.set('members/u',{enabled:true,role:'admin'});const req=(op,data={},role='admin')=>({auth:{uid:'u',token:{nakamaRole:role}},data:{op,...data}});return {docs,objects,api,req,revoke:()=>{enabled=false;},beforePublish:fn=>{beforePublish=fn;},upload:async rows=>{const w=X.utils.book_new();X.utils.book_append_sheet(w,X.utils.aoa_to_sheet(rows),'sheet1');const bytes=X.write(w,{type:'buffer',bookType:'xlsx'}),job=await api.handle(req('begin',{files:[{name:'export.xlsx',size:bytes.length}]}));objects.set(job.files[0].path,{bytes,contentType:job.files[0].contentType});return job.id;}};}
test('shared advertising API enforces membership, importer role and idempotent processing',async()=>{const h=harness();await a.rejects(h.api.handle({data:{op:'load'}}),e=>e.code==='unauthenticated');await a.rejects(h.api.handle(h.req('begin',{files:[]},'viewer')),e=>e.code==='permission-denied');const id=await h.upload(fixture()),result=await h.api.handle(h.req('process',{id}));a.equal(result.changes.added,2);const read=await h.api.handle(h.req('load',{},'viewer'));a.equal(read.rows.length,2);a.equal(read.rows[0].spend,100);a.equal((await h.api.handle(h.req('process',{id}))).revision,result.revision);const second=await h.upload(fixture());a.equal((await h.api.handle(h.req('process',{id:second}))).changes.duplicates,2);a.equal(h.docs.get('adWorkspace/main').revision,result.revision);h.revoke();await a.rejects(h.api.handle(h.req('load')),e=>e.code==='permission-denied');});
test('overlaps, changed pagination, changed shared revision, revocation and missing uploads cannot publish',async()=>{const h=harness(),id=await h.upload(fixture());await h.api.handle(h.req('process',{id}));const base=h.docs.get('adWorkspace/main').revision,overlap=await h.upload(fixture('2026-10-01','2026-10-07'));await a.rejects(h.api.handle(h.req('process',{id:overlap})),/overlaps/);a.equal(h.docs.get('adWorkspace/main').revision,base);await a.rejects(h.api.handle(h.req('load',{revision:C.randomId()})),e=>e.code==='aborted');const missing=await h.upload(fixture('2026-10-06'));h.objects.delete('adUploads/u/'+missing+'/0');await a.rejects(h.api.handle(h.req('process',{id:missing})),e=>e.code==='failed-precondition');const race=await h.upload(fixture('2026-10-07'));h.beforePublish(()=>h.docs.set('adWorkspace/main',{...h.docs.get('adWorkspace/main'),revision:C.randomId()}));await a.rejects(h.api.handle(h.req('process',{id:race})),e=>e.code==='aborted');a.equal(h.docs.get('adImports/'+race).state,'uploading');h.beforePublish(()=>h.revoke());const revoked=await h.upload(fixture('2026-10-08'));await a.rejects(h.api.handle(h.req('process',{id:revoked})),e=>e.code==='permission-denied');a.equal(h.docs.get('adImports/'+revoked).state,'uploading');});
test('authenticated advertising upload checks owner, role, expiry, file slots, encoding and original size; retries cannot overwrite',async()=>{
 const h=harness(),bytes=Buffer.from('original csv'),job=await h.api.handle(h.req('begin',{files:[{name:'ads.csv',size:bytes.length}]})),args={id:job.id,index:'0',base64:bytes.toString('base64')};
 for(const data of [{...args,index:'1'},{...args,index:0},{...args,base64:'invalid!'},{...args,base64:'YQ=='},{...args,base64:'YQ'},{...args,base64:'a'.repeat(Math.ceil(4*1024*1024/3)*4+1)}])await a.rejects(h.api.handle(h.req('upload',data)),e=>e.code==='invalid-argument');
 await a.rejects(h.api.handle({...h.req('upload',args),auth:{uid:'other',token:{nakamaRole:'admin'}}}),e=>e.code==='permission-denied');await a.rejects(h.api.handle(h.req('upload',args,'viewer')),e=>e.code==='permission-denied');a.equal(h.objects.size,0);
 a.equal((await h.api.handle(h.req('upload',args))).state,'uploaded');a.equal((await h.api.handle(h.req('upload',args))).state,'uploaded');a.equal(h.objects.get(job.files[0].path).contentType,'text/csv');
 await a.rejects(h.api.handle(h.req('upload',{...args,base64:Buffer.from('changed! csv').toString('base64')})),e=>e.code==='already-exists');a.ok(h.objects.get(job.files[0].path).bytes.equals(bytes));
 const jobDoc=h.docs.get('adImports/'+job.id);jobDoc.expiresAt={toMillis:()=>Date.now()-1};await a.rejects(h.api.handle(h.req('upload',args)),e=>e.code==='failed-precondition');jobDoc.expiresAt={toMillis:()=>Date.now()+10000};jobDoc.state='complete';await a.rejects(h.api.handle(h.req('upload',args)),e=>e.code==='failed-precondition');jobDoc.state='uploading';h.revoke();await a.rejects(h.api.handle(h.req('upload',args)),e=>e.code==='permission-denied');
});
module.exports={fixture};
