const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{JSDOM}=require('../backend/node_modules/jsdom'),root=path.resolve(__dirname,'..');
const flush=async()=>{for(let n=0;n<10;n++)await new Promise(r=>setImmediate(r));};
function harness(report,monthly=false){const dom=new JSDOM(fs.readFileSync(path.join(root,'customer-insight.html'),'utf8'),{url:'https://nakamaauto.com/customer-insight.html',runScripts:'outside-only'}),w=dom.window;let callback,pending;const calls=[];
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.fetch=async()=>({ok:true,json:async()=>['Order No','Quantity','Price']});w.nkmStoreLabel=v=>v;w.cloudMock={workspace:async()=>({revision:'r',months:['2026-08','2026-09']}),loadMonth:async(s,m)=>({daily:[{date:m+'-01',status:'Completed',gmv:m==='2026-08'?100:150}]}),start:async cb=>{callback=cb;await cb({user:{uid:'u'},role:'viewer',state:{revision:'r',months:['2026-08','2026-09']}});},customerInsights:async args=>{calls.push({...args});return pending?await pending:report;},authError:e=>e.message,signOut:async()=>callback(null),signIn:async()=>{},retrySession:async()=>{}};
for(const f of (monthly?['engine.js','report.js','date-range.js','store-picker.js','monthly-gmv.js']:['report.js','date-range.js','store-picker.js']))vm.runInContext(fs.readFileSync(path.join(root,'assets',f),'utf8'),dom.getInternalVMContext());
const source=fs.readFileSync(path.join(root,'assets/customer-insight.js'),'utf8').replace(/import\('\.\/cloud\.js[^']*'\)/,'Promise.resolve(cloudMock)');vm.runInContext(source,dom.getInternalVMContext());return {dom,w,calls,revoke:()=>callback({blocked:true,user:{uid:'u'},error:'Revoked'}),delay:p=>{pending=p;}};}
const report={version:1,revision:'r',months:['2026-09'],updatedAt:1,filters:{from:'2026-09-01',to:'2026-09-30'},options:{stores:['NKM_SHP'],platforms:['Shopee']},totals:{orders:1,gmv:59,units:1,aov:59,buyers:1,repeatBuyers:0,repeatRate:0,identifiedGmv:59,bulkOrders:0},coverage:{enrichedOrders:1,identifiedOrders:1,locatedOrders:1,fitmentOrders:1,wiperUnits:1,fitmentUnits:1,buyerCoverage:1,locationCoverage:1,fitmentCoverage:1,firstDate:'2026-09-08',lastDate:'2026-09-08'},personas:[{label:'Wiper replacement',orders:1,gmv:59}],provinces:[{label:'กรุงเทพมหานคร',orders:1,gmv:59}],cars:[{label:'Isuzu D-MAX',type:'Pickup',orders:1,gmv:59,units:1,share:1,marketType:'Core demand'}],frequency:[{label:'One observed order',orders:1,gmv:59}],vehicleTypes:[],categories:[],channels:[{label:'Shopee',gmv:59}]};
test('customer UI renders measured profile, correct order coverage, unavailable demographics and main cars',async()=>{const h=harness(report);await flush();const $=id=>h.w.document.getElementById(id);a.equal($('customer-dashboard').hidden,false);a.equal($('main-profile').textContent,'Wiper replacement');a.match($('car-rows').textContent,/Isuzu D-MAX/);a.match($('customer-status').textContent,/2026-09-08/);a.equal($('repeat-rate').textContent,'0.0%');a.equal(h.w.document.querySelectorAll('.demographic-list b')[1].textContent,'Not in this export');a.match($('header-mapping').textContent,/Price × Quantity/);await h.revoke();a.equal($('customer-dashboard').hidden,true);a.equal($('main-profile').textContent,'');a.equal($('car-rows').textContent,'');a.equal($('buyer-total').textContent,'');h.dom.window.close();});
test('late customer responses cannot repopulate a signed-out page',async()=>{const h=harness(report);await flush();let resolve;h.delay(new Promise(r=>{resolve=r;}));h.w.document.getElementById('refresh').click();await flush();await h.revoke();resolve(report);await flush();a.equal(h.w.document.getElementById('customer-dashboard').hidden,true);a.equal(h.w.document.getElementById('persona-grid').textContent,'');h.dom.window.close();});

test('customer filters leave global monthly GMV intact and revocation clears it',async()=>{const h=harness(report,true);await flush();const section=h.w.document.getElementById('monthly-gmv');a.equal(section.hidden,false);a.equal(section.querySelector('[data-month="2026-09"]').dataset.gmv,'150');a.match(section.textContent,/\+50.0%/);const before=section.innerHTML;h.w.document.getElementById('basis').value='all';h.w.document.getElementById('customer-filters').dispatchEvent(new h.w.Event('submit',{cancelable:true}));await flush();a.equal(section.innerHTML,before);h.w.document.getElementById('refresh').click();await flush();a.equal(section.querySelectorAll('[data-month]').length,2);await h.revoke();a.equal(section.hidden,true);a.equal(section.querySelector('[data-monthly-chart]').textContent,'');h.dom.window.close();});

test('customer date drafts stay local and Apply sends one request without changing monthly GMV',async()=>{const h=harness(report,true);await flush();const $=s=>h.w.document.querySelector(s),chart=h.w.document.getElementById('monthly-gmv'),before=chart.innerHTML,calls=h.calls.length;$('.date-range-trigger').click();$('[data-month-prev]').click();$('[data-date-preset="last7"]').click();a.equal(h.calls.length,calls);$('[data-range-cancel]').click();a.equal(h.w.document.getElementById('from').value,'2026-09-01');$('.date-range-trigger').click();$('[data-date="2026-09-08"]').click();$('[data-date="2026-09-20"]').click();a.equal(h.calls.length,calls);$('[data-range-apply]').click();await flush();a.equal(h.calls.length,calls+1);a.equal(h.calls.at(-1).from,'2026-09-08');a.equal(h.calls.at(-1).to,'2026-09-20');a.equal(chart.innerHTML,before);await h.revoke();a.equal($('.date-range-trigger').disabled,true);a.equal($('.date-range-trigger b').textContent,'Choose dates');h.dom.window.close();});


test('customer store picker sends one array request on Apply, preserves choices and keeps shortcuts',async()=>{
 const h=harness({...report,options:{stores:['NKM_SHP','NKM_TT','SG_SHP'],platforms:['Shopee','TikTok']}});await flush();const d=h.w.document,open=()=>d.querySelector('.store-picker-trigger').click(),dialog=()=>d.querySelector('.store-picker-dialog'),select=code=>dialog().querySelector('input[type=checkbox][value="'+code+'"]').click(),before=h.calls.length;
 open();dialog().querySelector('[data-store-clear]').click();select('NKM_SHP');select('SG_SHP');a.equal(h.calls.length,before);dialog().querySelector('[data-store-cancel]').click();a.equal(h.calls.length,before);a.match(d.querySelector('.store-picker-trigger b').textContent,/Nakama/);
 open();dialog().querySelector('[data-store-clear]').click();select('NKM_SHP');select('SG_SHP');dialog().querySelector('[data-store-apply]').click();await flush();a.equal(h.calls.length,before+1);a.deepEqual(Array.from(h.calls.at(-1).store),['NKM_SHP','SG_SHP']);a.equal(d.querySelector('.store-picker-trigger b').textContent,'2 stores selected');open();a.equal(dialog().querySelector('input[value="SG_SHP"]').checked,true);dialog().querySelector('[data-store-mode="all"]').click();dialog().querySelector('[data-store-apply]').click();await flush();a.equal(h.calls.at(-1).store,'all');open();dialog().querySelector('[data-store-mode="nakama"]').click();dialog().querySelector('[data-store-apply]').click();await flush();a.equal(h.calls.at(-1).store,'nakama');await h.revoke();a.equal(d.querySelector('.store-picker-trigger').disabled,true);a.equal(dialog().textContent.includes('SG_SHP'),false);h.dom.window.close();
});
