const assert=require('node:assert/strict');const E=require('../assets/engine.js');
const headers=['Order No','Order Time','BigSeller Store Nickname','Marketplace','Order Status','Merchant SKU','Product Name','Quantity','Price'];
const row=(id,sku,qty,price,status='Completed')=>[id,'2026-09-01 12:00:00','Nakama','Shopee',status,sku,'Wiper '+sku,qty,price];
const file=rows=>({name:'orders.csv',headers,rows});
const a=E.raw([file([row('1','A',2,100),row('1','B',1,50),row('2','A',0,99)])]);
assert.equal(a.daily[0].gmv,250);assert.equal(a.daily[0].units,3);assert.equal(a.daily[0].orders,2);assert.equal(a.skus.find(x=>x.sku==='A').orders,2);
const same=E.raw([file([row('1','A',2,100),row('1','B',1,50),row('2','A',0,99)])],a.records);assert.equal(same.daily[0].gmv,250);assert.equal(same.diagnostics.duplicates,2);
const updated=E.raw([file([row('1','A',2,100,'Canceled'),row('1','B',1,50,'Canceled')])],a.records);assert.equal(updated.daily.reduce((s,r)=>s+r.gmv,0),250);assert.equal(updated.daily.find(x=>x.status==='Canceled').orders,1);
const repeated=E.raw([file([row('1','A',1,100),row('1','A',1,100)])]);assert.equal(repeated.daily[0].gmv,200);assert.equal(repeated.daily[0].orders,1);
assert.equal(E.raw([file([row('1','A','garbage',100)])]).diagnostics.invalid,1);assert.equal(E.raw([file([row('1','A',1.5,100)])]).diagnostics.invalid,1);
assert.throws(()=>E.raw([{name:'missing',headers:headers.filter(x=>x!=='Price'),rows:[]}]),/missing headers/);
assert.equal(E.date('2026-09-01T18:00:00Z'),'2026-09-02');assert.equal(E.date('31/08/2026'),'2026-08-31');assert.equal(E.date('2026-02-30'),'');assert.equal(E.number('THB 1,500.50'),1500.5);
assert.throws(()=>E.raw([file([row('1','A',1,100),row('1','B',1,100,'Canceled')])]),/conflicting/);
assert.equal(E.date('30 Jun 2026 19:09'),'2026-06-30');
assert.equal(E.date('31 Feb 2026 19:09'),'');
assert.equal(E.raw([file([row('free','A',1,0)])]).daily[0].gmv,0);
const part=(stamp,n,rows)=>({name:`Order-SKU-all${stamp}(${n}).xlsx`,headers,rows});
const split=E.raw([part('20260928113057994',2,[row('1','B',1,50)]),part('20260928113057994',1,[row('1','A',2,100)])]);
assert.equal(split.daily[0].gmv,250);assert.equal(split.daily[0].orders,1);assert.equal(split.daily[0].units,3);
assert.throws(()=>E.raw([part('20260928113057994',2,[row('1','A',1,100)])]),/consecutive/);
assert.throws(()=>E.raw([part('20260928113057994',1,[row('1','A',1,100)]),part('20260928113057994',1,[row('1','A',1,100)])]),/duplicate or ambiguous/);
assert.equal(E.raw([file([row('1','A',1,100)]),file([row('1','A',1,200)])]).daily[0].gmv,200);
const newer=E.raw([part('20260928113725788',1,[row('1','A',1,100,'Canceled')])],split.records);
const older=E.raw([part('20260928113057994',1,[row('1','A',1,500)])],newer.records);
assert.equal(older.daily[0].gmv,100);assert.equal(older.daily[0].status,'Canceled');assert.equal(older.diagnostics.older,1);
assert.equal(E.raw([file([row(123456789012345678,'A',1,100)])]).diagnostics.invalid,1);
assert.equal(E.raw([file([row('123456789012345678','A',1,100)])]).records[0].id,'123456789012345678');
const XLSX=require('../assets/vendor/xlsx.full.min.js');
const csv=headers.join(',')+'\n'+row('123456789012345678','A',1,100).join(',');
const workbook=XLSX.read(csv,{type:'string',dense:true,raw:true});
const parsed=XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]],{header:1,raw:true});
assert.equal(E.raw([{name:'orders.csv',headers:parsed[0],rows:parsed.slice(1)}]).records[0].id,'123456789012345678');
const excluded=E.raw([file([row('pp','A',1,'--','Platform Processing'),row('pp','B','--',500,' platform processing '),row('priced','A',20,100,'Platform Processing'),...['Completed','Canceled','Unpaid','Shipped'].map((s,i)=>row('keep'+i,'A',1,10,s))])]);
const warehouse=row('mixed','A',99,'--','Platform Processing');warehouse[1]='2026-08-02 17:00';const sale=row('mixed','A',1,59);sale[1]='2026-08-05 06:33';
for(const rows of [[warehouse,sale],[sale,warehouse]]){const mixed=E.raw([file(rows)]);assert.equal(mixed.orderCount,1);assert.equal(mixed.daily[0].date,'2026-08-05');assert.equal(mixed.daily[0].status,'Completed');assert.equal(mixed.daily[0].gmv,59);assert.equal(mixed.daily[0].units,1);assert.equal(mixed.daily[0].orders,1);assert.equal(mixed.skus[0].units,1);assert.equal(mixed.diagnostics.excludedRows,1);assert.equal(mixed.diagnostics.excludedOrders,0);assert.equal(mixed.diagnostics.retainedSalesOrders,1);}
const mixedParts=E.raw([{...part('20261001043643116',1,[warehouse,row('shared','A',2,10)]),name:'Order-SKU-all20261001043643116(1)(1).xlsx'},part('20261001043643116',2,[sale,row('shared','B',1,20)])]);assert.equal(mixedParts.orderCount,2);assert.equal(mixedParts.daily.reduce((n,r)=>n+r.gmv,0),99);assert.equal(mixedParts.records.find(o=>o.id==='shared').lines.length,2);
assert.throws(()=>E.raw([part('20261001043643116',1,[sale]),{...part('20261001043643116',1,[sale]),name:'Order-SKU-all20261001043643116(1)(1).xlsx'}]),/duplicate or ambiguous/);
const transfer=E.raw([file([row('transfer','A',1,'--','To Ship'),row('paid-to-ship','A',2,15,'To Ship')])]);assert.equal(transfer.diagnostics.invalid,0);assert.equal(transfer.orderCount,1);assert.equal(transfer.diagnostics.unpricedToShipRows,1);assert.equal(transfer.daily[0].gmv,30);assert.equal(transfer.daily[0].status,'To Ship');assert.equal(transfer.records.find(o=>o.id==='transfer').excluded,true);assert.equal(E.raw([],transfer.records).orderCount,1);
const transferThenSale=E.raw([file([row('transfer','A',1,'--','To Ship'),row('transfer','A',2,20,'Completed')])]);assert.equal(transferThenSale.orderCount,1);assert.equal(transferThenSale.daily[0].gmv,40);
const otherPlatform=row('not-shopee','A',1,'--','To Ship');otherPlatform[3]='TikTok';assert.equal(E.raw([file([otherPlatform])]).diagnostics.invalid,1);assert.equal(E.raw([file([row('not-marker','A',1,'','To Ship')])]).diagnostics.invalid,1);
assert.equal(excluded.diagnostics.invalid,0);assert.equal(excluded.diagnostics.excludedRows,3);assert.equal(excluded.diagnostics.excludedOrders,2);assert.equal(excluded.orderCount,4);
assert.equal(excluded.daily.reduce((s,r)=>s+r.gmv,0),40);assert.equal(excluded.daily.reduce((s,r)=>s+r.units,0),4);assert.equal(excluded.daily.reduce((s,r)=>s+r.orders,0),4);assert.equal(excluded.skus.reduce((s,r)=>s+r.gmv,0),40);
assert.ok(excluded.records.filter(o=>o.status==='Platform Processing').every(o=>o.lines.length===0));
const processing=E.raw([part('20260929113057994',1,[row('1','A',1,'--','Platform Processing')])],split.records);
assert.equal(processing.orderCount,0);assert.deepEqual(processing.daily,[]);assert.deepEqual(processing.skus,[]);
const staleCompleted=E.raw([part('20260928113057994',1,[row('1','A',1,500)])],processing.records);
assert.equal(staleCompleted.orderCount,0);assert.equal(staleCompleted.diagnostics.older,1);assert.deepEqual(staleCompleted.daily,[]);
const completedAgain=E.raw([part('20260930113057994',1,[row('1','A',2,30)])],processing.records);
assert.equal(completedAgain.orderCount,1);assert.equal(completedAgain.daily[0].gmv,60);
const staleProcessing=E.raw([part('20260929113057994',1,[row('1','A',1,'--','Platform Processing')])],completedAgain.records);
assert.equal(staleProcessing.daily[0].gmv,60);assert.equal(staleProcessing.diagnostics.older,1);
const legacy=split.records.map(o=>({...o,status:'Platform Processing'}));assert.deepEqual(E.aggregate(legacy),{daily:[],skus:[]});assert.equal(E.raw([file([row('new','A',1,5)])],legacy).orderCount,1);
assert.equal(E.filter([{status:'Platform Processing',gmv:500},{status:'Completed',gmv:10}],{}).length,1);
assert.deepEqual(E.summary([['Date','Store Code','Marketplace','Order Status','GMV','Units','Orders'],['2026-09-01','NKM_SHP','Shopee','Platform Processing','--','--','--']]).daily,[]);
const vm=require('node:vm'),fs=require('node:fs'),messages=[],worker={importScripts:()=>{},XLSX,NKMEngine:E,self:{postMessage:v=>messages.push(v)}};
vm.runInNewContext(fs.readFileSync(require.resolve('../assets/import-worker.js'),'utf8'),worker);
const workerCsv=[headers,row('pp','A',1,'--','Platform Processing'),row('ok','A',1,10)].map(r=>r.join(',')).join('\n');
worker.self.onmessage({data:{files:[{name:'orders.csv',buffer:Uint8Array.from(Buffer.from(workerCsv)).buffer}],cloud:true}});
assert.equal(messages.at(-1).result.orderCount,1);assert.equal(messages.at(-1).result.records.length,0);assert.equal(messages.at(-1).result.diagnostics.excludedOrders,1);
console.log('PASS: Platform Processing exclusions, missing/priced rows, all sales totals, status transitions, older exports, legacy reports and worker preview count.');
const many=Array.from({length:100000},(_,i)=>row(String(i),'A',1,2));const start=performance.now();const large=E.raw([file(many)]);assert.equal(large.records.length,100000);assert.equal(large.daily[0].gmv,200000);assert.equal(large.daily[0].orders,100000);console.log(`PASS: header mapping, quantity validation, zero quantity, multi-SKU orders, duplicate exports, status updates, repeated SKU lines, Bangkok dates, conflict rejection, 100,000-row aggregation (${Math.round(performance.now()-start)} ms).`);

const conflictParts=Array.from({length:12},(_,i)=>part('20261002074246450',i+1,[row(i===0||i===11?'1078238338262289':'other'+i,'W'+i,1,10,i===11?'Canceled':'Completed')]));
assert.throws(()=>E.raw(conflictParts),error=>{assert.equal(error.code,'order-conflict');assert.equal(error.details.orderId,'1078238338262289');assert.equal(error.details.rows[0].file,'Order-SKU-all20261002074246450(1).xlsx');assert.equal(error.details.rows[1].file,'Order-SKU-all20261002074246450(12).xlsx');assert.equal(error.details.rows[0].row,2);assert.equal(error.details.rows[1].row,2);assert.equal(error.details.rows[0].status,'Completed');assert.equal(error.details.rows[1].status,'Canceled');assert.match(error.message,/row 2: 2026-09-01 \/ Completed/);return true;});
const priorRecord=JSON.stringify(a.records);assert.throws(()=>E.raw(conflictParts,a.records),/conflicting/);assert.equal(JSON.stringify(a.records),priorRecord);
const duplicateDates=[row('date-only','A',1,10),row('date-only','B',1,10)];duplicateDates[1][1]='2026-09-02 12:00:00';assert.throws(()=>E.raw([file(duplicateDates)]),error=>error.details.rows[0].date==='2026-09-01'&&error.details.rows[1].date==='2026-09-02');
const xlsxFile=rows=>{const w=XLSX.utils.book_new();XLSX.utils.book_append_sheet(w,XLSX.utils.aoa_to_sheet([headers,...rows]),'Orders');return XLSX.write(w,{type:'array',bookType:'xlsx'});};
const workerMessages=[],diagnosticWorker={importScripts:()=>{},XLSX,NKMEngine:E,self:{postMessage:v=>workerMessages.push(v)}};vm.runInNewContext(fs.readFileSync(require.resolve('../assets/import-worker.js'),'utf8'),diagnosticWorker);diagnosticWorker.self.onmessage({data:{files:conflictParts.map(f=>({name:f.name,buffer:xlsxFile(f.rows)})),cloud:true}});assert.equal(workerMessages.at(-1).code,'order-conflict');assert.equal(workerMessages.at(-1).details.rows[1].file,conflictParts[11].name);
const twelveValid=conflictParts.map(f=>({...f,rows:f.rows.map(r=>{const out=[...r];out[4]='Completed';return out;})}));assert.equal(E.raw(twelveValid).orderCount,11);console.log('PASS: 12 XLSX export parts, actionable conflict locations, preserved existing orders, and worker diagnostic delivery.');
