const {test}=require('node:test'),a=require('node:assert/strict'),E=require('../assets/shipment-engine'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const head=['รายการ','Extension','จำนวนกล่อง','KG','กว้าง','ยาว','สูง','CBM','ราคาต่อหน่วย','จำนวนเงิน'];
const data=()=>[head,...Array.from({length:50},(_,i)=>['TRACK',`${i+1}/50`,1,29.5,48,42,34,i===1?null:.069,5300,365.7]),['รวม',null,50],['Total',null,null,null,null,null,null,null,null,18285],['scratch',null,null,null,9702]];
const product={sku:'TEST',width:33,length:40,height:49,cbm:.065},row=()=>({...E.parse(data()).rows[0],sku:'TEST'});
test('Thai invoice reads exactly 50 cartons, skips totals and scratch cells, and flags only the missing CBM',()=>{const p=E.parse(data());a.equal(p.rows.length,50);a.equal(p.boxes,50);a.equal(p.invoiceTotal,18285);a.deepEqual(p.issues,[]);a.deepEqual(p.rows[0].issues,[]);a.deepEqual(p.rows[1].issues,['Missing CBM; dimensions used']);});
test('mixed axes choose independent minima and recalculate freight',()=>{const r=E.compare(row(),[product]);a.equal(r.used.width,33);a.equal(r.used.length,40);a.equal(r.used.height,34);a.equal(r.used.cbm,.04488);a.equal(r.correctedAmount,237.86);a.equal(r.difference,127.84);a.deepEqual(r.issues,[]);});
test('lower uploaded and lower reference CBM are retained without increasing volumes',()=>{for(const [excel,master,expected] of [[.03,.065,.03],[.069,.02,.02]]){const r=E.compare({...row(),cbm:excel},[{...product,cbm:master}]);a.equal(r.used.cbm,expected);a.ok(r.issues.includes('Lower supplied CBM retained'));}});
test('missing SKU, unknown SKU, duplicate SKU, missing dimensions, zero and negative CBM cannot pass',()=>{for(const [r,p] of [[{...row(),sku:''},[product]],[{...row(),sku:'NO'},[product]],[row(),[product,product]],[row(),[{...product,width:null}]],[{...row(),cbm:0},[product]],[{...row(),cbm:-1},[product]]])a.equal(E.compare(r,p).checked,false);});
test('missing invoice CBM is calculated but stays flagged for review; rate mismatch stays flagged',()=>{const p=E.parse(data());p.rows[1].sku='TEST';const r=E.compare(p.rows[1],[product]);a.equal(r.checked,true);a.ok(r.issues.includes('Missing CBM; dimensions used'));const mismatch=E.compare({...row(),amount:1},[product]);a.ok(mismatch.issues.includes('Amount differs from quantity × rate'));});
test('carton count and extension inconsistencies are reported',()=>{const d=data();d[2][1]='1/50';d[51][2]=49;const p=E.parse(d);a.ok(p.rows[1].issues.includes('Duplicate or inconsistent carton number'));a.equal(p.issues.length,2);});
test('units convert dimensions before comparison and kg basis never caps the weight',()=>{const mm=data();for(const r of mm.slice(1,51))for(const i of [4,5,6])r[i]*=10;a.equal(E.parse(mm,{unit:'mm'}).rows[0].width,48);const r=E.compare(row(),[product],{basis:'kg'});a.equal(r.correctedAmount,29.5*5300);a.equal(r.used.height,34);a.equal(E.compare(row(),[product],{basis:'none'}).correctedAmount,null);});
test('blank/zero Product Info carton placeholders remain missing and product Dimension is ignored',()=>{const p=E.catalog([['Parent SKU','Dimension','W','D','H','CBM'],['TEST','1x1x1',0,40,49,0]]);a.equal(p[0].width,null);a.equal(p[0].cbm,null);a.equal(E.compare(row(),p).checked,false);});
test('partial totals exclude unchecked rows and charge-less rows, and CSV preserves both dimensions safely',()=>{const checked=E.compare(row(),[product]),unknown=E.compare({...row(),sku:'=DANGER'},[product]);const t=E.totals([checked,unknown]);a.equal(t.checked,1);a.equal(t.chargeRows,1);a.equal(t.cbm,.04488);a.equal(t.correctedAmount,237.86);const csv=E.csv([checked,unknown]);a.match(csv,/Uploaded W cm/);a.match(csv,/Chosen W cm/);a.match(csv,/"'=DANGER"/);a.match(csv,/SKU not found/);});
test('worker reads an XLSX through the actual vendor parser and returns the same validated table',()=>{const X=require('../assets/vendor/xlsx.full.min.js'),book=X.utils.book_new();X.utils.book_append_sheet(book,X.utils.aoa_to_sheet(data()),'Invoice');const buffer=X.write(book,{type:'buffer',bookType:'xlsx'});let response;const ctx=vm.createContext({XLSX:X,NKMShipment:E,importScripts:()=>{},self:{postMessage:r=>{response=r;}}});vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/shipment-import-worker.js'),'utf8'),ctx);ctx.self.onmessage({data:{buffer,kind:'shipment',unit:'cm'}});a.equal(response.error,undefined);a.equal(response.result.rows.length,50);});
test('Sea and Truck use their SKU reference rates instead of the invoice rate; volume is unchanged',()=>{
 const p={...product,seaRate:2000,truckRate:4000},sea=E.compare(row(),[p],{freight:'sea'}),truck=E.compare(row(),[p],{freight:'truck'});
 a.equal(sea.correctedAmount,89.76);a.equal(truck.correctedAmount,179.52);a.equal(sea.used.cbm,truck.used.cbm);a.equal(truck.usedRate,4000);a.equal(truck.referenceRate,4000);a.match(truck.rateSource,/Truck/);a.ok(truck.issues.includes('Uploaded rate differs from Truck freight reference'));
 const csv=E.csv([truck]);a.match(csv,/Freight method/);a.match(csv,/"truck","cbm","4000","4000","Product Info Truck"/);
});
test('missing and invalid selected freight rates never fall back to the uploaded rate; explicit zero stays zero',()=>{
 for(const rate of [null,undefined,-1,'4000']){const r=E.compare(row(),[{...product,seaRate:rate,truckRate:4000}],{freight:'sea'});a.equal(r.correctedAmount,null);a.equal(r.usedRate,null);a.equal(E.totals([r]).chargeRows,0);a.ok(r.issues.includes('Missing or invalid Sea freight rate in Product Info'));}
 const zero=E.compare(row(),[{...product,seaRate:0}],{freight:'sea'});a.equal(zero.correctedAmount,0);a.equal(zero.usedRate,0);
 const noInvoiceRate=E.compare({...row(),rate:null},[{...product,seaRate:2000}],{freight:'sea'});a.equal(noInvoiceRate.correctedAmount,89.76);a.equal(noInvoiceRate.expectedOriginal,null);
});
test('Product Info imports freight headers with line breaks and ignores derived per-unit charges',()=>{
 const products=E.catalog([['Parent SKU','W','D','H','CBM','SEA Freight\n(THB/m3)','SEA Freight (per unit)','Truck Freight\n(THB/m3)','Truck Freight (per unit)'],['TEST',33,40,49,.065,2000,1.3,4000,2.6]]);
 a.equal(products[0].seaRate,2000);a.equal(products[0].truckRate,4000);a.equal(E.compare(row(),products,{freight:'truck'}).correctedAmount,179.52);
});
