const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{JSDOM}=require('../backend/node_modules/jsdom'),E=require('../assets/shipment-engine');
const flush=async()=>{for(let i=0;i<8;i++)await new Promise(r=>setImmediate(r));};
const product={sku:'TEST',width:33,length:40,height:49,cbm:.065,seaRate:5300,truckRate:7500},parsed=()=>E.parse([['Tracking','Extension','Boxes','Width','Length','Height','CBM','Rate','Amount'],['TR','1/1',1,48,42,34,.069,5300,365.7]]);
function harness(){const dom=new JSDOM(fs.readFileSync(require.resolve('../shipment-check.html'),'utf8'),{url:'https://nakamaauto.com/shipment-check/',runScripts:'outside-only'}),w=dom.window;let cb,reference=()=>Promise.resolve({products:[product],updatedAt:123}),active,downloads=[];w.URL.createObjectURL=blob=>{downloads.push(blob);return 'blob:test';};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=()=>{};w.Worker=class{constructor(){active=this;}postMessage(){if(!this.delayed)setImmediate(()=>this.onmessage?.({data:{result:parsed()}}));}terminate(){this.terminated=true;}};w.cloudMock={call:async()=>reference(),start:async fn=>{cb=fn;await fn({user:{uid:'u'},role:'viewer'});},signOut:()=>cb(null),authError:e=>e.message};vm.runInContext(fs.readFileSync(require.resolve('../assets/shipment-engine.js'),'utf8'),dom.getInternalVMContext());vm.runInContext(fs.readFileSync(require.resolve('../assets/shipment-check.js'),'utf8').replace(/import\('\.\/cloud\.js\?v=[^']+'\)/,'Promise.resolve(cloudMock)'),dom.getInternalVMContext());const el=id=>w.document.getElementById(id);return {dom,w,el,revoke:()=>cb({user:{uid:'u'},blocked:true}),delayReference:fn=>{reference=fn;},worker:()=>active,downloads,upload:async()=>{Object.defineProperty(el('shipment-file'),'files',{configurable:true,value:[{name:'invoice.xlsx',size:100,arrayBuffer:async()=>new ArrayBuffer(8)}]});el('shipment-file').dispatchEvent(new w.Event('change'));await flush();}};}
test('upload waits for SKU; applying a SKU updates the comparison, totals and export',async()=>{const h=harness();await flush();await h.upload();a.equal(h.el('shipment-matched').textContent,'0 / 1');a.equal(h.el('shipment-cbm').textContent,'—');h.el('shipment-bulk-sku').value='TEST';h.el('shipment-apply').click();a.equal(h.el('shipment-matched').textContent,'1 / 1');a.match(h.el('shipment-cbm').textContent,/0.06468/);a.match(h.el('shipment-rows').textContent,/Uploaded dimensions differ from Product Info/);h.el('shipment-export').click();a.equal(h.downloads.length,1);h.dom.window.close();});
test('editing a SKU retains input focus and immediately blocks an unknown match',async()=>{const h=harness();await flush();await h.upload();const input=h.el('shipment-rows').querySelector('input');input.focus();input.value='BAD';input.dispatchEvent(new h.w.Event('input',{bubbles:true}));a.equal(h.w.document.activeElement,input);a.match(h.el('shipment-rows').textContent,/SKU not found/);a.equal(h.el('shipment-matched').textContent,'0 / 1');h.dom.window.close();});
test('revocation clears private rows, master reference, selections and summaries',async()=>{const h=harness();await flush();await h.upload();h.el('shipment-bulk-sku').value='TEST';h.el('shipment-apply').click();await h.revoke();for(const id of ['shipment-rows','shipment-skus','reference-status','shipment-cbm','shipment-filename'])a.equal(h.el(id).textContent,'');a.equal(h.el('shipment-bulk-sku').value,'');a.equal(h.el('shipment-export').disabled,true);a.equal(h.el('shipment-workspace').hidden,true);h.dom.window.close();});
test('late reference response cannot restore a revoked catalog',async()=>{const h=harness();await flush();let finish;h.delayReference(()=>new Promise(r=>{finish=r;}));h.el('reference-refresh').click();await flush();await h.revoke();finish({products:[product],updatedAt:123});await flush();a.equal(h.el('shipment-skus').textContent,'');a.equal(h.el('reference-status').textContent,'');h.dom.window.close();});
test('freight selector recalculates charges without re-uploading or changing SKU/dimensions; kg basis is clearly independent',async()=>{
 const h=harness();await flush();await h.upload();h.el('shipment-bulk-sku').value='TEST';h.el('shipment-apply').click();a.equal(h.el('shipment-freight').value,'sea');a.equal(h.el('shipment-charge').textContent,'342.80');const cbm=h.el('shipment-cbm').textContent;
 h.el('shipment-freight').value='truck';h.el('shipment-freight').dispatchEvent(new h.w.Event('change'));a.equal(h.el('shipment-charge').textContent,'485.10');a.equal(h.el('shipment-cbm').textContent,cbm);a.equal(h.el('shipment-rows').querySelector('input').value,'TEST');a.match(h.el('shipment-rows').textContent,/Product Info Truck 7,500.00 THB\/m³/);a.match(h.el('shipment-rows').textContent,/Uploaded rate differs from Truck/);
 h.el('shipment-basis').value='kg';h.el('shipment-basis').dispatchEvent(new h.w.Event('change'));a.equal(h.el('shipment-freight').disabled,true);a.match(h.el('shipment-charge-note').textContent,/Uploaded kg rate/);await h.revoke();a.equal(h.el('shipment-freight').value,'sea');a.equal(h.el('shipment-freight').disabled,true);h.dom.window.close();
});
test('missing selected method rate shows an unavailable charge and a review flag',async()=>{const h=harness();h.delayReference(()=>Promise.resolve({products:[{...product,truckRate:null}],updatedAt:123}));await flush();await h.upload();h.el('shipment-bulk-sku').value='TEST';h.el('shipment-apply').click();h.el('shipment-freight').value='truck';h.el('shipment-freight').dispatchEvent(new h.w.Event('change'));a.equal(h.el('shipment-charge').textContent,'—');a.match(h.el('shipment-rows').textContent,/Missing or invalid Truck freight rate/);h.dom.window.close();});
test('table removes Chosen and shows the exact Product Info centimeters and calculated benchmark volume',async()=>{const h=harness();await flush();await h.upload();h.el('shipment-bulk-sku').value='TEST';h.el('shipment-apply').click();const table=h.w.document.querySelector('.shipment-table');a.equal(table.querySelectorAll('th').length,7);a.equal(table.querySelector('tbody tr').children.length,7);a.doesNotMatch(table.querySelector('thead').textContent,/Chosen/);const reference=table.querySelector('tbody tr').children[4];a.match(reference.textContent,/33 cm × 40 cm × 49 cm/);a.match(reference.textContent,/0.06468 CBM · benchmark/);a.match(reference.textContent,/Sheet CBM 0.065/);a.equal(h.el('shipment-charge').textContent,'342.80');h.dom.window.close();});
