const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../backend/functions/lib/core'),S=require('../assets/stock-engine');
function harness(){let saved=null,enabled=true;const source=fs.readFileSync(require.resolve('../backend/functions/index.js'),'utf8').split("const Stock=require('./lib/stock-engine');")[1];const ctx={exports:{},Buffer,require:()=>S,C,Stock:S,member:async(req,roles)=>C.role(req.auth,{enabled,role:req.auth?.token?.nakamaRole},roles),Timestamp:{now:()=>({toMillis:()=>123})},db:{doc:path=>({path,get:async()=>({data:()=>path==='stockForecast/main'?saved:{enabled,role:'admin'}})}),runTransaction:async cb=>cb({get:async ref=>ref.get(),set:(ref,data)=>{saved=data;}})},endpoint:(options,fn)=>fn};vm.runInNewContext(source,ctx);return {api:ctx.exports,get:()=>saved,revoke:()=>{enabled=false;}};}
const request=(role,data)=>({auth:{uid:'u',token:{nakamaRole:role}},data});
test('shared forecast requires membership and edit role; saves are guarded by the current revision',async()=>{const h=harness();await a.rejects(h.api.nkmStockForecast({data:{op:'load'}}),e=>e.code==='unauthenticated');await a.rejects(h.api.nkmStockForecast(request('viewer',{op:'save',state:S.empty(),revision:null})),e=>e.code==='permission-denied');a.equal(h.get(),null);const saved=await h.api.nkmStockForecast(request('admin',{op:'save',state:S.empty(),revision:null}));a.ok(saved.revision);await a.rejects(h.api.nkmStockForecast(request('admin',{op:'save',state:S.empty(),revision:null})),e=>e.code==='aborted');const read=await h.api.nkmStockForecast(request('viewer',{op:'load'}));a.equal(read.revision,saved.revision);h.revoke();await a.rejects(h.api.nkmStockForecast(request('admin',{op:'load'})),e=>e.code==='permission-denied');});
test('invalid stock payload cannot mutate the shared state',async()=>{const h=harness(),state=S.empty();state.snapshot={date:'2026-09-01',fileName:'bad.xlsx',rows:[{sku:'A',title:'A',warehouse:'Main',onhand:-1,incoming:0}]};await a.rejects(h.api.nkmStockForecast(request('admin',{op:'save',state,revision:null})),e=>e.code==='invalid-argument');a.equal(h.get(),null);});


test('existing backend accepts receipt corrections and removals while rejecting invalid corrections atomically',async()=>{
 const h=harness(),state=S.empty();state.snapshot={date:S.today(),fileName:'inventory.xlsx',rows:[{sku:'A',title:'A',warehouse:'Main',onhand:10,incoming:0}]};state.settings.warehouses=['Main'];state.pos=[{id:'p',number:'Test-PO',supplier:'Test',orderDate:S.shift(S.today(),-3),status:'confirmed',lines:[{id:'l',sku:'A',qty:100,warehouse:'Main',eta:S.today(),receipts:[{id:'r',date:S.today(),qty:100,stockEffect:'add'}]}]}];
 const original=await h.api.nkmStockForecast(request('admin',{op:'save',state,revision:null}));const corrected=structuredClone(original.state);corrected.pos[0].lines[0].receipts[0].qty=60;corrected.pos[0].lines[0].receipts[0].date=S.shift(S.today(),-1);const update=await h.api.nkmStockForecast(request('admin',{op:'save',state:corrected,revision:original.revision}));a.equal(S.openingStock(update.state,'A'),70);a.equal(S.remaining(update.state.pos[0].lines[0]),40);a.equal(update.state.pos[0].lines[0].receipts[0].id,'r');
 const invalid=structuredClone(update.state);invalid.pos[0].lines[0].receipts[0].qty=101;await a.rejects(h.api.nkmStockForecast(request('admin',{op:'save',state:invalid,revision:update.revision})),e=>e.code==='invalid-argument');a.equal(h.get().revision,update.revision);a.equal(h.get().state.pos[0].lines[0].receipts[0].qty,60);
 const undone=structuredClone(update.state);undone.pos[0].lines[0].receipts=[];const saved=await h.api.nkmStockForecast(request('admin',{op:'save',state:undone,revision:update.revision}));a.equal(S.openingStock(saved.state,'A'),10);a.equal(S.poStatus(saved.state.pos[0]),'confirmed');const otherDevice=await h.api.nkmStockForecast(request('viewer',{op:'load'}));a.equal(otherDevice.state.pos[0].lines[0].receipts.length,0);a.equal(otherDevice.revision,saved.revision);
});
