const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),S=require('../assets/stock-engine'),X=require('../assets/vendor/xlsx.full.min.js');
function fixture(){const s=S.empty();s.snapshot={date:'2026-09-01',fileName:'inventory.xlsx',rows:[{sku:'Wiper_Size14_Pack01',title:'Wiper',warehouse:'Main Warehouse',onhand:1000,incoming:5000}]};s.settings.warehouses=['Main Warehouse'];s.skus=[{sku:'Wiper_Size14_Pack01',category:'wiper',rate:50,offline:0,growth:0,rateSource:'Manual'}];return s;}
const po=(num,eta,qty,status='confirmed',receipts=[])=>({id:num,number:num,supplier:'Factory',orderDate:'2026-08-01',status,lines:[{id:num+'-1',sku:'Wiper_Size14_Pack01',qty,warehouse:'Main Warehouse',eta,receipts}]});
test('stock engine browser and backend copies stay identical',()=>a.equal(fs.readFileSync(path.resolve(__dirname,'../assets/stock-engine.js'),'utf8'),fs.readFileSync(path.resolve(__dirname,'../backend/functions/lib/stock-engine.js'),'utf8')));
test('On Hand parsing uses bilingual headers and ignores allocated and available balances',()=>{const s=S.parseInventory(['SKU Name','Warehouse','On Hand','Order Allocated','Available for whole warehouse','On The Way'],[['SKU','Main',13,12,1,38000]],'inventory.xlsx','2026-09-01');a.equal(s.rows[0].onhand,13);a.equal(s.rows[0].incoming,38000);const t=S.parseInventory(['ชื่อSKU','ชื่อคลังสินค้า','สต็อกที่มีอยู่'],[['SKU','Main',20]],'thai.xlsx','2026-09-01');a.equal(t.rows[0].onhand,20);a.throws(()=>S.parseInventory(['SKU Name','Warehouse','On Hand'],[['SKU','Main','--']],'bad.xlsx','2026-09-01'),/Invalid On Hand/);a.throws(()=>S.parseInventory(['SKU Name','Warehouse','On Hand'],[['SKU','Main',1],['SKU','Main',1]],'bad.xlsx','2026-09-01'),/Duplicate/);});
test('multiple POs arrive separately and a rate increase exposes the gap without changing ordered units',()=>{const s=fixture();s.settings.horizon=60;s.pos=[po('PO1','2026-09-21',2000),po('PO2','2026-10-16',3000)];let r=S.forecast(s,s.skus[0].sku,s.snapshot.date);a.equal(r.firstShortage,null);s.skus[0].rate=100;r=S.forecast(s,s.skus[0].sku,s.snapshot.date);a.equal(r.firstShortage,'2026-09-12');a.equal(r.days.find(d=>d.date==='2026-09-20').inbound,0);a.equal(r.days.find(d=>d.date==='2026-09-21').inbound,2000);a.equal(r.days.find(d=>d.date==='2026-10-16').inbound,3000);a.equal(s.pos[0].lines[0].qty,2000);a.equal(r.pipeline,5000);a.equal(r.reportedIncoming,5000);a.equal(r.incomingDifference,0);a.ok(r.unmet>0);});
test('received stock is added only after the snapshot, partial receipts leave just the outstanding ETA quantity',()=>{const s=fixture();s.pos=[po('P','2026-09-21',1000,'confirmed',[{id:'a',date:'2026-08-30',qty:200},{id:'b',date:'2026-09-05',qty:300}])];let r=S.forecast(s,s.skus[0].sku,s.snapshot.date);a.equal(r.opening,1000);a.equal(r.days.find(d=>d.date==='2026-09-05').inbound,300);a.equal(r.days.find(d=>d.date==='2026-09-21').inbound,500);a.equal(r.pipeline,500);a.equal(S.poStatus(s.pos[0]),'partially received');s.snapshot.date='2026-09-06';s.snapshot.rows[0].onhand=1200;r=S.forecast(s,s.skus[0].sku,s.snapshot.date);a.equal(r.opening,1200);a.equal(r.days.reduce((n,d)=>n+d.inbound,0),500);});
test('drafts, cancellations, overdue ETAs and warehouse scope cannot falsely replenish stock',()=>{const s=fixture();s.pos=[po('draft','2026-09-02',9000,'draft'),po('cancel','2026-09-02',9000,'cancelled'),po('late','2026-08-31',500)];s.snapshot.rows.push({sku:s.skus[0].sku,title:'Wiper',warehouse:'Return Warehouse',onhand:900,incoming:0});const r=S.forecast(s,s.skus[0].sku,s.snapshot.date);a.equal(r.opening,1000);a.equal(r.pipeline,500);a.equal(r.overdue.length,1);a.equal(r.days.reduce((n,d)=>n+d.inbound,0),0);a.ok(r.firstShortage);});
test('lost sales and backorders produce different post-arrival balances, zero demand is a valid rate',()=>{const s=fixture();s.skus[0].rate=100;s.pos=[po('P','2026-09-21',2000)];let r=S.forecast(s,s.skus[0].sku,s.snapshot.date);a.equal(r.days.find(d=>d.date==='2026-09-21').balance,1900);s.settings.demandMode='backorder';r=S.forecast(s,s.skus[0].sku,s.snapshot.date);a.equal(r.days.find(d=>d.date==='2026-09-21').balance,1000);s.skus[0].rate=0;a.equal(S.forecast(s,s.skus[0].sku,s.snapshot.date).firstShortage,null);s.skus[0].rate=null;a.equal(S.forecast(s,s.skus[0].sku,s.snapshot.date).available,false);});
test('reimport replaces the snapshot and preserves fixed PO quantities and SKU assumptions',()=>{let s=fixture();s.pos=[po('P','2026-09-21',2000)];const snap={date:'2026-09-02',fileName:'new.xlsx',rows:[{sku:s.skus[0].sku,title:'Wiper',warehouse:'Main Warehouse',onhand:900,incoming:2000}]};s=S.mergeSnapshot(s,snap);s=S.mergeSnapshot(s,snap);a.equal(s.snapshot.rows.length,1);a.equal(s.snapshot.rows[0].onhand,900);a.equal(s.skus[0].rate,50);a.equal(s.pos[0].lines[0].qty,2000);});
test('recommendation covers demand after the new ETA, using already scheduled arrivals and one buffer',()=>{const s=fixture();s.skus[0].rate=100;s.settings.coverageDays=30;s.settings.safetyDays=15;const r=S.forecast(s,s.skus[0].sku,s.snapshot.date);a.equal(r.recommendation,4500);s.pos=[po('P','2026-10-16',4000)];a.equal(S.forecast(s,s.skus[0].sku,s.snapshot.date).recommendation,500);});
test('server validation rejects invalid quantities, excess receipts and duplicate identifiers',()=>{const s=fixture();s.pos=[po('P','2026-09-21',1000)];a.deepEqual(S.validate(s),s);s.pos[0].lines[0].qty=-1;a.throws(()=>S.validate(s),/ordered quantity/);s.pos[0].lines[0].qty=1000;s.pos[0].lines[0].receipts=[{id:'x',date:'2026-09-01',qty:1001}];a.throws(()=>S.validate(s),/exceeds/);s.pos[0].lines[0].receipts=[];s.pos.push(clone(s.pos[0]));a.throws(()=>S.validate(s),/Duplicate PO/);});
function clone(v){return JSON.parse(JSON.stringify(v));}
test('independent same-day receipts add stock once, included receipts do not, and legacy workspaces migrate safely',()=>{
 const s=fixture();s.snapshot.date=S.today();s.snapshot.rows[0].onhand=10;s.skus[0].rate=1;
 s.pos=[po('P',S.today(),100,'confirmed',[{id:'a',date:S.today(),qty:100,stockEffect:'add'}])];
 const saved=S.validate(s);a.equal(saved.version,2);a.equal(saved.pos[0].lines[0].receipts[0].stockEffect,'add');
 let r=S.forecast(saved,s.skus[0].sku);a.equal(r.opening,110);a.equal(r.receiptAdjustments,100);a.equal(r.days[0].balance,109);a.equal(r.days.reduce((n,d)=>n+d.inbound,0),0);a.equal(r.pipeline,0);
 saved.pos[0].lines[0].receipts[0].stockEffect='included';r=S.forecast(saved,s.skus[0].sku);a.equal(r.opening,10);
 s.version=1;delete s.pos[0].lines[0].receipts[0].stockEffect;a.equal(S.validate(s).version,2);a.equal(S.forecast(S.validate(s),s.skus[0].sku).opening,10);
 s.pos[0].lines[0].receipts[0].stockEffect='incorrect';a.throws(()=>S.validate(s),/how the receipt affects stock/);
});
test('replacement stock imports reconcile each receipt without double-counting or losing independent additions',()=>{
 const s=fixture();s.snapshot.date=S.today();s.skus[0].rate=1;s.pos=[po('P',S.today(),100,'confirmed',[{id:'a',date:S.today(),qty:100,stockEffect:'add'}])];
 const snap={...s.snapshot,rows:[{...s.snapshot.rows[0],onhand:110}]},p=s.pos[0],l=p.lines[0],key=S.receiptKey(p,l,l.receipts[0]);
 let next=S.mergeSnapshot(s,snap,[key]);a.equal(next.pos[0].lines[0].receipts[0].stockEffect,'included');a.equal(S.forecast(next,l.sku).opening,110);next=S.mergeSnapshot(next,snap,[key]);a.equal(S.forecast(next,l.sku).opening,110);
 const without={...snap,rows:[{...snap.rows[0],onhand:10}]};next=S.mergeSnapshot(s,without,[]);a.equal(S.forecast(next,l.sku).opening,110);a.equal(next.pos[0].lines[0].qty,100);
});
test('replenishment resolves upcoming shortage warnings while preserving the earlier shortage history',()=>{
 const s=fixture();s.snapshot.date=S.shift(S.today(),-10);s.snapshot.rows[0].onhand=0;s.skus[0].rate=1;s.settings.horizon=30;s.settings.safetyDays=0;
 s.pos=[po('P',S.today(),100,'confirmed',[{id:'a',date:S.today(),qty:100,stockEffect:'add'}])];
 const r=S.forecast(s,s.skus[0].sku);a.equal(r.firstShortage,null);a.equal(r.historicalShortage,S.shift(s.snapshot.date,1));a.equal(r.days.find(d=>d.date===S.today()).balance,99);
});
test('online demand uses eligible units, excludes manual/cancelled/processing records and exposes missing months',()=>{const order=(status,platform,date,qty)=>({status,platform,date,lines:[{sku:'SKU',qty}]});const records=[order('Completed','Shopee','2026-09-28',70),order('To Ship','TikTok','2026-09-15',30),order('Canceled','Shopee','2026-09-28',999),order('Completed','Manual','2026-09-28',999),order('Platform Processing','Shopee','2026-09-28',999)];let r=S.demand(records,'2026-09-30',['2026-09']);a.equal(r.rows[0].rate7,10);a.equal(r.rows[0].units30,100);a.equal(r.coverage,true);r=S.demand(records,'2026-10-01',['2026-09']);a.equal(r.coverage,false);a.deepEqual(r.missingMonths,['2026-10']);});

test('unreceived ETA before today stays overdue even with an older snapshot; new orders use today for lead time',()=>{const s=fixture();s.pos=[po('P','2026-09-21',5000)];const r=S.forecast(s,s.skus[0].sku,'2026-09-25');a.equal(r.overdue.length,1);a.equal(r.days.find(d=>d.date==='2026-09-21').inbound,0);a.equal(r.proposedETA,'2026-11-09');});

test('historical exact sales SKUs have a confirmed zero rate when the latest window has no units',()=>{const r=S.demand([{date:'2026-08-01',status:'Completed',platform:'Shopee',lines:[{sku:'OLD',qty:100}]},{date:'2026-09-30',status:'Completed',platform:'Shopee',lines:[{sku:'NEW',qty:300}]}],null,['2026-09']);a.equal(r.rows.find(x=>x.sku==='OLD').rate30,0);a.equal(r.rows.find(x=>x.sku==='NEW').rate30,10);});
test('derived sales rates leave offline demand, manual fallbacks and purchase orders intact',()=>{const s=fixture();s.skus[0].offline=5;s.pos=[po('P','2026-10-16',2000)];const before=JSON.stringify(s);const report={coverage:true,end:'2026-09-30',rows:[{sku:s.skus[0].sku,rate30:100,rate7:200}]};const auto=S.applyDemand(s,report,30);a.equal(auto.skus[0].rate,100);a.equal(auto.skus[0].offline,5);a.equal(S.applyDemand(s,report,7).skus[0].rate,200);a.equal(auto.pos[0].lines[0].qty,2000);a.equal(JSON.stringify(s),before);a.equal(S.applyDemand(s,{...report,coverage:false}).skus[0].rate,null);a.equal(S.applyDemand(s,{...report,rows:[]}).skus[0].rate,50);});
test('cancelled-only online SKUs get zero demand and the latest imported date defines the window',()=>{const r=S.demand([{date:'2026-08-01',status:'Completed',platform:'Shopee',lines:[{sku:'OLD',qty:100}]},{date:'2026-09-30',status:'Canceled',platform:'Shopee',lines:[{sku:'CANCEL',qty:300}]}],null,['2026-09']);a.equal(r.end,'2026-09-30');a.equal(r.coverage,true);a.equal(r.rows.find(x=>x.sku==='OLD').rate30,0);a.equal(r.rows.find(x=>x.sku==='CANCEL').rate30,0);});

test('Max and Min use combined daily SKU units, including zero days, rather than individual orders',()=>{
 const order=(date,qty,status='Completed',platform='Shopee')=>({date,status,platform,lines:[{sku:'SKU',qty}]});
 const records=[order('2026-09-24',10),order('2026-09-24',90),order('2026-09-25',20),order('2026-09-26',30),order('2026-09-27',40),order('2026-09-28',50),order('2026-09-29',60),order('2026-09-30',70),order('2026-09-01',1000),order('2026-09-30',9999,'Canceled'),order('2026-09-30',9999,'Completed','Manual')];
 const report=S.demand(records,'2026-09-30',['2026-09']),row=report.rows[0];
 a.equal(report.statsVersion,2);a.equal(row.max7,100);a.equal(row.min7,20);a.equal(row.max30,1000);a.equal(row.min30,0);a.equal(row.rate7,370/7);a.equal(row.rate30,1370/30);
 a.equal('daily' in row,false);
 const state=fixture();state.skus[0].sku='SKU';state.snapshot.rows[0].sku='SKU';state.skus[0].offline=5;state.pos=[po('P','2026-11-10',2000)];const original=JSON.stringify(state);
 a.equal(S.applyDemand(state,report,7,'max').skus[0].rate,100);a.equal(S.applyDemand(state,report,7,'min').skus[0].rate,20);a.equal(S.applyDemand(state,report,30,'min').skus[0].rate,0);a.equal(S.forecast(S.applyDemand(state,report,7,'max'),'SKU',state.snapshot.date).rate,105);a.equal(JSON.stringify(state),original);
 a.equal(S.applyDemand(state,{...report,coverage:false},7,'max').skus[0].rate,null);
 a.equal(S.applyDemand(state,{...report,rows:[{sku:'SKU',rate30:25}]},30,'max').skus[0].rate,null);
});
