const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{JSDOM}=require('../backend/node_modules/jsdom'),S=require('../assets/stock-engine');
const flush=async()=>{for(let n=0;n<10;n++)await new Promise(r=>setImmediate(r));};
function fixture(){const s=S.empty();s.snapshot={date:'2026-09-01',fileName:'inventory.xlsx',rows:[{sku:'Wiper_Size14_Pack01',title:'Wiper',warehouse:'Main Warehouse',onhand:13,incoming:2000}]};s.settings.warehouses=['Main Warehouse'];s.skus=[{sku:'Wiper_Size14_Pack01',category:'wiper',rate:100,offline:0,growth:0,rateSource:'Manual'}];s.pos=[{id:'p',number:'PO1',supplier:'Factory',orderDate:'2026-08-01',status:'confirmed',lines:[{id:'l',sku:'Wiper_Size14_Pack01',qty:2000,warehouse:'Main Warehouse',eta:'2026-10-15',receipts:[]}]}];return s;}
function harness(role='admin'){const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'../stock-forecast.html'),'utf8'),{url:'https://nakamaauto.com/stock-forecast.html',runScripts:'outside-only'}),w=dom.window,ctx=dom.getInternalVMContext();let cb,updated,savedCalls=0,savedState=null,pending=null,rates={coverage:true,end:'2026-09-30',from:'2026-09-01',rows:[]};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.confirm=()=>true;w.cloudMock={start:async(fn,onError,onUpdate)=>{cb=fn;updated=onUpdate;await fn({user:{uid:'u'},role});},stockDemand:async()=>typeof rates==='function'?await rates():rates,stockForecast:async()=>pending?await pending:{state:fixture(),revision:'rev'},saveStockForecast:async state=>{savedCalls++;savedState=structuredClone(state);return {state,revision:'next'};},signOut:async()=>cb(null),authError:e=>e.message};vm.runInContext(fs.readFileSync(path.join(__dirname,'../assets/stock-engine.js'),'utf8'),ctx);const source=fs.readFileSync(path.join(__dirname,'../assets/stock-forecast.js'),'utf8').replace(/import\('\.\/cloud\.js\?v=[^']+'\)/,'Promise.resolve(cloudMock)');vm.runInContext(source,ctx);return {dom,w,revoke:()=>cb({blocked:true,user:{uid:'u'}}),delay:p=>{pending=p;},savedCalls:()=>savedCalls,savedState:()=>savedState,report:r=>{rates=r;},update:()=>updated()};}
test('stock page uses On Hand and keeps ordered quantities fixed when rates change',async()=>{const h=harness();await flush();const el=id=>h.w.document.getElementById(id);a.equal(el('stock-total').textContent,'13');el('stock-rows').querySelector('[data-sku]').click();el('sku-rate').value='200';el('sku-form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));a.match(el('sku-summary').textContent,/Daily demand 200/);a.match(el('sku-po-rows').textContent,/2,000/);a.equal(el('save-status').textContent,'Unsaved changes');el('save').click();await flush();a.equal(h.savedCalls(),1);a.equal(el('save-status').textContent,'Saved to shared workspace');await h.revoke();a.equal(el('stock-workspace').hidden,true);for(const id of ['stock-rows','po-rows','sku-po-rows','sku-chart','po-lines'])a.equal(el(id).textContent,'');h.dom.window.close();});
test('workspace PO navigation preserves unsaved inventory and opens a focused register',async()=>{
 const h=harness();await flush();const el=id=>h.w.document.getElementById(id);el('stock-rows').querySelector('[data-sku]').click();el('sku-rate').value='200';el('sku-form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));el('sku-dialog').close();
 h.w.NKMStockNavigate('pos');a.equal(h.w.location.hash,'#pos');a.equal(el('stock-pos').hidden,false);a.equal(el('inventory-title').textContent,'Purchase Orders');a.equal(h.w.document.body.classList.contains('stock-po-view'),true);a.equal(el('save-status').textContent,'Unsaved changes');a.match(el('po-rows').textContent,/PO1/);
 h.w.NKMStockNavigate('overview');a.equal(el('stock-overview').hidden,false);a.equal(el('inventory-title').textContent,'Stock Forecast');el('stock-rows').querySelector('[data-sku]').click();a.equal(el('sku-rate').value,'200');a.equal(h.savedCalls(),0);h.dom.window.close();
});
test('viewers cannot edit, receive or save stock',async()=>{const h=harness('viewer');await flush();const el=id=>h.w.document.getElementById(id);a.equal(el('new-po').disabled,true);a.equal(el('upload-stock').disabled,true);a.equal(el('save').disabled,true);el('save').onclick();el('new-po').onclick();a.equal(el('po-dialog').open,false);a.equal(h.savedCalls(),0);h.dom.window.close();});
test('late stock response cannot repopulate a revoked session',async()=>{const h=harness();await flush();let finish;h.delay(new Promise(r=>{finish=r;}));h.w.document.getElementById('refresh').click();await flush();await h.revoke();finish({state:fixture(),revision:'late'});await flush();a.equal(h.w.document.getElementById('stock-workspace').hidden,true);a.equal(h.w.document.getElementById('stock-rows').textContent,'');h.dom.window.close();});

test('automatic rates update on new sales reports without saving or changing POs; viewer sees the same rates',async()=>{const h=harness('viewer');h.report({coverage:true,end:'2026-09-30',rows:[{sku:'Wiper_Size14_Pack01',rate7:70,rate30:30}]});await flush();const el=id=>h.w.document.getElementById(id);el('stock-rows').querySelector('[data-sku]').click();a.equal(el('sku-rate').value,'30');a.equal(el('sku-rate').readOnly,true);a.match(el('sku-summary').textContent,/Daily demand 30/);h.report({coverage:true,end:'2026-10-01',rows:[{sku:'Wiper_Size14_Pack01',rate7:200,rate30:100}]});h.update();await flush();a.equal(el('sku-rate').value,'100');a.match(el('sku-po-rows').textContent,/2,000/);a.equal(h.savedCalls(),0);el('rate-window').value='7';el('rate-window').dispatchEvent(new h.w.Event('change'));a.equal(el('sku-rate').value,'200');a.equal(el('save').disabled,true);h.dom.window.close();});
test('stock sidebar sections update active state, URL and content for every navigation control',async()=>{const h=harness();await flush();const doc=h.w.document;for(const tab of ['pos','overview'])for(const b of doc.querySelectorAll('[data-stock-tab="'+tab+'"]')){b.click();a.equal(h.w.location.hash,'#'+tab);a.equal(doc.getElementById('stock-pos').hidden,tab!=='pos');a.equal(doc.getElementById('stock-overview').hidden,tab!=='overview');a.equal(doc.querySelector('.sidebar [data-stock-tab="'+tab+'"]').classList.contains('active'),true);}a.equal(doc.querySelector('.sidebar a[href="management.html#stores"]').textContent,'Store Performance');h.dom.window.close();});
test('late automatic rate responses are discarded after revocation',async()=>{const h=harness();await flush();let finish;h.report(()=>new Promise(r=>{finish=r;}));h.update();await flush();await h.revoke();finish({coverage:true,end:'2026-10-01',rows:[{sku:'Wiper_Size14_Pack01',rate30:999,rate7:999}]});await flush();a.equal(h.w.document.getElementById('stock-workspace').hidden,true);a.equal(h.w.document.getElementById('stock-rows').textContent,'');a.equal(h.w.document.getElementById('rate-note').textContent,'');h.dom.window.close();});
test('automatic sync preserves unapplied SKU input and clears stale charts on sync failure',async()=>{const h=harness();h.report({coverage:true,end:'2026-09-30',rows:[{sku:'Wiper_Size14_Pack01',rate30:30,rate7:70}]});await flush();const el=id=>h.w.document.getElementById(id);el('stock-rows').querySelector('[data-sku]').click();el('sku-offline').value='11';h.report({coverage:true,end:'2026-10-01',rows:[{sku:'Wiper_Size14_Pack01',rate30:100,rate7:200}]});h.update();await flush();a.equal(el('sku-offline').value,'11');a.equal(el('sku-rate').value,'100');h.report(async()=>{throw Error('Network unavailable');});h.update();await flush();a.equal(el('sku-chart').querySelector('svg'),null);a.equal(el('sku-offline').value,'11');a.match(el('rate-note').textContent,/sync failed/);h.dom.window.close();});

test('switching Max, Min and Average immediately updates open charts, offline demand and suggestions without a save',async()=>{
 const h=harness('viewer');h.report({statsVersion:2,coverage:true,end:'2026-09-30',rows:[{sku:'Wiper_Size14_Pack01',rate7:70,rate30:30,max7:700,max30:900,min7:2,min30:0}]});await flush();const el=id=>h.w.document.getElementById(id);
 el('stock-rows').querySelector('[data-sku]').click();const totals=el('sku-po-rows').textContent;
 for(const [mode,expected] of [['max','900'],['min','0'],['average','30']]){el('rate-logic').value=mode;el('rate-logic').dispatchEvent(new h.w.Event('change'));a.equal(el('sku-rate').value,expected);a.match(el('sku-summary').textContent,new RegExp('Daily demand '+expected));a.ok(el('sku-chart').querySelector('svg'));a.equal(el('sku-po-rows').textContent,totals);a.equal(el('save').disabled,true);}
 el('rate-logic').value='max';el('rate-logic').dispatchEvent(new h.w.Event('change'));el('rate-window').value='7';el('rate-window').dispatchEvent(new h.w.Event('change'));a.equal(el('sku-rate').value,'700');a.equal(h.savedCalls(),0);h.dom.window.close();
});
test('stock and PO headers sort numeric quantities, missing dates and metric help works by keyboard',async()=>{
 const h=harness();const state=fixture();state.snapshot.rows.push({...state.snapshot.rows[0],sku:'B',onhand:100});state.skus.push({...state.skus[0],sku:'B'});state.pos.push({...structuredClone(state.pos[0]),id:'p2',number:'PO2',lines:[{...structuredClone(state.pos[0].lines[0]),qty:100,sku:'B',eta:'2026-12-01'}]});h.delay(Promise.resolve({state,revision:'rev'}));await flush();const doc=h.w.document,button=(group,key)=>doc.querySelector('[data-sort-group="'+group+'"][data-sort="'+key+'"]');
 button('stock','onhand').click();a.equal(doc.querySelector('#stock-rows [data-sku]').dataset.sku,'Wiper_Size14_Pack01');a.equal(button('stock','onhand').closest('th').getAttribute('aria-sort'),'ascending');button('stock','onhand').click();a.equal(doc.querySelector('#stock-rows [data-sku]').dataset.sku,'B');
 button('po','ordered').click();a.match(doc.querySelector('#po-rows tr').textContent,/PO2/);button('po','ordered').click();a.match(doc.querySelector('#po-rows tr').textContent,/PO1/);
 const help=doc.querySelector('[data-help]');help.focus();a.ok(doc.querySelector('[role="tooltip"]'));doc.body.focus();help.blur();a.equal(doc.querySelector('[role="tooltip"]'),null);h.dom.window.close();
});
test('opaque sales transport failure keeps stock/PO workspace usable and missing rates unavailable',async()=>{
 const h=harness();h.report(async()=>{const error=Error('internal [0]');error.code='functions/internal';throw error;});await flush();const el=id=>h.w.document.getElementById(id);a.equal(el('stock-workspace').hidden,false);a.equal(el('upload-stock').disabled,false);a.equal(el('new-po').disabled,false);a.match(el('stock-error').textContent,/Sales sync could not reach/);a.doesNotMatch(el('stock-error').textContent,/internal \[0\]/);a.match(el('stock-rows').textContent,/Set rate/);a.match(el('po-rows').textContent,/2,000/);h.dom.window.close();
});
test('failed initial stock load cannot enable editing or overwrite an unknown shared workspace',async()=>{
 const h=harness();h.delay(Promise.reject(Object.assign(Error('internal [0]'),{code:'functions/internal'})));await flush();const el=id=>h.w.document.getElementById(id);a.equal(el('stock-workspace').hidden,true);a.equal(el('upload-stock').disabled,true);a.equal(el('save').disabled,true);a.match(el('stock-error').textContent,/shared stock workspace/);a.equal(h.savedCalls(),0);h.dom.window.close();
});

test('weekly calendar retains stockouts before replenishment, switches sales modes and clears private data on revocation',async()=>{
 const h=harness('viewer'),state=fixture(),sku=state.skus[0].sku,today=S.today(),weekday=new Date(today+'T00:00:00Z').getUTCDay(),monday=S.shift(today,8-(weekday||7));
 state.snapshot.date=S.shift(monday,-1);state.snapshot.rows[0].onhand=2;state.settings.horizon=30;state.pos[0].lines[0].eta=S.shift(monday,4);state.pos[0].lines[0].qty=20;
 h.delay(Promise.resolve({state,revision:'rev'}));h.report({statsVersion:2,coverage:true,end:today,rows:[{sku,rate7:1,rate30:1,max7:4,max30:4,min7:0,min30:0}]});await flush();const doc=h.w.document,el=id=>doc.getElementById(id),cell=()=>doc.querySelector('#calendar-rows [data-week="'+monday+'"]');
 a.equal(cell().querySelector('.calendar-balance').textContent,'17');a.ok(cell().classList.contains('calendar-stockout'));a.match(cell().textContent,/Stockout/);a.match(cell().textContent,/\+20 PO units/);
 el('rate-logic').value='min';el('rate-logic').dispatchEvent(new h.w.Event('change'));a.equal(cell().querySelector('.calendar-balance').textContent,'22');a.equal(cell().classList.contains('calendar-stockout'),false);a.equal(h.savedCalls(),0);
 cell().querySelector('button').click();a.equal(el('sku-dialog').open,true);el('sku-dialog').close();
 for(let i=0;i<2&&!el('calendar-next').disabled;i++)el('calendar-next').click();a.match(el('calendar-rows').textContent,/partial week/);a.equal(el('calendar-next').disabled,true);
 el('sku-search').value='NO_MATCH';el('sku-search').dispatchEvent(new h.w.Event('input'));a.match(el('calendar-rows').textContent,/No SKUs match/);
 await h.revoke();for(const id of ['calendar-rows','calendar-head','calendar-month','calendar-caption'])a.equal(el(id).textContent,'');h.dom.window.close();
});

test('weekly calendar labels unavailable rates and does not color them as zero stock',async()=>{
 const h=harness();h.report({statsVersion:2,coverage:false,end:S.today(),rows:[]});await flush();const doc=h.w.document;
 a.match(doc.getElementById('calendar-rows').textContent,/Unavailable/);a.equal(doc.querySelector('#calendar-rows .calendar-stockout'),null);
 doc.querySelector('[data-stock-tab="pos"]').click();a.equal(doc.getElementById('stock-calendar').hidden,true);h.dom.window.close();
});

test('receipts default to independent additions, persist their treatment, and existing receipt history can be reconciled',async()=>{
 const h=harness(),state=fixture(),sku=state.skus[0].sku;state.snapshot.date=S.today();state.pos[0].lines[0].eta=S.today();h.delay(Promise.resolve({state,revision:'rev'}));h.report({statsVersion:2,coverage:true,end:S.today(),rows:[{sku,rate30:1,rate7:1}]});await flush();const doc=h.w.document,el=id=>doc.getElementById(id);
 doc.querySelector('[data-receive]').click();a.equal(el('receipt-stock-effect').value,'add');el('receipt-qty').value='100';el('receipt-form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));a.equal(el('receipt-dialog').open,false);doc.querySelector('#stock-rows [data-sku]').click();a.match(el('sku-summary').textContent,/On Hand 113/);el('sku-dialog').close();
 doc.querySelector('[data-po]').click();const choice=doc.querySelector('[data-receipt-id]');a.equal(choice.value,'add');choice.value='included';el('po-form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));doc.querySelector('#stock-rows [data-sku]').click();a.match(el('sku-summary').textContent,/On Hand 13/);h.dom.window.close();
});


function receiptFixture(){const state=fixture();state.snapshot.date=S.today();state.pos[0].lines[0].receipts=[{id:'actual-receipt',date:S.today(),qty:2000,stockEffect:'add'}];return state;}
test('fully received PO receipt quantity and date can be corrected; stock and open quantity recalculate on apply and persist on save',async()=>{
 const h=harness(),state=receiptFixture();h.delay(Promise.resolve({state,revision:'rev'}));await flush();const doc=h.w.document,el=id=>doc.getElementById(id);a.match(el('po-rows').textContent,/received/);a.equal(el('stock-total').textContent,'2,013');
 doc.querySelector('[data-po]').click();doc.querySelector('[data-receipt-field=qty]').value='1200';doc.querySelector('[data-receipt-field=date]').value=S.shift(S.today(),-1);doc.querySelector('[data-receipt-field=qty]').dispatchEvent(new h.w.Event('input',{bubbles:true}));a.match(doc.querySelector('[data-receipt-summary]').textContent,/1,200.*800/);a.equal(el('stock-total').textContent,'2,013');a.equal(h.savedCalls(),0);
 el('po-form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));a.equal(el('po-dialog').open,false);a.equal(el('stock-total').textContent,'1,213');a.match(el('po-rows').textContent,/partially received/);a.equal(doc.querySelector('[data-receive]').disabled,false);el('save').click();await flush();const saved=h.savedState();a.equal(saved.pos[0].lines[0].receipts[0].id,'actual-receipt');a.equal(saved.pos[0].lines[0].receipts[0].date,S.shift(S.today(),-1));a.equal(saved.pos[0].lines[0].receipts[0].qty,1200);a.equal(S.remaining(saved.pos[0].lines[0]),800);a.equal(saved.pos[0].lines[0].qty,2000);a.equal(h.savedCalls(),1);h.dom.window.close();
});
test('removing a test receipt reverses its stock addition and reopens a fully received PO without deleting the PO',async()=>{
 const h=harness();h.delay(Promise.resolve({state:receiptFixture(),revision:'rev'}));await flush();const doc=h.w.document,el=id=>doc.getElementById(id);doc.querySelector('[data-po]').click();doc.querySelector('[data-remove-receipt]').click();a.equal(doc.querySelector('[data-receipt-row]'),null);a.match(el('po-lines').textContent,/No receipts recorded/);a.equal(el('stock-total').textContent,'2,013');
 el('po-form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));a.equal(el('stock-total').textContent,'13');a.match(el('po-rows').textContent,/confirmed/);a.equal(doc.querySelector('[data-receive]').disabled,false);el('save').click();await flush();a.equal(h.savedState().pos.length,1);a.equal(h.savedState().pos[0].lines[0].receipts.length,0);a.equal(S.remaining(h.savedState().pos[0].lines[0]),2000);h.dom.window.close();
});
test('closing the PO dialog discards unapplied receipt edits and removal',async()=>{
 const h=harness();h.delay(Promise.resolve({state:receiptFixture(),revision:'rev'}));await flush();const doc=h.w.document,el=id=>doc.getElementById(id);doc.querySelector('[data-po]').click();doc.querySelector('[data-receipt-field=qty]').value='20';doc.querySelector('[data-remove-receipt]').click();doc.querySelector('[data-close=po-dialog]').click();a.equal(el('stock-total').textContent,'2,013');a.equal(el('save').disabled,true);doc.querySelector('[data-po]').click();a.equal(doc.querySelector('[data-receipt-field=qty]').value,'2000');a.equal(h.savedCalls(),0);h.dom.window.close();
});
test('over-receipts and invalid dates are rejected without changing the received PO',async()=>{
 const h=harness();h.delay(Promise.resolve({state:receiptFixture(),revision:'rev'}));await flush();const doc=h.w.document,el=id=>doc.getElementById(id);doc.querySelector('[data-po]').click();const qty=doc.querySelector('[data-receipt-field=qty]'),date=doc.querySelector('[data-receipt-field=date]');qty.value='2001';el('po-form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));a.match(el('po-error').textContent,/exceeds ordered/);a.equal(el('po-dialog').open,true);a.equal(el('stock-total').textContent,'2,013');
 qty.value='100';date.value=S.shift(S.today(),1);el('po-form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));a.match(el('po-error').textContent,/Receipt date or quantity is invalid/);a.equal(el('save').disabled,true);date.value='2026-07-31';el('po-form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));a.match(el('po-error').textContent,/Receipt date or quantity is invalid/);a.equal(h.savedCalls(),0);h.dom.window.close();
});
test('receipt edits stay attached to the correct SKU when a PO has multiple lines and receipts',async()=>{
 const h=harness(),state=receiptFixture();state.pos[0].lines[0].receipts=[{id:'r1',date:S.today(),qty:300,stockEffect:'add'},{id:'r2',date:S.today(),qty:700,stockEffect:'included'}];state.pos[0].lines.push({...structuredClone(state.pos[0].lines[0]),id:'second-line',sku:'Spray_A',receipts:[{id:'r3',date:S.today(),qty:500,stockEffect:'add'}]});h.delay(Promise.resolve({state,revision:'rev'}));await flush();const doc=h.w.document,el=id=>doc.getElementById(id);doc.querySelector('[data-po]').click();doc.querySelector('[data-receipt-row=r1] [data-receipt-field=qty]').value='250';doc.querySelector('[data-receipt-row=r2] [data-remove-receipt]').click();el('add-po-line').click();a.equal(doc.querySelectorAll('.po-line').length,3);a.equal(doc.querySelector('[data-receipt-row=r1] [data-receipt-field=qty]').value,'250');doc.querySelector('.po-line:last-child [data-remove-line]').click();el('po-form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));el('save').click();await flush();const lines=h.savedState().pos[0].lines;a.deepEqual(lines[0].receipts.map(r=>[r.id,r.qty]),[['r1',250]]);a.equal(lines[1].receipts[0].id,'r3');a.equal(lines[1].receipts[0].qty,500);h.dom.window.close();
});
test('correction to a receipt already included in the snapshot does not subtract or add its stock again',async()=>{
 const h=harness(),state=receiptFixture();state.pos[0].lines[0].receipts[0].stockEffect='included';h.delay(Promise.resolve({state,revision:'rev'}));await flush();const doc=h.w.document,el=id=>doc.getElementById(id);a.equal(el('stock-total').textContent,'13');doc.querySelector('[data-po]').click();doc.querySelector('[data-receipt-field=qty]').value='400';el('po-form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));a.equal(el('stock-total').textContent,'13');doc.querySelector('[data-po]').click();doc.querySelector('[data-remove-receipt]').click();el('po-form').dispatchEvent(new h.w.Event('submit',{cancelable:true}));a.equal(el('stock-total').textContent,'13');h.dom.window.close();
});
