const {test}=require('node:test'),assert=require('node:assert/strict'),factory=require('../functions/lib/accounts');
function harness(){
 const data=new Map(),users=new Map(),requests=[];let clock=100000,fetchResult={ok:true,idToken:'good'};
 const fail=(code,message)=>{throw Object.assign(Error(message),{code});};
 const snap=key=>({id:key.split('/').at(-1),exists:data.has(key),data:()=>data.get(key)});
 const ref=key=>({key,get:async()=>snap(key),set:async(value,options)=>{data.set(key,options?.merge?{...data.get(key),...value}:value);}});
 const db={doc:ref,runTransaction:async fn=>fn({get:async r=>snap(r.key),set:(r,v,o)=>data.set(r.key,o?.merge?{...data.get(r.key),...v}:v),create:(r,v)=>{if(data.has(r.key))throw Error('exists');data.set(r.key,v);},delete:r=>data.delete(r.key)}),collection:()=>({orderBy(){return this;},limit(){return this;},startAfter(){return this;},get:async()=>({docs:[...data.keys()].filter(k=>k.startsWith('accountProfiles/')).map(snap)})})};
 const auth={createUser:async u=>{if([...users.values()].some(v=>v.email.toLowerCase()===u.email.toLowerCase()))fail('auth/email-already-exists','Duplicate');const {password,...rest}=u;users.set(u.uid,{...rest,customClaims:{}});},getUser:async uid=>{if(!users.has(uid))fail('auth/user-not-found','Missing');return users.get(uid);},verifyIdToken:async token=>{if(token!=='good')fail('bad-token','Bad token');return {uid:requests.at(-1)?.uid};},setCustomUserClaims:async(uid,claims)=>{users.get(uid).customClaims=claims;},revokeRefreshTokens:async uid=>{users.get(uid).revoked=true;}};
 const member=async(r,roles)=>{const u=users.get(r.auth?.uid),m=data.get('members/'+r.auth?.uid);if(!u||u.disabled||!m?.enabled||m.role!==u.customClaims?.nakamaRole||!roles.includes(m.role))fail('permission-denied','No admin access');return {uid:u.uid,role:m.role};};
 const api=factory({db,auth,fail,member,apiKey:'public-key',now:()=>clock,fetchImpl:async(url,options)=>{const body=JSON.parse(options.body);requests.push({...body,uid:[...users.values()].find(u=>u.email===body.email)?.uid});return {ok:fetchResult.ok,json:async()=>fetchResult};}});
 const request=(data,uid,ip='test-ip')=>({data,auth:uid?{uid}:null,rawRequest:{ip}});
 return {api,data,users,requests,request,setFetch:v=>fetchResult=v,tick:()=>clock+=60001,admin:()=>{users.set('admin',{uid:'admin',email:'admin@example.com',emailVerified:false,customClaims:{nakamaRole:'admin',unrelated:true}});data.set('members/admin',{enabled:true,role:'admin'});}};
}
test('registration accepts unrelated email providers, creates no membership or role, and never stores password',async()=>{const h=harness();const result=await h.api.register(h.request({userId:'Arun.Test',email:'user@hotmail.com',password:'  My Password!  ',role:'admin'}));assert.equal(result.userId,'arun.test');assert.equal(result.status,'pending');const uid=h.data.get('userIds/arun.test').uid;assert.equal(h.data.get('members/'+uid),undefined);assert.deepEqual(h.users.get(uid).customClaims,{});assert.equal(h.data.get('accountProfiles/'+uid).verificationRequired,true);assert.doesNotMatch(JSON.stringify([...h.data.values()]),/My Password/);});
test('case-insensitive duplicates fail without replacing the original alias; duplicate emails release their reservation',async()=>{const h=harness();await h.api.register(h.request({userId:'Arun',email:'one@gmail.com',password:'StrongPass!'}));const uid=h.data.get('userIds/arun').uid;await assert.rejects(h.api.register(h.request({userId:'ARUN',email:'two@outlook.com',password:'StrongPass!'})),{code:'already-exists'});assert.equal(h.data.get('userIds/arun').uid,uid);await assert.rejects(h.api.register(h.request({userId:'another',email:'one@gmail.com',password:'StrongPass!'})),{code:'already-exists'});assert.equal(h.data.has('userIds/another'),false);});
test('User ID login does not reveal email for unknown IDs or incorrect passwords and checks token UID',async()=>{const h=harness();await h.api.register(h.request({userId:'username',email:'one@icloud.com',password:'StrongPass!'}));await assert.rejects(h.api.login(h.request({userId:'missing',password:'StrongPass!'})),{code:'unauthenticated'});h.setFetch({ok:false});await assert.rejects(h.api.login(h.request({userId:'username',password:'wrong'})),{code:'unauthenticated'});h.setFetch({ok:true,idToken:'bad'});await assert.rejects(h.api.login(h.request({userId:'username',password:'wrong'})),{code:'unauthenticated'});h.setFetch({ok:true,idToken:'good'});assert.deepEqual(await h.api.login(h.request({userId:'USERNAME',password:'  Exact password!  '})),{email:'one@icloud.com'});assert.equal(h.requests.at(-1).password,'  Exact password!  ');assert.equal(h.data.get('members/'+h.data.get('userIds/username').uid),undefined);});
test('existing users choose a unique ID without changing their password, membership or unrelated claims',async()=>{const h=harness();h.admin();const before={...h.users.get('admin').customClaims};const p=await h.api.link(h.request({userId:'owner'},'admin'));assert.equal(p.status,'active');assert.deepEqual(h.users.get('admin').customClaims,before);assert.equal(h.data.get('members/admin').enabled,true);await assert.rejects(h.api.link(h.request({userId:'different'},'admin')),{code:'failed-precondition'});await assert.rejects(h.api.link(h.request({userId:'somebody'})),{code:'unauthenticated'});});
test('approval requires a verified email and an enabled admin; pending accounts cannot list or approve users',async()=>{const h=harness();h.admin();await h.api.register(h.request({userId:'newuser',email:'user@yahoo.com',password:'StrongPass!'}));const uid=h.data.get('userIds/newuser').uid;await assert.rejects(h.api.list(h.request({},uid)),{code:'permission-denied'});await assert.rejects(h.api.review(h.request({uid,action:'approve',role:'admin'},uid)),{code:'permission-denied'});await assert.rejects(h.api.review(h.request({uid,action:'approve',role:'viewer'},'admin')),{code:'failed-precondition'});assert.equal(h.data.has('members/'+uid),false);h.users.get(uid).emailVerified=true;await h.api.review(h.request({uid,action:'approve',role:'importer'},'admin'));assert.deepEqual(h.data.get('members/'+uid),{enabled:true,role:'importer'});assert.equal(h.users.get(uid).customClaims.nakamaRole,'importer');assert.equal((await h.api.profile(h.request({},uid))).status,'active');await h.api.review(h.request({uid,action:'disable'},'admin'));assert.equal(h.data.get('members/'+uid).enabled,false);assert.equal(h.users.get(uid).customClaims.nakamaRole,undefined);assert.equal(h.users.get(uid).revoked,true);});
test('self access changes and invalid roles are rejected; revoked admin cannot review',async()=>{const h=harness();h.admin();await assert.rejects(h.api.review(h.request({uid:'admin',action:'disable'},'admin')),{code:'failed-precondition'});await assert.rejects(h.api.review(h.request({uid:'target',action:'approve',role:'super_admin'},'admin')),{code:'invalid-argument'});h.data.get('members/admin').enabled=false;await assert.rejects(h.api.review(h.request({uid:'target',action:'approve',role:'viewer'},'admin')),{code:'permission-denied'});});
test('malformed identifiers are rejected and repeated password attempts are rate limited',async()=>{const h=harness();await assert.rejects(h.api.register(h.request({userId:'../foo',email:'user@gmail.com',password:'StrongPass!'})),{code:'invalid-argument'});for(let i=0;i<10;i++)await assert.rejects(h.api.login(h.request({userId:'unknown',password:'pass'})),{code:'unauthenticated'});await assert.rejects(h.api.login(h.request({userId:'unknown',password:'pass'})),{code:'resource-exhausted'});h.tick();await assert.rejects(h.api.login(h.request({userId:'unknown',password:'pass'})),{code:'unauthenticated'});});
