const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),zlib=require('node:zlib');
const C=require('../functions/lib/core'),E=require('../functions/lib/engine'),Customer=require('../functions/lib/customer'),Stock=require('../functions/lib/stock-engine');
const revision='11111111-1111-4111-8111-111111111111',manifestPath=`private/revisions/${revision}/orders.manifest.json`;
const order=(i,product='Wiper')=>({key:JSON.stringify(['Shopee','NKM_SHP',String(i)]),id:String(i),date:'2026-09-08',store:'NKM_SHP',marketplaceStore:'NAKAMA',platform:'Shopee',status:'Completed',sourceBatch:'20261001101409972',customer:{version:1,buyerHash:'a'.repeat(64),province:'กรุงเทพมหานคร',country:'Thailand'},lines:[{sku:'WIPER',product,price:59,qty:1,status:'Completed',variation:'21/19 DMAX'}]});
async function storage(records){const objects=new Map(),writes=[];await C.saveSnapshot(records,manifestPath,async(path,bytes,type)=>{objects.set(path,bytes);writes.push({path,type});});return {objects,writes,download:async path=>{if(!objects.has(path))throw Object.assign(Error('Missing'),{code:404});return objects.get(path);},manifest:()=>JSON.parse(objects.get(manifestPath))};}
test('raw parsing releases unused export columns and preserves all sales/customer enrichment fields',()=>{
 const X=require('../functions/lib/vendor/xlsx.full.min.js'),headers=['Receiver Name','Order No','Order Time','BigSeller Store Nickname','Marketplace','Order Status','Merchant SKU','Product Name','Quantity','Price','Shipping Address','Username (Buyer)','Province (State)','Variation Name','Customer Code','Country','Marketplace Store','Order Item ID'],rows=[['Private receiver','123456789012345678','2026-09-08 10:00','NKM_SHP','Shopee','Completed','WIPER','Wiper',1,59,'Private address','buyer','กรุงเทพมหานคร','21/19 DMAX','','Thailand','NAKAMA','item1']],w=X.utils.book_new();X.utils.book_append_sheet(w,X.utils.aoa_to_sheet([headers,...rows]),'Orders');
 const parsed=C.parse(X.write(w,{type:'buffer',bookType:'xlsx'}),'orders.xlsx');a.equal(parsed.headers.includes('Shipping Address'),false);a.equal(parsed.headers.includes('Receiver Name'),false);a.equal(parsed.rows.length,1);a.deepEqual(C.calculate([parsed],[],Buffer.alloc(32,7)),C.calculate([{name:'orders.xlsx',headers,rows}],[],Buffer.alloc(32,7)));
});
test('new snapshot round trips preserve order identities, item statuses, hashes, exclusions and extra metadata; legacy gzip remains readable',async()=>{
 const rows=[order(1),{...order(2),partialCanceled:true,lines:[...order(2).lines,{sku:'CANCEL',product:'Other',qty:2,price:10,status:'Canceled'}]},{...order(3),excluded:true,status:'Platform Processing',lines:[],futureMetadata:{retain:true}}],s=await storage(rows);
 a.deepEqual(await C.readSnapshot(manifestPath,s.download),rows);a.equal(s.writes.at(-1).path,manifestPath);a.equal(s.writes.at(-1).type,'application/json');a.equal(s.writes[0].type,'application/gzip');
 a.deepEqual(await C.readSnapshot('private/revisions/old/orders.json.gz',async()=>C.snapshot(rows)),rows);
 const empty=await storage([]);a.deepEqual(await C.readSnapshot(manifestPath,empty.download),[]);
});
test('history above the previous 256 MiB limit uses bounded parts and retains report, customer and demand totals',async()=>{
 const title='ใบปัดน้ำฝน'.repeat(90),count=Math.ceil((C.LIMITS.snapshotBytes+1024*1024)/Buffer.byteLength(JSON.stringify(order(999999,title))))+100,records=Array.from({length:count},(_,i)=>order(i,title)),s=await storage(records),m=s.manifest();
 a.ok(m.uncompressedBytes>C.LIMITS.snapshotBytes);a.ok(m.parts.length>1);a.equal(m.orders,count);a.ok(m.parts.every(p=>p.uncompressedBytes<=C.LIMITS.snapshotPartBytes));
 const restored=await C.readSnapshot(manifestPath,s.download);a.equal(restored.length,count);a.deepEqual(restored[0],records[0]);a.deepEqual(restored.at(-1),records.at(-1));a.deepEqual(E.aggregate(restored),E.aggregate(records));
 const args={from:'2026-09-01',to:'2026-09-30',basis:'completed'};a.deepEqual(Customer.summary(restored,args),Customer.summary(records,args));a.deepEqual(Stock.demand(restored,'2026-09-08',['2026-08','2026-09']),Stock.demand(records,'2026-09-08',['2026-08','2026-09']));
 a.equal(E.raw([],restored).orderCount,count);console.log(`Validated ${count} orders, ${(m.uncompressedBytes/1048576).toFixed(1)} MiB canonical history in ${m.parts.length} parts.`);
});
test('missing, corrupt, reordered, oversized and count-mismatched parts cannot be read as valid history',async()=>{
 const s=await storage([order(1)]),original=Buffer.from(s.objects.get(manifestPath)),p=s.manifest().parts[0],part=s.objects.get(p.path);
 s.objects.delete(p.path);await a.rejects(C.readSnapshot(manifestPath,s.download),e=>e.code==='data-loss');s.objects.set(p.path,Buffer.from(part));s.objects.get(p.path)[5]^=1;await a.rejects(C.readSnapshot(manifestPath,s.download),e=>e.code==='data-loss');s.objects.set(p.path,part);
 for(const change of [m=>m.parts[0].path='private/elsewhere',m=>m.parts[0].uncompressedBytes=C.LIMITS.snapshotPartBytes+1,m=>m.orders++,m=>m.uncompressedBytes=C.LIMITS.snapshotTotalBytes+1,m=>m.version=3]){const m=JSON.parse(original);change(m);s.objects.set(manifestPath,Buffer.from(JSON.stringify(m)));await a.rejects(C.readSnapshot(manifestPath,s.download),e=>e.code==='data-loss');}
 const wrong=zlib.gzipSync(Buffer.from('{}')),m=JSON.parse(original);m.parts[0]={...m.parts[0],bytes:wrong.length,uncompressedBytes:2,sha256:crypto.createHash('sha256').update(wrong).digest('hex')};m.uncompressedBytes=2;s.objects.set(p.path,wrong);s.objects.set(manifestPath,Buffer.from(JSON.stringify(m)));await a.rejects(C.readSnapshot(manifestPath,s.download),e=>e.code==='data-loss');
});
test('storage failure never writes a manifest and an oversized individual order fails explicitly',async()=>{
 const saved=[];await a.rejects(C.saveSnapshot([order(1)],manifestPath,async(path)=>{if(path.endsWith('.json.gz'))throw Error('Storage failed');saved.push(path);}),/Storage failed/);a.equal(saved.length,0);
 await a.rejects(C.saveSnapshot([order(1,'x'.repeat(C.LIMITS.snapshotPartBytes))],manifestPath,async()=>{}),e=>e.code==='resource-exhausted');
});
async function endpointHarness(records,{legacy=false,storageFailure=false,reportFailure=false}={}){
 const s=await storage(records),oldPath=legacy?`private/revisions/${revision}/orders.json.gz`:manifestPath;if(legacy)s.objects.set(oldPath,C.snapshot(records));
 const id='22222222-2222-4222-8222-222222222222',uploadPath=`uploads/u/${id}/0`,source=Buffer.from('Order No,Order Time,BigSeller Store Nickname,Marketplace,Order Status,Merchant SKU,Product Name,Quantity,Price\n0,2026-09-08 09:00,NKM_SHP,Shopee,Completed,WIPER,Wiper updated,2,59\n');
 s.objects.set(uploadPath,source);s.objects.set('private/internal/customer-identity-key',Buffer.alloc(32,7));const now=()=>({toMillis:()=>Date.now()}),docs=new Map([['members/u',{enabled:true,role:'admin'}],['workspace/main',{revision,months:['2026-09']}],['reports/'+revision,{state:'published',snapshot:oldPath}],['imports/'+id,{owner:'u',state:'uploading',expiresAt:{toMillis:()=>Date.now()+60000},files:{0:{index:'0',name:'orders.csv',size:source.length,contentType:'text/csv',lastModified:1}}}]]),saved=[],downloads=[];let enabled=true;
 const deleted=Symbol('delete'),update=(path,values)=>{const d={...docs.get(path)};for(const [k,v] of Object.entries(values)){if(v===deleted)delete d[k];else d[k]=v;}docs.set(path,d);},ref=path=>({path,get:async()=>({exists:docs.has(path),data:()=>docs.get(path)}),create:async data=>{a.equal(docs.has(path),false);docs.set(path,data);}});
 const db={doc:ref,runTransaction:async callback=>callback({get:r=>r.get(),set:(r,d)=>docs.set(r.path,d),update:(r,d)=>update(r.path,d),delete:r=>docs.delete(r.path)}),batch:()=>{const writes=[];return {set:(r,d)=>writes.push([r.path,d]),commit:async()=>{if(reportFailure)throw Error('Report write failed');for(const [p,d] of writes)docs.set(p,d);}};}};
 const bucket={file:path=>({name:path,getMetadata:async()=>[{size:source.length,contentType:'text/csv',generation:'1'}],download:async()=>{downloads.push(path);return [await s.download(path)];},save:async(bytes)=>{if(storageFailure&&path.includes('/orders/000001.json.gz'))throw Error('Part write failed');s.objects.set(path,bytes);saved.push(path);}})};
 const exports={},sandbox={exports,process:{env:{GCLOUD_PROJECT:'nakama-sales'}},console:{error:()=>{}},require:name=>name==='firebase-functions/v2/https'?{onCall:(opts,fn)=>fn,HttpsError:class extends Error{constructor(code,message,details){super(message);this.code=code;this.details=details;}}}:name==='firebase-admin/app'?{initializeApp:()=>{}}:name==='firebase-admin/firestore'?{getFirestore:()=>db,Timestamp:{now,fromMillis:value=>({toMillis:()=>value})},FieldValue:{delete:()=>deleted}}:name==='firebase-admin/auth'?{getAuth:()=>({getUser:async()=>({disabled:!enabled})})}:name==='firebase-admin/storage'?{getStorage:()=>({bucket:()=>bucket})}:name==='./lib/core'?C:name==='./lib/customer'?Customer:name==='./lib/stock-engine'?Stock:name==='./lib/ads-service'?require('../functions/lib/ads-service'):name==='./lib/accounts'?require('../functions/lib/accounts'):name==='./auth-config.json'?{apiKey:'test-public-key'}:require(name)};
 vm.runInNewContext(fs.readFileSync(require.resolve('../functions/index.js'),'utf8'),sandbox);const request=data=>({auth:{uid:'u',token:{nakamaRole:'admin'}},data});return {api:exports,docs,objects:s.objects,saved,downloads,run:(name,data)=>exports[name](request(data)),id,revoke:()=>{enabled=false;}};
}
test('production handlers migrate old revisions on import and all consumers can read new parts',async()=>{
 for(const legacy of [true,false]){const h=await endpointHarness([order(0),order(1)],{legacy});const done=await h.run('nkmProcessImport',{id:h.id});a.equal(done.state,'complete');a.equal(h.docs.get('workspace/main').revision,done.revision);const published=h.docs.get('reports/'+done.revision);a.equal(published.state,'published');a.ok(published.snapshot.endsWith('orders.manifest.json'));
 const rows=await C.readSnapshot(published.snapshot,async p=>h.objects.get(p));a.equal(rows.length,2);a.equal(rows.find(r=>r.id==='0').lines[0].qty,2);a.equal(rows.find(r=>r.id==='1').customer.buyerHash,'a'.repeat(64));
 const customer=await h.run('nkmCustomerInsights',{from:'2026-09-01',to:'2026-09-30',basis:'completed'});a.equal(customer.totals.orders,2);a.equal(customer.totals.units,3);a.equal(customer.totals.gmv,177);
 const demand=await h.run('nkmStockDemand',{end:'2026-09-08'});a.equal(demand.rows[0].units30,3);a.equal((await h.run('nkmProcessImport',{id:h.id})).revision,done.revision);
 const reads=h.downloads.length;h.revoke();await a.rejects(h.run('nkmCustomerInsights',{from:'2026-09-01',to:'2026-09-30'}),e=>e.code==='permission-denied');await a.rejects(h.run('nkmStockDemand',{end:'2026-09-08'}),e=>e.code==='permission-denied');a.equal(h.downloads.length,reads);}
});
test('later-part and report-write failures leave the published workspace and reports unchanged',async()=>{
 const records=Array.from({length:6500},(_,i)=>order(i,'ใบปัดน้ำฝน'.repeat(90)));
 for(const failure of [{storageFailure:true},{reportFailure:true}]){const h=await endpointHarness(records,failure);await a.rejects(h.run('nkmProcessImport',{id:h.id}),e=>e.code==='internal');a.equal(h.docs.get('workspace/main').revision,revision);a.equal(h.docs.get('reports/'+revision).state,'published');a.equal(h.docs.get('imports/'+h.id).state,'uploading');a.equal(h.docs.has('internal/importLease'),false);
 if(failure.storageFailure){a.ok(h.saved.some(p=>p.includes('/orders/000000.json.gz')));a.equal(h.saved.some(p=>p.endsWith('/orders.manifest.json')),false);}else {const draft=[...h.docs.entries()].find(([p,d])=>p.startsWith('reports/')&&d.state==='draft');a.ok(draft);a.notEqual(h.docs.get('workspace/main').revision,draft[0].slice(8));}
 const customer=await h.run('nkmCustomerInsights',{from:'2026-09-01',to:'2026-09-30',basis:'completed'});a.equal(customer.totals.orders,records.length);a.equal(customer.totals.units,records.length);}
});

