const {test}=require('node:test'),a=require('node:assert/strict'),C=require('../functions/lib/core');
const headers=['Order No','Order Time','BigSeller Store Nickname','Marketplace','Order Status','Merchant SKU','Product Name','Quantity','Price'];
const row=(id,qty=2,price=50)=>[id,'2026-09-01 09:00','NKM_SHP','Shopee','Completed','W24','Wiper',qty,price];
const parsed=(rows,name='orders.csv')=>C.parse(Buffer.from([headers,...rows].map(r=>r.join(',')).join('\n')),name),bad=(fn,code)=>a.throws(fn,e=>e.code===code);
test('verified membership, import roles, dedicated project',()=>{bad(()=>C.role(null,{}),'unauthenticated');bad(()=>C.role({uid:'v',token:{nakamaRole:'viewer'}},{enabled:true,role:'viewer'},['importer','admin']),'permission-denied');bad(()=>C.role({uid:'v',token:{nakamaRole:'admin'}},{enabled:false,role:'admin'}),'permission-denied');bad(()=>C.role({uid:'v',token:{nakamaRole:'admin'}},{enabled:true,role:'viewer'}),'permission-denied');a.equal(C.role({uid:'v',token:{nakamaRole:'viewer'}},{enabled:true,role:'viewer'}).role,'viewer');bad(()=>C.project('sss-attendance-prods'),'failed-precondition');a.equal(C.project('nakama-sales-cloud'),'nakama-sales-cloud');});
test('manifest size, names, exact MIME types, total bytes',()=>{const f={name:'orders.csv',size:100,lastModified:1};a.equal(C.manifest([f])[0].contentType,'text/csv');for(const name of ['../orders.csv','orders.json','a\\orders.csv'])bad(()=>C.manifest([{...f,name}]),'invalid-argument');bad(()=>C.manifest([f,f]),'invalid-argument');bad(()=>C.manifest([{...f,size:C.LIMITS.fileBytes+1}]),'invalid-argument');bad(()=>C.manifest(Array.from({length:5},(_,i)=>({...f,name:i+'.csv',size:C.LIMITS.fileBytes}))),'invalid-argument');});
test('server CSV and XLSX parsing: long IDs, zero values, malformed rows',()=>{const d=C.calculate([parsed([row('123456789012345678'),row('2',2,0),row('3',0,30)])]);a.equal(d.records[0].id,'123456789012345678');a.equal(d.daily[0].gmv,100);a.equal(d.daily[0].orders,3);a.equal(d.daily[0].units,4);bad(()=>C.calculate([parsed([row('4',-1)])]),'invalid-argument');bad(()=>C.parse(Buffer.from('a,b\n1,2'),'x.csv'),'invalid-argument');a.deepEqual(C.unpack(C.snapshot(d.records)),d.records);const X=require('../functions/lib/vendor/xlsx.full.min.js'),w=X.utils.book_new();X.utils.book_append_sheet(w,X.utils.aoa_to_sheet([headers,row('123456789012345678')]),'Orders');a.equal(C.calculate([C.parse(X.write(w,{type:'buffer',bookType:'xlsx'}),'orders.xlsx')]).daily[0].gmv,100);});
test('complete-order replacement, older exports, split parts',()=>{const old=parsed([row('1')],'Order-SKU-all20260901090000000.csv'),newer=parsed([row('1',3,70)],'Order-SKU-all20260902090000000.csv');const first=C.calculate([old]),second=C.calculate([newer],first.records),third=C.calculate([old],second.records);a.equal(second.daily[0].gmv,210);a.equal(third.daily[0].gmv,210);a.equal(third.records.length,1);const p1=parsed([row('1')],'Order-SKU-all20260903090000000(1).csv'),p2=parsed([row('1',1,20)],'Order-SKU-all20260903090000000(2).csv');a.equal(C.calculate([p1,p2]).daily[0].gmv,120);bad(()=>C.calculate([p2]),'invalid-argument');});
test('Platform Processing is excluded server-side and snapshots prevent older orders returning',()=>{const pp=row('1',1,'--');pp[4]='Platform Processing';const valid=row('2'),data=C.calculate([parsed([pp,valid])]);a.equal(data.diagnostics.invalid,0);a.equal(data.diagnostics.excludedRows,1);a.equal(data.diagnostics.excludedOrders,1);a.equal(data.orderCount,1);a.equal(data.daily[0].gmv,100);a.equal(data.daily[0].units,2);a.equal(data.daily[0].orders,1);a.equal(C.reports(data)[0].meta.gmv,100);a.equal(data.skus[0].gmv,100);const old=parsed([row('1')],'Order-SKU-all20260901090000000.csv'),newer=parsed([pp],'Order-SKU-all20260902090000000.csv'),updated=C.calculate([newer],C.calculate([old]).records);a.equal(updated.orderCount,0);a.deepEqual(C.reports(updated),[]);const stale=C.calculate([old],C.unpack(C.snapshot(updated.records)));a.equal(stale.orderCount,0);a.deepEqual(stale.daily,[]);a.equal(stale.diagnostics.older,1);const malformed=row('bad',1,'--');bad(()=>C.calculate([parsed([pp,malformed])]),'invalid-argument');});
test('document and page limits; pagination has no gaps or duplicates',async()=>{const rows=Array.from({length:4500},(_,i)=>({i,product:'p'.repeat(400),gmv:i})),chunks=C.packRows(rows);a.ok(chunks.length>1);for(const c of chunks)a.ok(Buffer.byteLength(JSON.stringify(c))<=C.LIMITS.chunkBytes);let cursor=null,out=[];do{const args=cursor?C.pageArgs({revision:C.randomId(),month:'2026-09',kind:'skus',cursor}):{chunk:0,offset:0},p=await C.page(async i=>chunks[i],chunks.length,args);a.ok(Buffer.byteLength(JSON.stringify(p))<=C.LIMITS.pageBytes);a.ok(p.rows.length<=500);out.push(...p.rows);cursor=p.nextCursor;}while(cursor);a.deepEqual(out,rows);await a.rejects(()=>C.page(async()=>[],1,{chunk:9,offset:0}),e=>e.code==='invalid-argument');await a.rejects(()=>C.page(async()=>null,1,{chunk:0,offset:0}),e=>e.code==='data-loss');a.deepEqual(await C.page(async()=>null,0,{chunk:0,offset:0}),{rows:[],nextCursor:null});bad(()=>C.pageArgs({revision:C.randomId(),month:'2026-13',kind:'daily'}),'invalid-argument');bad(()=>C.packRows([{text:'x'.repeat(C.LIMITS.pageBytes)}]),'resource-exhausted');});
test('expired, competing and superseded leases cannot publish',()=>{const l={token:'mine',expires:200};a.equal(C.leaseValid(l,'mine','r1','r1',100),true);a.equal(C.leaseValid(l,'other','r1','r1',100),false);a.equal(C.leaseValid(l,'mine','r1','r2',100),false);a.equal(C.leaseValid(l,'mine','r1','r1',201),false);});
test('warehouse processing and real sales sharing one ID keep only real sales',()=>{const pp=row('same',99,'--');pp[4]='Platform Processing';pp[1]='2026-08-02 17:00';const sale=row('same',1,59);sale[1]='2026-08-05 06:33';for(const rows of [[pp,sale],[sale,pp]]){const data=C.calculate([parsed(rows)]);a.equal(data.orderCount,1);a.equal(data.daily[0].gmv,59);a.equal(data.daily[0].units,1);a.equal(data.daily[0].date,'2026-08-05');a.equal(data.daily[0].status,'Completed');a.equal(data.diagnostics.excludedRows,1);a.equal(data.diagnostics.excludedOrders,0);a.equal(data.diagnostics.retainedSalesOrders,1);a.equal(C.reports(data)[0].meta.orders,1);const repeated=C.calculate([parsed(rows)],C.unpack(C.snapshot(data.records)));a.equal(repeated.daily[0].gmv,59);a.equal(repeated.orderCount,1);}const conflict=[...sale];conflict[4]='Canceled';bad(()=>C.calculate([parsed([pp,sale,conflict])]),'invalid-argument');});
test('confirmed unpriced Shopee To Ship transfers are excluded, priced sales remain',()=>{const transfer=row('transfer',1,'--');transfer[4]='To Ship';const sale=row('priced',1,59);sale[4]='To Ship';const data=C.calculate([parsed([transfer,sale])]);a.equal(data.orderCount,1);a.equal(data.diagnostics.unpricedToShipRows,1);a.equal(data.daily[0].gmv,59);a.equal(data.daily[0].status,'To Ship');a.equal(C.calculate([parsed([sale])],C.unpack(C.snapshot(data.records))).orderCount,1);const replaced=C.calculate([parsed([row('transfer',2,20)])],data.records);a.equal(replaced.orderCount,2);a.equal(replaced.daily.reduce((n,r)=>n+r.gmv,0),99);const badPrice=[...sale];badPrice[8]='garbage';a.throws(()=>C.calculate([parsed([badPrice])]),e=>e.code==='invalid-argument'&&e.details.errors[0].includes('Price "garbage"'));});

test('order conflicts identify both export locations without publishing a report',()=>{const first=parsed([row('1078238338262289')],'Order-SKU-all20261002074246450(1).csv'),parts=Array.from({length:10},(_,i)=>parsed([row('other'+i)],`Order-SKU-all20261002074246450(${i+2}).csv`)),changed=row('1078238338262289');changed[4]='Canceled';a.throws(()=>C.calculate([first,...parts,parsed([changed],'Order-SKU-all20261002074246450(12).csv')]),e=>{a.equal(e.code,'invalid-argument');a.equal(e.details.kind,'order-conflict');a.equal(e.details.rows[0].status,'Completed');a.equal(e.details.rows[1].status,'Canceled');a.equal(e.details.rows[1].row,2);return true;});a.equal(require('node:fs').readFileSync(require('node:path').resolve(__dirname,'../../assets/engine.js'),'utf8'),require('node:fs').readFileSync(require('node:path').resolve(__dirname,'../functions/lib/engine.js'),'utf8'));});

test('partial cancellation preserves both item statuses and counts one completed order',()=>{
 const sale=row('partial',1,59),cancel=row('partial',1,59);cancel[4]='Canceled';cancel[5]='OTHER';
 const data=C.calculate([parsed([sale,cancel])]),records=C.unpack(C.snapshot(data.records));
 a.equal(records[0].partialCanceled,true);a.deepEqual(records[0].lines.map(l=>l.status),['Completed','Canceled']);
 const meta=C.reports(data)[0].meta;a.equal(meta.orders,1);a.equal(meta.gmv,118);a.equal(meta.units,2);
 a.equal(C.calculate([parsed([sale,cancel])],records).diagnostics.duplicates,1);
});
