const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),C=require('../functions/lib/core'),I=require('../functions/lib/customer');
const headers=['Order No','Order Time','BigSeller Store Nickname','Marketplace','Order Status','Merchant SKU','Product Name','Quantity','Price','Username (Buyer)','Province (State)','Variation Name','Customer Code'];
const row=(id,buyer='buyer-private',variant='21/19 DMAX 4DOOR',qty=1)=>[id,'2026-09-08 09:00','NKM_SHP','Shopee','Completed','WIPER','Nakama ใบปัดน้ำฝน',qty,59,buyer,'จังหวัดกรุงเทพมหานคร',variant,''];
const file=(rows,name='Order-SKU-all20261001101409972.csv')=>({name,headers,rows}),key=Buffer.alloc(32,7),args={from:'2026-09-01',to:'2026-09-30',store:'nakama',basis:'completed'};
test('reordered rich headers preserve sales totals and retain only secret-hashed identities',()=>{const rows=[row('one'),row('two'),row('masked','bu***er'),row('zero','other',undefined,0)],normal=C.calculate([file(rows)],[],key),reordered=C.calculate([{name:'orders.csv',headers:[...headers].reverse(),rows:rows.map(r=>[...r].reverse())}],[],key);a.deepEqual(normal.daily,reordered.daily);a.deepEqual(normal.skus,reordered.skus);a.equal(normal.records[0].customer.province,'กรุงเทพมหานคร');a.ok(/^[a-f0-9]{64}$/.test(normal.records[0].customer.buyerHash));a.equal(normal.records[2].customer.buyerHash,'');a.ok(!JSON.stringify(normal.records).includes('buyer-private'));a.notEqual(C.calculate([file([row('one')])],[],Buffer.alloc(32,8)).records[0].customer.buyerHash,normal.records[0].customer.buyerHash);const summary=I.summary(normal.records,args);a.equal(summary.totals.repeatBuyers,1);a.equal(summary.totals.buyers,2);a.ok(!JSON.stringify(summary).includes('buyerHash'));a.ok(!JSON.stringify(summary).includes('buyer-private'));});
test('buyer identities stay scoped; replacement and richer reimports update metadata once',()=>{const rows=[row('one'),row('one')];rows[1][2]='NKM_TT';rows[1][3]='TikTok';a.equal(I.summary(C.calculate([file(rows)],[],key).records,args).totals.buyers,2);const legacy=C.calculate([{name:'old.csv',headers:headers.slice(0,9),rows:[row('one').slice(0,9)]}]);a.equal(I.summary(legacy.records,args).totals.buyers,0);const enriched=C.calculate([file([row('one')])],legacy.records,key);a.equal(enriched.orderCount,1);a.equal(I.summary(enriched.records,args).totals.buyers,1);a.equal(C.calculate([file([row('one')])],enriched.records,key).orderCount,1);});
test('multi-line orders do not inflate province/buyer counts and ambiguous fitments remain unknown',()=>{const rows=[row('one','b','21/19 DMAX',2),row('one','b','VIGO REVO',1),row('two','c','24/14',1)];const data=C.calculate([file(rows)],[],key),s=I.summary(data.records,args);a.equal(s.totals.orders,2);a.equal(s.provinces[0].orders,2);a.equal(s.totals.buyers,2);a.equal(s.coverage.wiperUnits,4);a.equal(s.coverage.fitmentUnits,2);a.equal(s.cars[0].orders,1);a.equal(s.cars[0].units,2);a.equal(I.fitment({product:'ใบปัดน้ำฝน Toyota VIGO REVO',sku:'24/14',variation:''}),null);a.equal(I.fitment({product:'ใบปัดน้ำฝน',sku:'X',variation:'CX30'}).model,'CX-30');});
test('completed/default Nakama scope, exclusions, geographic coverage and buyer denominators',()=>{const rows=[row('one'),row('two','***'),row('cancel'),row('group'),row('processing')];rows[1][10]='unknown';rows[2][4]='Canceled';rows[3][2]='SG_SHP';rows[4][4]='Platform Processing';rows[4][8]='--';const data=C.calculate([file(rows)],[],key),s=I.summary(data.records,args);a.equal(s.totals.orders,2);a.equal(s.totals.buyers,1);a.equal(s.coverage.identifiedOrders,1);a.equal(s.coverage.locatedOrders,1);a.equal(s.coverage.buyerCoverage,.5);a.equal(I.summary(data.records,{...args,basis:'all',store:'all'}).totals.orders,4);const old=I.summary([{...data.records.find(o=>!o.excluded),customer:undefined,lines:[{sku:'size24',product:'Wiper',price:59,qty:1}]}],args);a.equal(old.totals.repeatRate,null);a.equal(old.coverage.fitmentCoverage,0);a.throws(()=>I.summary([],{...args,from:'2026-09-31'}));a.throws(()=>I.summary([],{...args,basis:'invalid'}));});
function endpointHarness(records){let downloads=0,reads=0,enabled=true;const revision='11111111-1111-4111-8111-111111111111',snapshot=C.snapshot(records),db={doc:p=>({get:async()=>{reads++;const d=p.startsWith('members/')?{enabled,role:'viewer'}:p==='workspace/main'?{revision,months:['2026-09']}:{state:'published',snapshot:'private/revisions/sample'};return {data:()=>d};}})},exports={},sandbox={exports,process:{env:{GCLOUD_PROJECT:'nakama-sales'}},console,require:name=>name==='firebase-functions/v2/https'?{onCall:(opts,fn)=>fn,HttpsError:class extends Error{constructor(code,msg){super(msg);this.code=code;}}}:name==='firebase-admin/app'?{initializeApp:()=>{}}:name==='firebase-admin/firestore'?{getFirestore:()=>db}:name==='firebase-admin/auth'?{getAuth:()=>({getUser:async()=>({disabled:false})})}:name==='firebase-admin/storage'?{getStorage:()=>({bucket:()=>({file:()=>({download:async()=>{downloads++;return [snapshot];}})})})}:name==='./lib/core'?C:name==='./lib/customer'?I:name==='./lib/stock-engine'?require('../functions/lib/stock-engine'):name==='./lib/ads-service'?require('../functions/lib/ads-service'):name==='./lib/accounts'?require('../functions/lib/accounts'):name==='./auth-config.json'?{apiKey:'test-public-key'}:require(name)};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../functions/index.js'),'utf8'),sandbox);return {call:exports.nkmCustomerInsights,stats:()=>({downloads,reads}),revoke:()=>{enabled=false;}};}
test('customer endpoint rejects unauthenticated and revoked members before reading private snapshots',async()=>{const h=endpointHarness(C.calculate([file([row('one')])],[],key).records);await a.rejects(()=>h.call({data:args}),e=>e.code==='unauthenticated');a.equal(h.stats().downloads,0);const request={auth:{uid:'u',token:{nakamaRole:'viewer'}},data:args},s=await h.call(request);a.equal(s.totals.orders,1);a.equal(s.version,1);a.ok(!JSON.stringify(s).includes('buyerHash'));h.revoke();const n=h.stats().downloads;await a.rejects(()=>h.call(request),e=>e.code==='permission-denied');a.equal(h.stats().downloads,n);});


test('multiple customer stores include only exact selections and keep buyer identities scoped',()=>{
 const rows=[row('one','same-buyer'),row('two','same-buyer'),row('three','same-buyer'),row('four','same-buyer')];rows[1][2]='NKM_TT';rows[1][3]='TikTok';rows[2][2]='SG_SHP';rows[3][2]='CKW_SHP';
 const records=C.calculate([file(rows)],[],key).records,s=I.summary(records,{...args,store:['NKM_SHP','SG_SHP','NKM_SHP']});a.equal(s.totals.orders,2);a.equal(s.totals.gmv,118);a.equal(s.totals.buyers,2);a.deepEqual(s.filters.store,['NKM_SHP','SG_SHP']);a.equal(s.coverage.identifiedOrders,2);a.equal(I.summary(records,{...args,store:['NOT_IMPORTED']}).totals.orders,0);a.equal(I.summary(records,{...args,store:'nakama'}).totals.orders,2);a.equal(I.summary(records,{...args,store:'all'}).totals.orders,4);a.equal(I.summary(records,{...args,store:['NKM_SHP','NKM_TT'],platform:'Shopee'}).totals.orders,1);a.ok(!JSON.stringify(s).includes('same-buyer'));
 for(const store of [[],[null],[''],['all','NKM_SHP'],['nakama'],Array(101).fill('NKM_SHP'),{}])a.throws(()=>I.validate({...args,store}));
});
