const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawnSync}=require('node:child_process'),root=path.resolve(__dirname,'..');
test('configure accepts public project config; deployment guards reject mismatches and attendance',()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'nkm-config-test-'));try{for(const p of ['backend/scripts','backend/functions/lib','assets'])fs.mkdirSync(path.join(temp,p),{recursive:true});for(const f of ['configure.cjs','project.cjs','check-project.cjs'])fs.copyFileSync(path.join(root,'scripts',f),path.join(temp,'backend/scripts',f));fs.cpSync(path.join(root,'functions/lib'),path.join(temp,'backend/functions/lib'),{recursive:true});const fixture=path.join(temp,'public-web-config.json'),config={apiKey:'synthetic-public-api-key',authDomain:'nakama-test-cloud.firebaseapp.com',projectId:'nakama-test-cloud',storageBucket:'nakama-test-cloud.firebasestorage.app',appId:'synthetic-web-app'};fs.writeFileSync(fixture,JSON.stringify(config));const invoke=(file,args=[],env={})=>spawnSync(process.execPath,[path.join(temp,'backend/scripts',file),...args],{encoding:'utf8',env:{...process.env,...env}});
a.equal(invoke('configure.cjs',['--project',config.projectId,'--config',fixture]).status,0);a.equal(JSON.parse(fs.readFileSync(path.join(temp,'backend/nakama-project.json'))).projectId,config.projectId);a.match(fs.readFileSync(path.join(temp,'assets/cloud-config.js'),'utf8'),/nakama-test-cloud/);a.equal(invoke('check-project.cjs',[],{GCLOUD_PROJECT:config.projectId,NKM_DEPLOY_PROJECT:config.projectId}).status,0);a.notEqual(invoke('check-project.cjs',[],{GCLOUD_PROJECT:'different-cloud-project',NKM_DEPLOY_PROJECT:config.projectId}).status,0);a.notEqual(invoke('configure.cjs',['--project','sss-attendance-prods','--config',fixture]).status,0);fs.writeFileSync(fixture,JSON.stringify({...config,type:'service_account',private_key:'synthetic'}));a.notEqual(invoke('configure.cjs',['--project',config.projectId,'--config',fixture]).status,0);}finally{fs.rmSync(temp,{recursive:true,force:true});}});
const vm=require('node:vm');
function accessHarness(failAt,missing=false){const calls=[],logs=[],module={exports:{}},sandbox={module,console:{log:m=>logs.push(m),error:m=>logs.push(m)},require:name=>name==='node:child_process'?{spawnSync:(cmd,args)=>{calls.push([cmd,...args]);if(missing&&args[0]==='--version')return {error:Error('missing')};if(args[0]==='functions')return {status:0,stdout:'projects/nakama-sales/locations/asia-southeast1/services/'+args[2].toLowerCase()+'\n'};if(args[0]==='run'&&args[3]===failAt)return {status:1};return {status:0,stdout:''};}}:name==='./project.cjs'?id=>{if(id!=='nakama-sales')throw Error('Wrong Nakama project');}:require(name)};vm.runInNewContext(fs.readFileSync(path.join(root,'scripts/browser-access.cjs'),'utf8'),sandbox);return {api:module.exports,calls,logs};}
test('browser access setup targets only the six account services and never adds allUsers or changes organization policies',()=>{const h=accessHarness();h.api.configureBrowserAccess('nakama-sales');const updates=h.calls.filter(c=>c[1]==='run');a.equal(updates.length,6);a.deepEqual(updates.map(c=>c[4]),['nkmaccountprofile','nkmaccounts','nkmlinkuserid','nkmregister','nkmreviewaccount','nkmuserlogin']);for(const c of updates){a.ok(c.includes('--no-invoker-iam-check'));a.ok(c.includes('nakama-sales'));a.ok(c.includes('asia-southeast1'));}a.ok(!JSON.stringify(h.calls).includes('allUsers'));a.ok(!JSON.stringify(h.calls).includes('org-policies'));});
test('a policy denial stops access setup at the failing service without attempting the remaining services',()=>{const h=accessHarness('nkmlinkuserid');a.throws(()=>h.api.configureBrowserAccess('nakama-sales'),/organization policy requires the IAM invoker check/);a.equal(h.calls.filter(c=>c[1]==='run').length,3);a.ok(!h.calls.some(c=>c.includes('nkmregister')));});
test('project mismatch and missing gcloud fail before any service mutation',()=>{const h=accessHarness();a.throws(()=>h.api.configureBrowserAccess('sss-attendance-prods'),/Wrong Nakama project/);a.equal(h.calls.length,0);const missing=accessHarness(undefined,true);a.throws(()=>missing.api.configureBrowserAccess('nakama-sales'),/Install the Google Cloud CLI/);a.equal(missing.calls.length,1);});
function deployHarness(status){const calls=[],logs=[],mockProcess={execPath:'/node',argv:['node','deploy','--project','nakama-sales'],env:{},exitCode:0},access={checkCli:()=>calls.push('preflight'),configureBrowserAccess:id=>calls.push('access:'+id)},fakeRequire=name=>name==='node:child_process'?{spawnSync:(cmd,args,options)=>{calls.push({cmd,args,options});return {status};}}:name==='node:path'?path:name==='./project.cjs'?id=>a.equal(id,'nakama-sales'):name==='./browser-access.cjs'?access:require(name);fakeRequire.resolve=()=>'/firebase-cli';vm.runInNewContext(fs.readFileSync(path.join(root,'scripts/deploy.cjs'),'utf8'),{require:fakeRequire,process:mockProcess,__dirname:path.join(root,'scripts'),console:{log:m=>logs.push(m),error:m=>logs.push(m)}});return {calls,logs,process:mockProcess};}
test('successful backend deploy applies account browser access, preserving the project guard and original deployment targets',()=>{const h=deployHarness(0);a.equal(h.calls[0],'preflight');a.equal(h.calls[1].options.env.NKM_DEPLOY_PROJECT,'nakama-sales');a.ok(h.calls[1].args.includes('functions:nakama,firestore,storage'));a.equal(h.calls.at(-1),'access:nakama-sales');a.equal(h.process.exitCode,0);});
test('failed backend deploy is not reported as success and gives the scoped recovery command',()=>{const h=deployHarness(2);a.equal(h.process.exitCode,2);a.ok(!h.calls.includes('access:nakama-sales'));a.ok(h.logs.some(m=>m.includes('npm run browser-access -- --project nakama-sales')));});
