const {test,before,after}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),{initializeTestEnvironment,assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{doc,getDoc,setDoc,collection,getDocs}=require('firebase/firestore'),{ref,uploadBytes,getBytes,listAll,deleteObject}=require('firebase/storage');
process.env.GCLOUD_PROJECT='demo-nakama';process.env.FIREBASE_CONFIG=JSON.stringify({projectId:'demo-nakama',storageBucket:'demo-nakama.appspot.com'});
const ar=require('node:module').createRequire(require.resolve('../functions/package.json')),functions=require('../functions'),{getFirestore}=ar('firebase-admin/firestore'),{getAuth}=ar('firebase-admin/auth'),{getStorage}=ar('firebase-admin/storage'),db=getFirestore(),adminAuth=getAuth(),bucket=getStorage().bucket();let env;
const run=(name,uid,role,data)=>functions[name].run({auth:uid?{uid,token:{nakamaRole:role}}:null,data}),denies=(p,code)=>a.rejects(p,e=>e.code===code);
const headers='Order No,Order Time,BigSeller Store Nickname,Marketplace,Order Status,Merchant SKU,Product Name,Quantity,Price\n',csv=(price=50,qty=2)=>Buffer.from(headers+`123456789012345678,2026-09-01 09:00,NKM_SHP,Shopee,Completed,W24,Wiper,${qty},${price}\n`);
async function begin(bytes,name='orders.csv'){return run('nkmBeginImport','importer','importer',{files:[{name,size:bytes.length,lastModified:1}]});}
async function rawUpload(job,bytes,ctx,type='text/csv'){return uploadBytes(ref(ctx.storage('gs://demo-nakama.appspot.com'),job.files[0].path),bytes,{contentType:type});}
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-nakama',firestore:{host:'127.0.0.1',port:8085,rules:fs.readFileSync('firestore.rules','utf8')},storage:{host:'127.0.0.1',port:9199,rules:fs.readFileSync('storage.rules','utf8')}});await env.clearFirestore();for(const [uid,role] of [['importer','importer'],['viewer','viewer'],['other','importer']]){try{await adminAuth.deleteUser(uid);}catch{}await adminAuth.createUser({uid,email:uid+'@example.test'});await adminAuth.setCustomUserClaims(uid,{nakamaRole:role});await db.doc('members/'+uid).set({enabled:true,role});}});
after(async()=>{await env?.cleanup();});
test('advertising uploads enforce the manifest and publish through the production handler',{timeout:60000},async()=>{
 const imp=env.authenticatedContext('importer',{nakamaRole:'importer'}),viewer=env.authenticatedContext('viewer',{nakamaRole:'viewer'}),other=env.authenticatedContext('other',{nakamaRole:'importer'}),anon=env.unauthenticatedContext();
 const bytes=Buffer.from('Shopee Ads Data,Time:2026-10-05-2026-10-05,Currency:THB\nBigSeller Store Name,Spend,Sales Amount,Direct Sales Amount,Conversion,Direct Conversion,Views,Clicks,Sold Products,Directly Sold Products\nTEST_STORE,100,500,300,10,8,1000,100,15,12\n');
 const job=await run('nkmProcessImport','importer','importer',{source:'advertising',op:'begin',files:[{name:'ads.csv',size:bytes.length,lastModified:1}]});
 await assertFails(rawUpload(job,bytes,viewer));await assertFails(rawUpload(job,bytes,other));await assertFails(rawUpload(job,bytes,anon));await assertFails(rawUpload(job,Buffer.from('wrong size'),imp));await assertFails(rawUpload(job,bytes,imp,'application/json'));
 await assertFails(rawUpload(job,bytes,imp));
 const args={source:'advertising',op:'upload',id:job.id,index:'0',base64:bytes.toString('base64')};await denies(run('nkmProcessImport','viewer','viewer',args),'permission-denied');await denies(run('nkmProcessImport','other','importer',args),'permission-denied');await denies(run('nkmProcessImport',null,null,args),'unauthenticated');
 a.equal((await run('nkmProcessImport','importer','importer',args)).state,'uploaded');a.equal((await run('nkmProcessImport','importer','importer',args)).state,'uploaded');await assertFails(rawUpload(job,bytes,imp));
 const source=ref(imp.storage('gs://demo-nakama.appspot.com'),job.files[0].path);await assertFails(getBytes(source));await assertFails(deleteObject(source));
 const result=await run('nkmProcessImport','importer','importer',{source:'advertising',op:'process',id:job.id});a.equal(result.state,'complete');
 const report=await run('nkmProcessImport','viewer','viewer',{source:'advertising',op:'load'});a.equal(report.rows.length,1);a.equal(report.rows[0].spend,100);a.equal(report.rows[0].sales,500);
 const ttBytes=Buffer.from('ตามวัน,ต้นทุน,คำสั่งซื้อ SKU (ร้านค้าปัจจุบัน),รายได้ขั้นต้น (ร้านค้าปัจจุบัน),สกุลเงิน\n2026-10-04 00:00:00,200,20,1000,THB\n2026-10-05 00:00:00,300,30,1500,THB\n-,500,50,2500,THB\n');
 const tt=await run('nkmProcessImport','importer','importer',{source:'advertising',op:'begin',tiktokStore:'TEST_TT',files:[{name:'tiktok.csv',size:ttBytes.length}]});await run('nkmProcessImport','importer','importer',{source:'advertising',op:'upload',id:tt.id,index:'0',base64:ttBytes.toString('base64')});await run('nkmProcessImport','importer','importer',{source:'advertising',op:'process',id:tt.id,tiktokStore:'FORGED_TT'});
 const both=await run('nkmProcessImport','viewer','viewer',{source:'advertising',op:'load'});a.equal(both.rows.length,3);const ttRows=both.rows.filter(r=>r.platform==='TikTok');a.equal(ttRows.length,2);a.equal(ttRows[0].store,'TEST_TT');a.equal(ttRows[0].directSales,null);a.equal(ttRows.reduce((sum,r)=>sum+r.spend,0),500);await assertFails(getDoc(doc(viewer.firestore(),'adImports/'+tt.id)));await assertFails(getBytes(ref(viewer.storage('gs://demo-nakama.appspot.com'),tt.files[0].path)));
 const periodBytes=Buffer.from(bytes.toString().replace('Time:2026-10-05-2026-10-05','Time:2026-10-01-2026-10-07'));
 const period=await run('nkmProcessImport','importer','importer',{source:'advertising',op:'begin',files:[{name:'period.csv',size:periodBytes.length}]});await run('nkmProcessImport','importer','importer',{source:'advertising',op:'upload',id:period.id,index:'0',base64:periodBytes.toString('base64')});await run('nkmProcessImport','importer','importer',{source:'advertising',op:'process',id:period.id});const all=await run('nkmProcessImport','viewer','viewer',{source:'advertising',op:'load'}),Ads=require('../../assets/ads-engine');a.equal(Ads.select(all.rows,{from:'2026-10-01',to:'2026-10-07'},[],'Shopee').totals.spend,100);a.equal(Ads.select(all.rows,{from:'2026-10-05',to:'2026-10-05'},[],'Shopee').totals.spend,100);
 await assertFails(getDoc(doc(viewer.firestore(),'adImports/'+job.id)));await assertFails(getBytes(ref(viewer.storage('gs://demo-nakama.appspot.com'),(await db.doc('adWorkspace/main').get()).data().path)));
});
test('real rules + production handlers: source privacy, roles, atomic publication and revocation',{timeout:60000},async()=>{
const imp=env.authenticatedContext('importer',{nakamaRole:'importer'}),viewer=env.authenticatedContext('viewer',{nakamaRole:'viewer'}),other=env.authenticatedContext('other',{nakamaRole:'importer'}),anon=env.unauthenticatedContext();
await denies(run('nkmWorkspace',null,null,{}),'unauthenticated');await denies(run('nkmBeginImport','viewer','viewer',{files:[{name:'orders.csv',size:1}]}),'permission-denied');
const bytes=csv(),job=await begin(bytes);await assertFails(rawUpload(job,bytes,viewer));await assertFails(rawUpload(job,bytes,other));await assertFails(rawUpload(job,bytes,anon));await assertFails(rawUpload(job,Buffer.from('wrong size'),imp));await assertFails(rawUpload(job,bytes,imp,'application/json'));await assertSucceeds(rawUpload(job,bytes,imp));await assertFails(rawUpload(job,bytes,imp));
const source=ref(imp.storage('gs://demo-nakama.appspot.com'),job.files[0].path);await assertFails(getBytes(source));await assertFails(listAll(ref(imp.storage('gs://demo-nakama.appspot.com'),'uploads/importer')));await assertFails(deleteObject(source));await assertFails(getDoc(doc(viewer.firestore(),'imports/'+job.id)));await assertFails(setDoc(doc(imp.firestore(),'workspace/main'),{revision:'forged'}));
const first=await run('nkmProcessImport','importer','importer',{id:job.id});a.equal(first.state,'complete');const state=await run('nkmWorkspace','viewer','viewer',{});a.equal(state.revision,first.revision);a.deepEqual(state.months,['2026-09']);a.equal((await assertSucceeds(getDoc(doc(viewer.firestore(),'workspace/main')))).data().revision,first.revision);await assertFails(getDoc(doc(anon.firestore(),'workspace/main')));await assertFails(getDocs(collection(viewer.firestore(),'workspace')));
const args={revision:first.revision,month:'2026-09',kind:'daily'},daily=await run('nkmReportPage','viewer','viewer',args);a.equal(daily.rows[0].gmv,100);a.equal(daily.rows[0].orders,1);a.equal(daily.rows[0].units,2);a.equal(daily.nextCursor,null);a.deepEqual(await run('nkmReportPage','other','importer',args),daily);await assertFails(getDoc(doc(viewer.firestore(),`reports/${first.revision}/months/2026-09/sections/daily/chunks/000000`)));const published=(await db.doc('reports/'+first.revision).get()).data(),[manifestBytes]=await bucket.file(published.snapshot).download(),manifest=JSON.parse(manifestBytes.toString());a.equal(manifest.version,2);a.equal(manifest.orders,1);await assertFails(getBytes(ref(viewer.storage('gs://demo-nakama.appspot.com'),published.snapshot)));await assertFails(getBytes(ref(viewer.storage('gs://demo-nakama.appspot.com'),manifest.parts[0].path)));
a.equal((await run('nkmProcessImport','importer','importer',{id:job.id})).revision,first.revision);await denies(run('nkmImportStatus','other','importer',{id:job.id}),'permission-denied');await denies(run('nkmReportPage',null,null,args),'unauthenticated');
const bad=csv(20,-1),badJob=await begin(bad,'bad.csv');await rawUpload(badJob,bad,imp);await denies(run('nkmProcessImport','importer','importer',{id:badJob.id}),'invalid-argument');a.equal((await run('nkmWorkspace','viewer','viewer',{})).revision,first.revision);a.equal((await run('nkmImportStatus','importer','importer',{id:badJob.id})).state,'failed');
const missing=await begin(bytes,'missing.csv');await denies(run('nkmProcessImport','importer','importer',{id:missing.id}),'failed-precondition');a.equal((await run('nkmWorkspace','viewer','viewer',{})).revision,first.revision);await rawUpload(missing,bytes,imp);await db.doc('internal/importLease').set({token:'competing',expires:Date.now()+30000});await denies(run('nkmProcessImport','importer','importer',{id:missing.id}),'aborted');a.equal((await db.doc('workspace/main').get()).data().revision,first.revision);await db.doc('internal/importLease').delete();
await db.doc('members/viewer').update({enabled:false});await denies(run('nkmWorkspace','viewer','viewer',{}),'permission-denied');await assertFails(getDoc(doc(viewer.firestore(),'workspace/main')));await db.doc('members/importer').update({enabled:false});await denies(run('nkmProcessImport','importer','importer',{id:missing.id}),'permission-denied');a.equal((await db.doc('workspace/main').get()).data().revision,first.revision);a.equal((await run('nkmHistory','other','importer',{})).history.length,1);
});
