const {test,before,after}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),{initializeTestEnvironment,assertFails,assertSucceeds}=require('@firebase/rules-unit-testing'),{doc,getDoc,setDoc,collection,getDocs}=require('firebase/firestore'),{ref,uploadBytes,getBytes,listAll,deleteObject}=require('firebase/storage');
process.env.GCLOUD_PROJECT='demo-nakama';process.env.FIREBASE_CONFIG=JSON.stringify({projectId:'demo-nakama',storageBucket:'demo-nakama.appspot.com'});
const ar=require('node:module').createRequire(require.resolve('../functions/package.json')),functions=require('../functions'),{getFirestore}=ar('firebase-admin/firestore'),{getAuth}=ar('firebase-admin/auth'),{getStorage}=ar('firebase-admin/storage'),db=getFirestore(),adminAuth=getAuth(),bucket=getStorage().bucket();let env;
const run=(name,uid,role,data)=>functions[name].run({auth:uid?{uid,token:{nakamaRole:role}}:null,data}),denies=(p,code)=>a.rejects(p,e=>e.code===code);
const headers='Order No,Order Time,BigSeller Store Nickname,Marketplace,Order Status,Merchant SKU,Product Name,Quantity,Price\n',csv=(price=50,qty=2)=>Buffer.from(headers+`123456789012345678,2026-09-01 09:00,NKM_SHP,Shopee,Completed,W24,Wiper,${qty},${price}\n`);
async function begin(bytes,name='orders.csv'){return run('nkmBeginImport','importer','importer',{files:[{name,size:bytes.length,lastModified:1}]});}
async function rawUpload(job,bytes,ctx,type='text/csv'){return uploadBytes(ref(ctx.storage('gs://demo-nakama.appspot.com'),job.files[0].path),bytes,{contentType:type});}
before(async()=>{env=await initializeTestEnvironment({projectId:'demo-nakama',firestore:{host:'127.0.0.1',port:8085,rules:fs.readFileSync('firestore.rules','utf8')},storage:{host:'127.0.0.1',port:9199,rules:fs.readFileSync('storage.rules','utf8')}});await env.clearFirestore();for(const [uid,role] of [['importer','importer'],['viewer','viewer'],['other','importer']]){try{await adminAuth.deleteUser(uid);}catch{}await adminAuth.createUser({uid,email:uid+'@example.test'});await adminAuth.setCustomUserClaims(uid,{nakamaRole:role});await db.doc('members/'+uid).set({enabled:true,role});}});
after(async()=>{await env?.cleanup();});
test('real rules + production handlers: source privacy, roles, atomic publication and revocation',{timeout:60000},async()=>{
const imp=env.authenticatedContext('importer',{nakamaRole:'importer'}),viewer=env.authenticatedContext('viewer',{nakamaRole:'viewer'}),other=env.authenticatedContext('other',{nakamaRole:'importer'}),anon=env.unauthenticatedContext();
await denies(run('nkmWorkspace',null,null,{}),'unauthenticated');await denies(run('nkmBeginImport','viewer','viewer',{files:[{name:'orders.csv',size:1}]}),'permission-denied');
const bytes=csv(),job=await begin(bytes);await assertFails(rawUpload(job,bytes,viewer));await assertFails(rawUpload(job,bytes,other));await assertFails(rawUpload(job,bytes,anon));await assertFails(rawUpload(job,Buffer.from('wrong size'),imp));await assertFails(rawUpload(job,bytes,imp,'application/json'));await assertSucceeds(rawUpload(job,bytes,imp));await assertFails(rawUpload(job,bytes,imp));
const source=ref(imp.storage('gs://demo-nakama.appspot.com'),job.files[0].path);await assertFails(getBytes(source));await assertFails(listAll(ref(imp.storage('gs://demo-nakama.appspot.com'),'uploads/importer')));await assertFails(deleteObject(source));await assertFails(getDoc(doc(viewer.firestore(),'imports/'+job.id)));await assertFails(setDoc(doc(imp.firestore(),'workspace/main'),{revision:'forged'}));
const first=await run('nkmProcessImport','importer','importer',{id:job.id});a.equal(first.state,'complete');const state=await run('nkmWorkspace','viewer','viewer',{});a.equal(state.revision,first.revision);a.deepEqual(state.months,['2026-09']);a.equal((await assertSucceeds(getDoc(doc(viewer.firestore(),'workspace/main')))).data().revision,first.revision);await assertFails(getDoc(doc(anon.firestore(),'workspace/main')));await assertFails(getDocs(collection(viewer.firestore(),'workspace')));
const args={revision:first.revision,month:'2026-09',kind:'daily'},daily=await run('nkmReportPage','viewer','viewer',args);a.equal(daily.rows[0].gmv,100);a.equal(daily.rows[0].orders,1);a.equal(daily.rows[0].units,2);a.equal(daily.nextCursor,null);a.deepEqual(await run('nkmReportPage','other','importer',args),daily);await assertFails(getDoc(doc(viewer.firestore(),`reports/${first.revision}/months/2026-09/sections/daily/chunks/000000`)));await assertFails(getBytes(ref(viewer.storage('gs://demo-nakama.appspot.com'),`private/revisions/${first.revision}/orders.json.gz`)));
a.equal((await run('nkmProcessImport','importer','importer',{id:job.id})).revision,first.revision);await denies(run('nkmImportStatus','other','importer',{id:job.id}),'permission-denied');await denies(run('nkmReportPage',null,null,args),'unauthenticated');
const bad=csv(20,-1),badJob=await begin(bad,'bad.csv');await rawUpload(badJob,bad,imp);await denies(run('nkmProcessImport','importer','importer',{id:badJob.id}),'invalid-argument');a.equal((await run('nkmWorkspace','viewer','viewer',{})).revision,first.revision);a.equal((await run('nkmImportStatus','importer','importer',{id:badJob.id})).state,'failed');
const missing=await begin(bytes,'missing.csv');await denies(run('nkmProcessImport','importer','importer',{id:missing.id}),'failed-precondition');a.equal((await run('nkmWorkspace','viewer','viewer',{})).revision,first.revision);await rawUpload(missing,bytes,imp);await db.doc('internal/importLease').set({token:'competing',expires:Date.now()+30000});await denies(run('nkmProcessImport','importer','importer',{id:missing.id}),'aborted');a.equal((await db.doc('workspace/main').get()).data().revision,first.revision);await db.doc('internal/importLease').delete();
await db.doc('members/viewer').update({enabled:false});await denies(run('nkmWorkspace','viewer','viewer',{}),'permission-denied');await assertFails(getDoc(doc(viewer.firestore(),'workspace/main')));await db.doc('members/importer').update({enabled:false});await denies(run('nkmProcessImport','importer','importer',{id:missing.id}),'permission-denied');a.equal((await db.doc('workspace/main').get()).data().revision,first.revision);a.equal((await run('nkmHistory','other','importer',{})).history.length,1);
});
