const {test}=require('node:test'),a=require('node:assert/strict'),create=require('../functions/lib/shipment-reference');
const fs=require('node:fs'),vm=require('node:vm'),C=require('../functions/lib/core'),Stock=require('../../assets/stock-engine');
const product={sku:'TEST',width:33,length:40,height:49,cbm:.065};
test('reference preserves both freight rates, missing values and explicit zero, rejecting invalid rates',()=>{const p=create.validate([{...product,seaRate:0,truckRate:4000}])[0];a.equal(p.seaRate,0);a.equal(p.truckRate,4000);a.equal(create.validate([product])[0].seaRate,null);for(const rate of [-1,'4000',Infinity])a.throws(()=>create.validate([{...product,truckRate:rate}]));});
function harness(saved={products:[product],updatedAt:{toMillis:()=>123},source:{url:'https://docs.google.com/spreadsheets/d/test'}},{denyAt=0}={}){let checks=0,reads=0;return {api:create({db:{doc:name=>{a.equal(name,'shipmentReference/main');return {get:async()=>{reads++;return {data:()=>saved};}};}},member:async()=>{checks++;if(checks===denyAt)throw Error('permission-denied');},C:{fail:(code,message)=>{throw Object.assign(Error(message),{code});}}}),checks:()=>checks,reads:()=>reads};}
test('private catalog checks membership before reading and before returning',async()=>{const h=harness(),r=await h.api.load({});a.equal(h.checks(),2);a.equal(r.products.length,1);a.equal(r.updatedAt,123);});
test('unauthorized sessions never read the catalog and revocation during read never returns it',async()=>{for(const denyAt of [1,2]){const h=harness(undefined,{denyAt});await a.rejects(h.api.load({}),/permission-denied/);a.equal(h.reads(),denyAt===1?0:1);}});
test('missing or malformed catalog fails explicitly',async()=>{for(const [saved,code] of [[null,'failed-precondition'],[{products:[{...product,cbm:-1}]},'data-loss']]){const h=harness(saved);await a.rejects(h.api.load({}),e=>e.code===code);}});
test('zero placeholders normalize to missing, negatives are rejected, and duplicate rows remain available for ambiguity checks',()=>{a.equal(create.validate([{...product,width:0}])[0].width,null);a.throws(()=>create.validate([{...product,cbm:-1}]));a.equal(create.validate([product,{...product,sku:'test'}]).length,2);});
test('production callable dispatches product-info for enabled members and rejects missing or revoked authentication',async()=>{
 let enabled=true;const context={exports:{},Buffer,C,Stock,Timestamp:{},require:name=>name==='./lib/shipment-reference'?create:Stock,endpoint:(options,fn)=>fn,member:async request=>C.role(request.auth,{enabled,role:'viewer'}),db:{doc:name=>{a.equal(name,'shipmentReference/main');return {get:async()=>({data:()=>({products:[product]})})};}}};
 const source=fs.readFileSync(require.resolve('../functions/index.js'),'utf8').split("const Stock=require('./lib/stock-engine');")[1];vm.runInNewContext(source,context);
 const invoke=auth=>context.exports.nkmStockForecast({auth,data:{op:'product-info'}});await a.rejects(invoke(null),e=>e.code==='unauthenticated');const auth={uid:'u',token:{nakamaRole:'viewer'}};a.equal((await invoke(auth)).products.length,1);enabled=false;await a.rejects(invoke(auth),e=>e.code==='permission-denied');
});
