const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{JSDOM}=require('jsdom'),root=path.resolve(__dirname,'../..');
const summary=month=>({mode:'raw',records:[],revision:'r1',month,diagnostics:{sourceUnverified:false},daily:[{date:month+'-01',month,store:'NKM_SHP',platform:'Shopee',status:'Completed',gmv:100,orders:1,units:2}],skus:[{date:month+'-01',month,store:'NKM_SHP',platform:'Shopee',status:'Completed',sku:'W24',product:'Wiper',gmv:100,orders:1,units:2}]}),flush=()=>new Promise(r=>setTimeout(r,10));
function harness(mock,settings={}){const dom=new JSDOM(fs.readFileSync(path.join(root,'management.html'),'utf8'),{url:'http://localhost/management.html',runScripts:'outside-only'}),w=dom.window,ctx=dom.getInternalVMContext();const media={matches:settings.dark===true,addEventListener:(event,fn)=>{media.listener=fn;}};w.matchMedia=()=>media;w.scrollTo=()=>{};if(settings.savedTheme)w.localStorage.setItem('nakama-theme',settings.savedTheme);w.cloudMock=mock;for(const f of ['engine.js','store-labels.js','report.js','charts.js','insights.js','insight-ui.js','theme.js'])vm.runInContext(fs.readFileSync(path.join(root,'assets',f),'utf8'),ctx);const src=fs.readFileSync(path.join(root,'assets/management.js'),'utf8').split("import('./cloud.js")[0];vm.runInContext(src+'\ncloud=cloudMock;',ctx);return {dom,w,ctx,media};}
test('period comparison loads only relevant months, viewer upload denied, reset retains month, sign-out clears records',async()=>{const fetched=[],{dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'viewer',revision:'r1',months:['2026-08','2026-09']}),history:async()=>[],loadMonth:async(s,m)=>{fetched.push(m);return summary(m);}}),el=id=>w.document.getElementById(id);vm.runInContext("sessionChanged({user:{uid:'test'},role:'viewer'});",ctx);await flush();a.deepEqual(fetched,['2026-09','2026-08']);a.equal(el('auth-gate').hidden,true);a.equal(el('upload').disabled,true);a.equal(el('gmv').textContent,'฿100');a.equal(el('month').options.length,2);el('reset').click();a.equal(el('month').value,'2026-09');el('month').value='2026-08';el('month').dispatchEvent(new w.Event('change'));await flush();a.deepEqual(fetched,['2026-09','2026-08','2026-08']);a.equal(el('month').value,'2026-08');vm.runInContext("cloudMock.workspace=async()=>({role:'importer',revision:'r1',months:['2026-09']});sessionChanged({user:{uid:'test'},role:'importer'});",ctx);await flush();a.equal(el('upload').disabled,false);vm.runInContext('sessionChanged(null);',ctx);a.equal(el('auth-gate').hidden,false);for(const id of ['store-rows','sku-rows','trend'])a.equal(el(id).textContent,'');a.equal(el('gmv').textContent,'—');a.equal(el('upload').disabled,true);a.equal(vm.runInContext('dataset',ctx),null);dom.window.close();});
test('late report response cannot expose data after revocation',async()=>{let finish;const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'viewer',revision:'r1',months:['2026-09']}),history:async()=>[],loadMonth:()=>new Promise(r=>{finish=r;})});vm.runInContext('sessionChanged({user:{uid:"test"},role:"viewer"});',ctx);await flush();vm.runInContext('sessionChanged({blocked:true,user:{uid:"test"}});',ctx);finish(summary('2026-09'));await flush();a.equal(vm.runInContext('dataset',ctx),null);a.equal(w.document.getElementById('auth-gate').hidden,false);a.equal(w.document.getElementById('gmv').textContent,'—');dom.window.close();});
test('excluded orders stay out of legacy displays and previews allow an exclusion-only update',async()=>{const report=summary('2026-09');for(const kind of ['daily','skus'])report[kind].push({...report[kind][0],status:'Platform Processing',gmv:999,orders:9,units:9});const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'admin',revision:'r1',months:['2026-09']}),history:async()=>[],loadMonth:async()=>report}),el=id=>w.document.getElementById(id);vm.runInContext("sessionChanged({user:{uid:'test'},role:'admin'});",ctx);await flush();a.equal(el('gmv').textContent,'฿100');a.equal(el('orders').textContent,'1');a.equal(el('units').textContent,'2');a.ok(!el('status').textContent.includes('Platform Processing'));a.ok(!el('statuses').textContent.includes('Platform Processing'));a.ok(!el('sku-rows').textContent.includes('999'));w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};vm.runInContext("preview({daily:[],skus:[],records:[],orderCount:0,diagnostics:{invalid:0,excludedOrders:2,excludedRows:3,errors:[]}});",ctx);a.equal(el('confirm').disabled,false);a.match(el('preview-details').textContent,/2 orders entirely excluded · 3 Platform Processing rows ignored/);a.match(el('preview-details').textContent,/0 included orders/);vm.runInContext("preview({daily:[],skus:[],records:[],orderCount:0,diagnostics:{invalid:1,excludedOrders:2,excludedRows:3,errors:[]}});",ctx);a.equal(el('confirm').disabled,true);dom.window.close();});
test('custom, yesterday and year periods use real dates, and partial-month products are withheld',async()=>{const make=(m,items)=>({...summary(m),daily:items.map(([date,gmv])=>({date,month:m,store:'NKM_SHP',platform:'Shopee',status:'Completed',gmv,orders:1,units:2})),skus:[{...summary(m).skus[0],gmv:items.reduce((n,r)=>n+r[1],0)}]}),reports={'2026-08':make('2026-08',[['2026-08-01',10]]),'2026-09':make('2026-09',[['2026-09-29',200],['2026-09-30',100]]),'2026-10':make('2026-10',[['2026-10-01',300],['2026-10-05',400]])},calls=[],{dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'admin',revision:'r1',months:Object.keys(reports)}),history:async()=>[],loadMonth:async(s,m,options)=>{calls.push({month:m,dailyOnly:options?.dailyOnly});return reports[m];}}),el=id=>w.document.getElementById(id);vm.runInContext("NKMReport.today=()=> '2026-10-01';sessionChanged({user:{uid:'test'},role:'admin'});",ctx);await flush();a.equal(el('gmv').textContent,'฿700');a.match(el('gmv-change').textContent,/133.3%/);w.document.querySelector('[data-date-mode="custom"]').click();el('date-from').value='2026-09-30';el('date-to').value='2026-10-01';el('apply-dates').click();await flush();a.equal(el('gmv').textContent,'฿400');a.equal(el('orders').textContent,'2');a.equal(el('units').textContent,'4');w.document.querySelector('[data-view="sku"]').click();a.equal(el('sku-range-notice').hidden,false);a.equal(w.document.querySelector('[data-export="skus"]').disabled,true);a.match(el('sku-rows').textContent,/full month/);a.equal(vm.runInContext('skuRows().length',ctx),0);el('date-from').value='2026-10-05';el('date-to').value='2026-10-01';el('apply-dates').click();a.match(el('period-status').textContent,/valid dates/);a.equal(el('gmv').textContent,'฿400');w.document.querySelector('[data-date-mode="yesterday"]').click();await flush();a.equal(el('gmv').textContent,'฿100');a.match(el('period-title').textContent,/30 Sept? 2026/);a.equal(vm.runInContext('activeRange.to',ctx),'2026-09-30');w.document.querySelector('[data-date-mode="year"]').click();await flush();a.equal(el('gmv').textContent,'฿1,010');a.equal(vm.runInContext('dataset.skuAvailable',ctx),true);a.equal(w.document.querySelector('[data-export="skus"]').disabled,false);a.equal(el('sku-range-notice').hidden,false);a.match(el('sku-range-notice').textContent,/Missing reports/);a.equal(el('insight-grid').querySelectorAll('.insight-card').length,6);a.ok(el('trend').querySelector('svg'));a.ok(el('orders-chart').querySelector('svg'));a.ok(el('platform-bars').querySelector('svg'));vm.runInContext('sessionChanged(null);',ctx);for(const id of ['insight-grid','store-chart','orders-chart'])a.equal(el(id).textContent,'');a.equal(vm.runInContext('reportCache.size',ctx),0);dom.window.close();});
test('theme follows system in Auto and saves manual appearance choices',async()=>{const {dom,w,media}=harness({pendingImport:()=>null},{dark:true});await flush();const el=mode=>w.document.querySelector('button[data-theme-mode="'+mode+'"]');a.equal(w.document.documentElement.dataset.theme,'dark');a.equal(el('auto').getAttribute('aria-pressed'),'true');el('light').click();a.equal(w.document.documentElement.dataset.theme,'light');a.equal(w.localStorage.getItem('nakama-theme'),'light');media.matches=true;media.listener();a.equal(w.document.documentElement.dataset.theme,'light');el('dark').click();a.equal(w.document.documentElement.dataset.theme,'dark');el('auto').click();media.matches=false;media.listener();a.equal(w.document.documentElement.dataset.theme,'light');a.equal(w.localStorage.getItem('nakama-theme'),'auto');dom.window.close();const restored=harness({pendingImport:()=>null},{dark:false,savedTheme:'dark'});await flush();a.equal(restored.w.document.documentElement.dataset.theme,'dark');a.equal(restored.w.document.querySelector('button[data-theme-mode="dark"]').getAttribute('aria-pressed'),'true');restored.dom.window.close();});
test('daily-only cloud requests preserve pagination validation and do not fetch SKU pages',async()=>{const calls=[],sandbox={window:{NKM_CLOUD_CONFIG:{firebase:{projectId:'nakama-sales',apiKey:'public'}}},mockSDK:{httpsCallable:(functions,name)=>async args=>{calls.push(args.kind);return {data:{revision:args.revision,month:args.month,kind:args.kind,total:1,rows:[{date:args.month+'-01',kind:args.kind}],nextCursor:null}};}}},ctx=vm.createContext(sandbox),source=fs.readFileSync(path.join(root,'assets/cloud.js'),'utf8').replace("import * as F from './vendor/firebase-sdk.js?v=glass-20261001';",'const F=mockSDK;').replace(/\bexport /g,'');vm.runInContext(source,ctx);const daily=await vm.runInContext("loadMonth({revision:'r1',months:['2026-09']},'2026-09',{dailyOnly:true})",ctx);a.deepEqual(calls,['daily']);a.equal(daily.daily.length,1);a.equal(daily.skus.length,0);calls.length=0;const full=await vm.runInContext("loadMonth({revision:'r1',months:['2026-09']},'2026-09')",ctx);a.deepEqual(calls,['daily','skus']);a.equal(full.skus.length,1);sandbox.mockSDK.httpsCallable=()=>async args=>({data:{revision:'wrong',month:args.month,kind:args.kind,rows:[],total:0,nextCursor:null}});await a.rejects(vm.runInContext("loadMonth({revision:'r1',months:['2026-09']},'2026-09',{dailyOnly:true})",ctx),/Report changed/);});

test('sales basis changes values while health denominators remain stable, and new data clears on sign-out',async()=>{
 const report=summary('2026-09');report.daily.push({...report.daily[0],status:'Canceled',gmv:40,units:1},{...report.daily[0],status:'Return & Refund',gmv:20,units:1});report.skus.push({...report.skus[0],status:'Canceled',gmv:40,units:1},{...report.skus[0],status:'Return & Refund',gmv:20,units:1});
 const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'viewer',revision:'r1',months:['2026-09']}),history:async()=>[],loadMonth:async()=>report}),el=id=>w.document.getElementById(id);
 vm.runInContext("sessionChanged({user:{uid:'test'},role:'viewer'});",ctx);await flush();
 a.equal(el('gmv').textContent,'฿160');a.match(el('health-summary').textContent,/33\.3%/);
 el('sales-basis').value='completed';el('sales-basis').dispatchEvent(new w.Event('change'));a.equal(el('gmv').textContent,'฿100');a.equal(el('orders').textContent,'1');a.match(el('gmv-label').textContent,/Completed value/);a.match(el('health-summary').textContent,/33\.3%/);
 el('status').value='Canceled';el('status').dispatchEvent(new w.Event('change'));a.equal(el('gmv').textContent,'฿0');a.match(el('health-store-rows').textContent,/33\.3%/);
 w.document.querySelector('[data-view="health"]').click();a.equal(el('health-view').hidden,false);el('reset').click();a.equal(el('sales-basis').value,'all');a.equal(el('gmv').textContent,'฿160');
 w.document.querySelector('[data-view="sources"]').click();a.equal(el('sources-view').hidden,false);a.equal(el('dashboard').hidden,true);a.match(el('source-grid').textContent,/Not connected/);a.match(el('source-coverage').textContent,/2026-09/);
 vm.runInContext('sessionChanged(null);',ctx);for(const id of ['action-grid','health-summary','health-store-rows','source-grid','source-coverage','product-summary','product-chart'])a.equal(el(id).textContent,'');a.equal(el('sources-view').hidden,true);dom.window.close();
});
test('missing current months and failed comparison pages cannot produce a false percentage',async()=>{
 const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'admin',revision:'r1',months:['2026-08','2026-09','2026-10']}),history:async()=>[],loadMonth:async(s,m)=>{if(m==='2026-08')throw Error('Comparison unavailable');return summary(m);}}),el=id=>w.document.getElementById(id);
 vm.runInContext("sessionChanged({user:{uid:'test'},role:'admin'});",ctx);await flush();
 w.document.querySelector('[data-date-mode="custom"]').click();el('date-from').value='2026-09-02';el('date-to').value='2026-10-03';el('apply-dates').click();await flush();a.equal(vm.runInContext('dataset.comparisonAvailable',ctx),false);a.equal(el('gmv-change').textContent,'Prior period unavailable');w.cloudMock.loadMonth=async(s,m)=>summary(m);
 w.document.querySelector('[data-date-mode="year"]').click();await flush();a.match(el('period-status').textContent,/No report for 2026-01/);a.match(el('action-grid').textContent,/Check report coverage/);a.equal(vm.runInContext('dataset.comparisonAvailable',ctx),false);dom.window.close();
});
test('product rankings aggregate stores, obey sales basis and remain withheld for partial months',async()=>{
 const report=summary('2026-09');report.skus.push({...report.skus[0],store:'NKM_TT',gmv:50,units:1},{...report.skus[0],sku:'CLEAN',product:'Cleaner',gmv:40,units:8,status:'Canceled'});
 const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'admin',revision:'r1',months:['2026-09']}),history:async()=>[],loadMonth:async()=>report}),el=id=>w.document.getElementById(id);
 vm.runInContext("sessionChanged({user:{uid:'test'},role:'admin'});",ctx);await flush();w.document.querySelector('[data-view="sku"]').click();a.match(el('product-summary').textContent,/2/);a.match(el('sku-rows').textContent,/78\.9%/);
 w.document.querySelector('[data-product-metric="units"]').click();a.match(el('product-chart').querySelector('.ranked-row').textContent,/CLEAN/);
 el('sales-basis').value='completed';el('sales-basis').dispatchEvent(new w.Event('change'));a.match(el('product-chart').textContent,/W24/);a.ok(!el('product-chart').textContent.includes('CLEAN'));a.match(el('sku-rows').textContent,/100\.0%/);
 w.document.querySelector('[data-date-mode="custom"]').click();el('date-from').value='2026-09-01';el('date-to').value='2026-09-02';el('apply-dates').click();await flush();a.equal(el('product-summary').textContent,'');a.match(el('product-chart').textContent,/complete months/);dom.window.close();
});
