const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{JSDOM}=require('jsdom'),root=path.resolve(__dirname,'../..');
const summary=month=>({mode:'raw',records:[],revision:'r1',month,diagnostics:{sourceUnverified:false},daily:[{date:month+'-01',month,store:'NKM_SHP',platform:'Shopee',status:'Completed',gmv:100,orders:1,units:2}],skus:[{date:month+'-01',month,store:'NKM_SHP',platform:'Shopee',status:'Completed',sku:'W24',product:'Wiper',gmv:100,orders:1,units:2}]}),flush=()=>new Promise(r=>setTimeout(r,10));
test('sales sections share one page and tool navigation preserves mounted frames without new report calls',async()=>{
 let membership=0,reports=0;const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>{membership++;return {role:'viewer',revision:'r1',months:['2026-09']};},history:async()=>[],loadMonth:async(s,m)=>{reports++;return summary(m);}});
 const scrolls=[];w.Element.prototype.scrollIntoView=function(args){scrolls.push(args);};
 vm.runInContext("sessionChanged({user:{uid:'test'},role:'viewer',state:{role:'viewer',revision:'r1',months:['2026-09']}});",ctx);await flush();a.equal(membership,0);const before=reports;
 for(const section of ['overview','stores','sku'])a.equal(w.document.getElementById(section+'-view').hidden,false);
 const click=view=>w.document.querySelector('.sidebar [data-view="'+view+'"]').click();click('stock');const frame=w.document.querySelector('#stock-view iframe');a.ok(frame);click('stores');click('stock');a.equal(w.document.querySelector('#stock-view iframe'),frame);click('customers');click('sku');click('customers');a.equal(w.document.querySelectorAll('iframe').length,2);a.equal(reports,before);a.equal(membership,0);a.equal(scrolls.at(-1).behavior,'smooth');
 vm.runInContext("sessionChanged({blocked:true,user:{uid:'test'}});",ctx);a.equal(w.document.querySelectorAll('iframe').length,0);a.equal(w.document.getElementById('auth-gate').hidden,false);dom.window.close();
});
function harness(mock,settings={}){const dom=new JSDOM(fs.readFileSync(path.join(root,'management.html'),'utf8'),{url:'http://localhost/management.html',runScripts:'outside-only'}),w=dom.window,ctx=dom.getInternalVMContext();const media={matches:settings.dark===true,addEventListener:(event,fn)=>{media.listener=fn;}};w.matchMedia=()=>media;w.scrollTo=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};if(settings.savedTheme)w.localStorage.setItem('nakama-theme',settings.savedTheme);const RealDate=w.Date;w.Date=class extends RealDate{constructor(...args){super(...(args.length?args:['2026-10-01T05:00:00Z']));}static now(){return new RealDate('2026-10-01T05:00:00Z').getTime();}};w.cloudMock=mock;for(const f of ['workspace-shell.js','engine.js','store-labels.js','report.js','date-range.js','charts.js','insights.js','insight-ui.js','theme.js'])vm.runInContext(fs.readFileSync(path.join(root,'assets',f),'utf8'),ctx);const src=fs.readFileSync(path.join(root,'assets/management.js'),'utf8').split("import('./cloud.js")[0];vm.runInContext(src+'\ncloud=cloudMock;',ctx);return {dom,w,ctx,media};}
test('period comparison loads only relevant months, viewer upload denied, reset retains month, sign-out clears records',async()=>{const fetched=[],{dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'viewer',revision:'r1',months:['2026-08','2026-09']}),history:async()=>[],loadMonth:async(s,m)=>{fetched.push(m);return summary(m);}}),el=id=>w.document.getElementById(id);vm.runInContext("sessionChanged({user:{uid:'test'},role:'viewer'});",ctx);await flush();a.deepEqual(fetched,['2026-09','2026-08']);a.equal(el('auth-gate').hidden,true);a.equal(el('upload').disabled,true);a.equal(el('gmv').textContent,'฿100');a.equal(vm.runInContext('selectedRange.from',ctx),'2026-09-01');el('reset').click();a.equal(vm.runInContext('selectedRange.from',ctx),'2026-09-01');setRange(w,'2026-08-01','2026-08-31');await flush();a.deepEqual(fetched,['2026-09','2026-08','2026-08']);a.equal(vm.runInContext('selectedRange.from',ctx),'2026-08-01');vm.runInContext("cloudMock.workspace=async()=>({role:'importer',revision:'r1',months:['2026-09']});sessionChanged({user:{uid:'test'},role:'importer'});",ctx);await flush();a.equal(el('upload').disabled,false);vm.runInContext('sessionChanged(null);',ctx);a.equal(el('auth-gate').hidden,false);for(const id of ['store-rows','sku-rows','trend'])a.equal(el(id).textContent,'');a.equal(el('gmv').textContent,'—');a.equal(el('upload').disabled,true);a.equal(vm.runInContext('dataset',ctx),null);dom.window.close();});
test('late report response cannot expose data after revocation',async()=>{let finish;const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'viewer',revision:'r1',months:['2026-09']}),history:async()=>[],loadMonth:()=>new Promise(r=>{finish=r;})});vm.runInContext('sessionChanged({user:{uid:"test"},role:"viewer"});',ctx);await flush();vm.runInContext('sessionChanged({blocked:true,user:{uid:"test"}});',ctx);finish(summary('2026-09'));await flush();a.equal(vm.runInContext('dataset',ctx),null);a.equal(w.document.getElementById('auth-gate').hidden,false);a.equal(w.document.getElementById('gmv').textContent,'—');dom.window.close();});
test('excluded orders stay out of legacy displays and previews allow an exclusion-only update',async()=>{const report=summary('2026-09');for(const kind of ['daily','skus'])report[kind].push({...report[kind][0],status:'Platform Processing',gmv:999,orders:9,units:9});const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'admin',revision:'r1',months:['2026-09']}),history:async()=>[],loadMonth:async()=>report}),el=id=>w.document.getElementById(id);vm.runInContext("sessionChanged({user:{uid:'test'},role:'admin'});",ctx);await flush();a.equal(el('gmv').textContent,'฿100');a.equal(el('orders').textContent,'1');a.equal(el('units').textContent,'2');a.ok(!el('status').textContent.includes('Platform Processing'));a.ok(!el('statuses').textContent.includes('Platform Processing'));a.ok(!el('sku-rows').textContent.includes('999'));w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};vm.runInContext("preview({daily:[],skus:[],records:[],orderCount:0,diagnostics:{invalid:0,excludedOrders:2,excludedRows:3,errors:[]}});",ctx);a.equal(el('confirm').disabled,false);a.match(el('preview-details').textContent,/2 orders entirely excluded · 3 Platform Processing rows ignored/);a.match(el('preview-details').textContent,/0 included orders/);vm.runInContext("preview({daily:[],skus:[],records:[],orderCount:0,diagnostics:{invalid:1,excludedOrders:2,excludedRows:3,errors:[]}});",ctx);a.equal(el('confirm').disabled,true);dom.window.close();});
test('custom, yesterday and year periods use real dates, and partial-month products are withheld',async()=>{const make=(m,items)=>({...summary(m),daily:items.map(([date,gmv])=>({date,month:m,store:'NKM_SHP',platform:'Shopee',status:'Completed',gmv,orders:1,units:2})),skus:[{...summary(m).skus[0],gmv:items.reduce((n,r)=>n+r[1],0)}]}),reports={'2026-08':make('2026-08',[['2026-08-01',10]]),'2026-09':make('2026-09',[['2026-09-29',200],['2026-09-30',100]]),'2026-10':make('2026-10',[['2026-10-01',300],['2026-10-05',400]])},calls=[],{dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'admin',revision:'r1',months:Object.keys(reports)}),history:async()=>[],loadMonth:async(s,m,options)=>{calls.push({month:m,dailyOnly:options?.dailyOnly});return reports[m];}}),el=id=>w.document.getElementById(id);vm.runInContext("NKMReport.today=()=> '2026-10-01';sessionChanged({user:{uid:'test'},role:'admin'});",ctx);await flush();a.equal(el('gmv').textContent,'฿700');a.match(el('gmv-change').textContent,/133.3%/);setRange(w,'2026-09-30','2026-10-01');await flush();a.equal(el('gmv').textContent,'฿400');a.equal(el('orders').textContent,'2');a.equal(el('units').textContent,'4');w.document.querySelector('[data-view="sku"]').click();a.equal(el('sku-range-notice').hidden,false);a.equal(w.document.querySelector('[data-export="skus"]').disabled,true);a.match(el('sku-rows').textContent,/full month/);a.equal(vm.runInContext('skuRows().length',ctx),0);setRange(w,'2026-10-05','2026-10-01');a.match(w.document.querySelector('.date-range-error').textContent,/valid dates/);w.document.querySelector('[data-range-cancel]').click();a.equal(el('gmv').textContent,'฿400');applyPreset(w,'yesterday');await flush();a.equal(el('gmv').textContent,'฿100');a.match(el('period-title').textContent,/30 Sept? 2026/);a.equal(vm.runInContext('activeRange.to',ctx),'2026-09-30');applyPreset(w,'year');await flush();a.equal(el('gmv').textContent,'฿1,010');a.equal(vm.runInContext('dataset.skuAvailable',ctx),true);a.equal(w.document.querySelector('[data-export="skus"]').disabled,false);a.equal(el('sku-range-notice').hidden,false);a.match(el('sku-range-notice').textContent,/Missing reports/);a.equal(el('insight-grid').querySelectorAll('.insight-card').length,6);a.ok(el('trend').querySelector('svg'));a.ok(el('orders-chart').querySelector('svg'));a.ok(el('platform-bars').querySelector('svg'));vm.runInContext('sessionChanged(null);',ctx);for(const id of ['insight-grid','store-chart','orders-chart'])a.equal(el(id).textContent,'');a.equal(vm.runInContext('reportCache.size',ctx),0);dom.window.close();});
test('theme follows system in Auto and saves manual appearance choices',async()=>{const {dom,w,media}=harness({pendingImport:()=>null},{dark:true});await flush();const el=mode=>w.document.querySelector('button[data-theme-mode="'+mode+'"]');a.equal(w.document.documentElement.dataset.theme,'dark');a.equal(el('auto').getAttribute('aria-pressed'),'true');el('light').click();a.equal(w.document.documentElement.dataset.theme,'light');a.equal(w.localStorage.getItem('nakama-theme'),'light');media.matches=true;media.listener();a.equal(w.document.documentElement.dataset.theme,'light');el('dark').click();a.equal(w.document.documentElement.dataset.theme,'dark');el('auto').click();media.matches=false;media.listener();a.equal(w.document.documentElement.dataset.theme,'light');a.equal(w.localStorage.getItem('nakama-theme'),'auto');dom.window.close();const restored=harness({pendingImport:()=>null},{dark:false,savedTheme:'dark'});await flush();a.equal(restored.w.document.documentElement.dataset.theme,'dark');a.equal(restored.w.document.querySelector('button[data-theme-mode="dark"]').getAttribute('aria-pressed'),'true');restored.dom.window.close();});
test('daily-only cloud requests preserve pagination validation and do not fetch SKU pages',async()=>{const calls=[],sandbox={window:{NKM_CLOUD_CONFIG:{firebase:{projectId:'nakama-sales',apiKey:'public'}}},mockSDK:{httpsCallable:(functions,name)=>async args=>{calls.push(args.kind);return {data:{revision:args.revision,month:args.month,kind:args.kind,total:1,rows:[{date:args.month+'-01',kind:args.kind}],nextCursor:null}};}}},ctx=vm.createContext(sandbox),source=fs.readFileSync(path.join(root,'assets/cloud.js'),'utf8').replace("import * as F from './vendor/firebase-sdk.js?v=glass-20261001';",'const F=mockSDK;').replace(/\bexport /g,'');vm.runInContext(source,ctx);const daily=await vm.runInContext("loadMonth({revision:'r1',months:['2026-09']},'2026-09',{dailyOnly:true})",ctx);a.deepEqual(calls,['daily']);a.equal(daily.daily.length,1);a.equal(daily.skus.length,0);calls.length=0;const full=await vm.runInContext("loadMonth({revision:'r1',months:['2026-09']},'2026-09')",ctx);a.deepEqual(calls,['daily','skus']);a.equal(full.skus.length,1);sandbox.mockSDK.httpsCallable=()=>async args=>({data:{revision:'wrong',month:args.month,kind:args.kind,rows:[],total:0,nextCursor:null}});await a.rejects(vm.runInContext("loadMonth({revision:'r1',months:['2026-09']},'2026-09',{dailyOnly:true})",ctx),/Report changed/);});

test('sales basis changes values while health denominators remain stable, and new data clears on sign-out',async()=>{
 const report=summary('2026-09');report.daily.push({...report.daily[0],status:'Canceled',gmv:40,units:1},{...report.daily[0],status:'Return & Refund',gmv:20,units:1});report.skus.push({...report.skus[0],status:'Canceled',gmv:40,units:1},{...report.skus[0],status:'Return & Refund',gmv:20,units:1});
 const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'viewer',revision:'r1',months:['2026-09']}),history:async()=>[],loadMonth:async()=>report}),el=id=>w.document.getElementById(id);
 vm.runInContext("sessionChanged({user:{uid:'test'},role:'viewer'});",ctx);await flush();
 a.equal(el('gmv').textContent,'฿160');a.match(el('health-summary').textContent,/33\.3%/);
 el('sales-basis').value='completed';el('sales-basis').dispatchEvent(new w.Event('change'));a.equal(el('gmv').textContent,'฿100');a.equal(el('orders').textContent,'1');a.match(el('gmv-label').textContent,/Completed value/);a.match(el('health-summary').textContent,/33\.3%/);
 el('status').value='Canceled';el('status').dispatchEvent(new w.Event('change'));a.equal(el('gmv').textContent,'฿0');a.match(el('health-store-rows').textContent,/33\.3%/);
 w.document.querySelector('[data-view="health"]').click();a.equal(el('health-view').hidden,false);el('reset').click();a.equal(el('sales-basis').value,'all');a.equal(el('gmv').textContent,'฿160');
 w.document.querySelector('[data-view="sources"]').click();a.equal(el('sources-view').hidden,false);a.equal(el('dashboard').hidden,true);a.match(el('source-grid').textContent,/Not connected/);a.match(el('source-coverage').textContent,/2026-09/);
 vm.runInContext('sessionChanged(null);',ctx);for(const id of ['action-grid','health-summary','health-store-rows','source-grid','source-coverage','product-summary','product-chart'])a.equal(el(id).textContent,'');a.equal(el('sources-view').hidden,true);dom.window.close();
});
test('missing current months and failed comparison pages cannot produce a false percentage',async()=>{
 const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'admin',revision:'r1',months:['2026-08','2026-09','2026-10']}),history:async()=>[],loadMonth:async(s,m)=>{if(m==='2026-08')throw Error('Comparison unavailable');return summary(m);}}),el=id=>w.document.getElementById(id);
 vm.runInContext("sessionChanged({user:{uid:'test'},role:'admin'});",ctx);await flush();
 setRange(w,'2026-09-02','2026-10-03');await flush();a.equal(vm.runInContext('dataset.comparisonAvailable',ctx),false);a.equal(el('gmv-change').textContent,'Prior period unavailable');w.cloudMock.loadMonth=async(s,m)=>summary(m);
 applyPreset(w,'year');await flush();a.match(el('period-status').textContent,/No report for 2026-01/);a.match(el('action-grid').textContent,/Check report coverage/);a.equal(vm.runInContext('dataset.comparisonAvailable',ctx),false);dom.window.close();
});
test('product rankings aggregate stores, obey sales basis and remain withheld for partial months',async()=>{
 const report=summary('2026-09');report.skus.push({...report.skus[0],store:'NKM_TT',gmv:50,units:1},{...report.skus[0],sku:'CLEAN',product:'Cleaner',gmv:40,units:8,status:'Canceled'});
 const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'admin',revision:'r1',months:['2026-09']}),history:async()=>[],loadMonth:async()=>report}),el=id=>w.document.getElementById(id);
 vm.runInContext("sessionChanged({user:{uid:'test'},role:'admin'});",ctx);await flush();w.document.querySelector('[data-view="sku"]').click();a.match(el('product-summary').textContent,/2/);a.match(el('sku-rows').textContent,/78\.9%/);
 w.document.querySelector('[data-product-metric="units"]').click();a.match(el('product-chart').querySelector('.ranked-row').textContent,/CLEAN/);
 el('sales-basis').value='completed';el('sales-basis').dispatchEvent(new w.Event('change'));a.match(el('product-chart').textContent,/W24/);a.ok(!el('product-chart').textContent.includes('CLEAN'));a.match(el('sku-rows').textContent,/100\.0%/);
 setRange(w,'2026-09-01','2026-09-02');await flush();a.equal(el('product-summary').textContent,'');a.match(el('product-chart').textContent,/complete months/);dom.window.close();
});

test('every Management sidebar tab selects its section and supports history navigation',async()=>{const {dom,w}=harness({pendingImport:()=>null,workspace:async()=>({role:'viewer',revision:'r1',months:['2026-09']}),history:async()=>[],loadMonth:async(s,m)=>summary(m)});vm.runInContext("sessionChanged({user:{uid:'test'},role:'viewer'});",dom.getInternalVMContext());await flush();for(const view of ['stores','sku','health','sources','imports','overview']){const button=w.document.querySelector('.sidebar [data-view="'+view+'"]');button.click();a.equal(w.location.hash,'#'+view);a.equal(button.classList.contains('active'),true);a.equal(w.document.getElementById(view+'-view').hidden,false);}w.location.hash='#stores';await flush();a.equal(w.document.getElementById('stores-view').hidden,false);a.equal(w.document.querySelector('.sidebar [data-view="stores"]').getAttribute('aria-current'),'page');a.ok(w.document.querySelector('.actions a[data-view="stock"]'));dom.window.close();});

test('grouped menu opens PO directly, reuses inventory and clears summary and menu on revocation',async()=>{
 let reports=0;const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'admin',revision:'r1',months:['2026-09']}),history:async()=>[],loadMonth:async(s,m)=>{reports++;return summary(m);}}),el=id=>w.document.getElementById(id);
 vm.runInContext("sessionChanged({user:{uid:'test'},role:'admin'});",ctx);await flush();
 a.deepEqual([...w.document.querySelectorAll('.sidebar .nav-group h2')].map(n=>n.textContent),['Store Overview','Inventory Management','Data & Imports']);
 a.equal(el('summary-view').hidden,false);a.equal(el('summary-heading').textContent,'Executive Summary');a.equal(el('summary-view').querySelectorAll('.insight-card').length,6);a.ok(el('summary-view').contains(el('gmv')));a.ok(el('summary-view').contains(el('action-grid')));const before=reports;
 el('open-navigation').click();a.equal(el('navigation-dialog').open,true);a.equal(el('open-navigation').getAttribute('aria-expanded'),'true');w.document.querySelector('#navigation-dialog [data-view="pos"]').click();
 a.equal(el('navigation-dialog').open,false);a.equal(w.location.hash,'#pos');a.equal(el('stock-view').hidden,false);a.equal(el('dashboard').hidden,true);const frame=el('stock-view').querySelector('iframe');a.ok(frame.src.endsWith('?embedded=1#pos'));const tabs=[];frame.contentWindow.NKMStockNavigate=tab=>tabs.push(tab);
 w.document.querySelector('.sidebar [data-view="stock"]').click();a.equal(el('stock-view').querySelector('iframe'),frame);a.deepEqual(tabs,['overview']);w.document.querySelector('.sidebar [data-view="pos"]').click();a.deepEqual(tabs,['overview','pos']);
 vm.runInContext('render();',ctx);a.deepEqual(tabs,['overview','pos']);w.location.hash='#stock';await flush();a.equal(frame.dataset.section,'overview');a.equal(w.document.querySelector('.sidebar [data-view="stock"]').getAttribute('aria-current'),'page');
 w.document.querySelector('.sidebar [data-view="summary"]').click();a.equal(el('summary-view').hidden,false);a.equal(reports,before);el('open-navigation').click();el('navigation-dialog').close();a.equal(el('open-navigation').getAttribute('aria-expanded'),'false');el('open-navigation').click();vm.runInContext("sessionChanged({blocked:true,user:{uid:'test'}});",ctx);
 a.equal(el('navigation-dialog').open,false);a.equal(el('summary-view').textContent.includes('฿100'),false);a.equal(el('insight-grid').textContent,'');a.equal(el('action-grid').textContent,'');a.equal(w.document.querySelectorAll('iframe').length,0);el('open-navigation').click();a.equal(el('navigation-dialog').open,false);dom.window.close();
});

function setRange(w,from,to){w.document.querySelector('.date-range-trigger').click();for(const [selector,value] of [['[data-range-from]',from],['[data-range-to]',to]]){const input=w.document.querySelector(selector);input.value=value;input.dispatchEvent(new w.Event('input'));}w.document.querySelector('[data-range-apply]').click();}
function applyPreset(w,key){w.document.querySelector('.date-range-trigger').click();w.document.querySelector('[data-date-preset="'+key+'"]').click();w.document.querySelector('[data-range-apply]').click();}

test('import conflict details remain visible, preserve loaded reports, and clear on dismiss or revocation',async()=>{const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'admin',revision:'r1',months:['2026-09']}),history:async()=>[],loadMonth:async(s,m)=>summary(m)}),el=id=>w.document.getElementById(id);vm.runInContext("sessionChanged({user:{uid:'test'},role:'admin'});",ctx);await flush();const before=el('gmv').textContent;w.Worker=class{postMessage(){this.onmessage({data:{error:'Order 1078238338262289 has conflicting dates/statuses',code:'order-conflict',details:{rows:[{file:'part(1).xlsx',row:2,date:'2026-09-01',status:'Completed',sku:'A'},{file:'part(12).xlsx',row:55,date:'2026-09-01',status:'Canceled',sku:'B'}]}}});}terminate(){}};w.testFiles=[{name:'part(1).xlsx',size:100,lastModified:1,arrayBuffer:async()=>new ArrayBuffer(10)}];await vm.runInContext('upload(testFiles)',ctx);a.equal(el('import-error').hidden,false);a.match(el('import-error-message').textContent,/1078238338262289/);a.match(el('import-error-rows').textContent,/Row 55/);a.match(el('import-error-rows').textContent,/Canceled/);a.equal(el('toast').hidden,true);a.equal(el('gmv').textContent,before);a.equal(vm.runInContext('importBusy',ctx),false);a.equal(el('upload').disabled,false);el('dismiss-import-error').click();a.equal(el('import-error').hidden,true);await vm.runInContext('upload(testFiles)',ctx);vm.runInContext('sessionChanged(null)',ctx);a.equal(el('import-error').hidden,true);a.equal(el('import-error-message').textContent,'');a.equal(el('import-error-rows').textContent,'');dom.window.close();});

test('revocation during import preview cancels reading and cannot show a late private error',async()=>{const {dom,w,ctx}=harness({pendingImport:()=>null,workspace:async()=>({role:'admin',revision:'r1',months:['2026-09']}),history:async()=>[],loadMonth:async(s,m)=>summary(m)});vm.runInContext("sessionChanged({user:{uid:'test'},role:'admin'});",ctx);await flush();let previewWorker;w.Worker=class{constructor(){previewWorker=this;}postMessage(){}terminate(){this.stopped=true;}};w.testFiles=[{name:'orders.xlsx',size:100,lastModified:1,arrayBuffer:async()=>new ArrayBuffer(10)}];const reading=vm.runInContext('upload(testFiles)',ctx);await flush();a.equal(vm.runInContext('importBusy',ctx),true);vm.runInContext('sessionChanged(null)',ctx);await reading;a.equal(previewWorker.stopped,true);a.equal(vm.runInContext('importBusy',ctx),false);a.equal(w.document.getElementById('import-error').hidden,true);dom.window.close();});
