'use strict';
const XLSX=require('./vendor/xlsx.full.min.js'),Ads=require('./ads-engine');
module.exports=function({db,bucket,member,C,Timestamp}){
 const maxRows=50000,maxBytes=16*1024*1024;
 function parse(bytes,name,options={}){let workbook;try{const csv=/\.csv$/i.test(name),input=csv?new TextDecoder('utf-8',{fatal:true}).decode(bytes):bytes;workbook=XLSX.read(input,{type:csv?'string':'buffer',dense:true,raw:true,sheetRows:1003});}catch{C.fail('invalid-argument',name+': unreadable XLSX/CSV file.');}if(workbook.SheetNames.length!==1)C.fail('invalid-argument',name+': upload a single-sheet Shopee Ads Overview or TikTok GMV Max daily export.');const sheet=workbook.Sheets[workbook.SheetNames[0]],ref=sheet['!fullref']||sheet['!ref'];if(ref&&XLSX.utils.decode_range(ref).e.r>=1002)C.fail('invalid-argument',name+': too many advertising rows.');try{return Ads.parse(XLSX.utils.sheet_to_json(sheet,{header:1,raw:true,defval:null}),name,options);}catch(e){C.fail('invalid-argument',e.message);}}
 async function snapshot(workspace){if(!workspace?.path)return [];const [bytes]=await bucket.file(workspace.path).download({validation:'crc32c'});if(bytes.length>maxBytes)C.fail('data-loss','Advertising snapshot exceeds its limit.');const rows=JSON.parse(bytes.toString());if(!Array.isArray(rows)||rows.length>maxRows)C.fail('data-loss','Invalid advertising snapshot.');return rows;}
 function status(id,job){return {id,state:job.state,revision:job.revision||null,changes:job.changes||null};}
 async function jobFor(request){const user=await member(request,['importer','admin']),id=C.uuid(request.data?.id),ref=db.doc('adImports/'+id),job=(await ref.get()).data();if(!job||job.owner!==user.uid)C.fail('permission-denied','Advertising import unavailable.');return {user,id,ref,job};}
 async function handle(request){const op=request.data?.op||'load';
  if(op==='begin'){const user=await member(request,['importer','admin']),files=C.manifest(request.data?.files),tiktokStore=request.data?.tiktokStore;if(tiktokStore!==undefined&&!Ads.validStore(tiktokStore))C.fail('invalid-argument','Choose a valid TikTok store.');if(files.some(f=>f.size>4*1024*1024)||files.reduce((n,f)=>n+f.size,0)>16*1024*1024)C.fail('invalid-argument','Advertising files may be at most 4 MiB each and 16 MiB per batch.');const id=C.randomId(),now=Date.now(),rate=db.doc('limits/ads-'+user.uid);await db.runTransaction(async tx=>{const saved=(await tx.get(rate)).data()||{},recent=saved.windowStart>now-60000,attempts=recent?(saved.attempts||0)+1:1;if(attempts>5)C.fail('resource-exhausted','Too many advertising imports. Wait one minute.');tx.set(rate,{windowStart:recent?saved.windowStart:now,attempts});tx.create(db.doc('adImports/'+id),{owner:user.uid,state:'uploading',tiktokStore:tiktokStore?.trim()||'',files:Object.fromEntries(files.map(f=>[f.index,f])),createdAt:Timestamp.fromMillis(now),expiresAt:Timestamp.fromMillis(now+86400000)});});return {id,files:files.map(f=>({...f,path:`adUploads/${user.uid}/${id}/${f.index}`}))};}
  if(op==='status'){const {id,job}=await jobFor(request);return status(id,job);}
  if(op==='upload'){
   const {user,id,job}=await jobFor(request),index=request.data?.index,encoded=request.data?.base64;
   if(job.state!=='uploading'||job.expiresAt.toMillis()<=Date.now())C.fail('failed-precondition','Advertising upload expired or finished. Select the files again.');
   if(typeof index!=='string'||!/^\d{1,2}$/.test(index)||!Object.hasOwn(job.files,index))C.fail('invalid-argument','Advertising file is not in this import.');
   const f=job.files[index];
   if(typeof encoded!=='string'||encoded.length>Math.ceil(4*1024*1024/3)*4||!encoded.length||!/^[A-Za-z0-9+/]+={0,2}$/.test(encoded))C.fail('invalid-argument','Invalid advertising file encoding.');
   const bytes=Buffer.from(encoded,'base64');
   if(bytes.length!==f.size||bytes.toString('base64')!==encoded)C.fail('invalid-argument',f.name+': upload does not match the manifest.');
   const object=bucket.file(`adUploads/${user.uid}/${id}/${index}`);
   try{await object.save(bytes,{resumable:false,preconditionOpts:{ifGenerationMatch:0},metadata:{contentType:f.contentType,cacheControl:'no-store'}});}
   catch(e){if(e.code!==412)throw e;const [metadata]=await object.getMetadata();if(Number(metadata.size)!==f.size||metadata.contentType!==f.contentType)C.fail('already-exists','This advertising file was already uploaded with different contents. Select the files again.');const [saved]=await bucket.file(object.name,{generation:metadata.generation}).download({validation:'crc32c'});if(!saved.equals(bytes))C.fail('already-exists','This advertising file was already uploaded with different contents. Select the files again.');}
   await member(request,['importer','admin']);return {id,index,state:'uploaded'};
  }
  if(op==='load'){await member(request);const workspace=(await db.doc('adWorkspace/main').get()).data(),revision=workspace?.revision||null;if(request.data?.revision&&request.data.revision!==revision)C.fail('aborted','Advertising reports changed. Refresh to load the latest reports.');const offset=request.data?.cursor==null?0:Number(request.data.cursor);if(!Number.isSafeInteger(offset)||offset<0||offset>maxRows)C.fail('invalid-argument','Invalid advertising page.');const all=await snapshot(workspace);if(offset>all.length)C.fail('invalid-argument','Advertising page is outside this report.');let end=offset,bytes=256;while(end<all.length&&end-offset<300){const size=Buffer.byteLength(JSON.stringify(all[end]))+1;if(end>offset&&bytes+size>100000)break;bytes+=size;end++;}await member(request);return {revision,rows:all.slice(offset,end),total:all.length,nextCursor:end<all.length?String(end):null,updatedAt:workspace?.updatedAt?.toMillis?.()||null};}
  if(op!=='process')C.fail('invalid-argument','Unknown advertising operation.');
  const {user,id,ref,job}=await jobFor(request);if(job.state==='complete')return status(id,job);if(job.expiresAt.toMillis()<Date.now())C.fail('failed-precondition','Advertising upload expired. Select the files again.');const workspaceRef=db.doc('adWorkspace/main'),workspace=(await workspaceRef.get()).data(),incoming=[];
  for(const f of Object.values(job.files)){const object=bucket.file(`adUploads/${user.uid}/${id}/${f.index}`);let metadata;try{[metadata]=await object.getMetadata();}catch(e){if(e.code===404)C.fail('failed-precondition',f.name+': upload is missing. Select all files again.');throw e;}if(Number(metadata.size)!==f.size||metadata.contentType!==f.contentType)C.fail('invalid-argument',f.name+': upload does not match the manifest.');const [bytes]=await bucket.file(object.name,{generation:metadata.generation}).download({validation:'crc32c'});if(metadata.metadata?.firebaseStorageDownloadTokens)await object.setMetadata({metadata:{firebaseStorageDownloadTokens:null}});incoming.push(...parse(bytes,f.name,{tiktokStore:job.tiktokStore}));}
  let merged;try{merged=Ads.merge(await snapshot(workspace),incoming);}catch(e){C.fail('invalid-argument',e.message);}const bytes=Buffer.from(JSON.stringify(merged.rows));if(merged.rows.length>maxRows||bytes.length>maxBytes)C.fail('resource-exhausted','Advertising history exceeds the supported workspace size.');
  const changes={added:merged.added,replaced:merged.replaced,duplicates:merged.duplicates},changed=Boolean(merged.added||merged.replaced),revision=changed?C.randomId():(workspace?.revision||null),path=changed?`private/ads/${revision}.json`:workspace?.path;
  if(changed)await bucket.file(path).save(bytes,{resumable:false,preconditionOpts:{ifGenerationMatch:0},metadata:{contentType:'application/json',cacheControl:'no-store'}});
  await member(request,['importer','admin']);const now=Timestamp.now();
  return db.runTransaction(async tx=>{const [current,currentJob,m]=await Promise.all([tx.get(workspaceRef),tx.get(ref),tx.get(db.doc('members/'+user.uid))]);C.role(request.auth,m.data(),['importer','admin']);if(currentJob.data()?.state==='complete')return status(id,currentJob.data());if((current.data()?.revision||null)!==(workspace?.revision||null))C.fail('aborted','Another advertising import finished first. Retry this pending import.');if(changed)tx.set(workspaceRef,{revision,path,updatedAt:now,updatedBy:user.uid});tx.update(ref,{state:'complete',revision,changes,completedAt:now});return {id,state:'complete',revision,changes};});
 }
 return {handle,parse};
};
