'use strict';
const crypto=require('node:crypto'),zlib=require('node:zlib'),E=require('./engine'),XLSX=require('./vendor/xlsx.full.min.js');
const LIMITS=Object.freeze({files:40,fileBytes:32*1024*1024,totalBytes:128*1024*1024,rows:600000,orders:1000000,snapshotBytes:256*1024*1024,chunkBytes:160*1024,pageBytes:112*1024,pageRows:500,months:600});
class Problem extends Error{constructor(code,message,details){super(message);this.code=code;this.details=details;}}
const fail=(code,message,details)=>{throw new Problem(code,message,details);};
function project(id){if(typeof id!=='string'||!id||/attendance|YOUR_NAKAMA_PROJECT_ID/i.test(id)||! /^[a-z][a-z0-9-]{4,61}[a-z0-9]$/.test(id))fail('failed-precondition','Use a dedicated Nakama Firebase project.');return id;}
function role(auth,member,allowed=['viewer','importer','admin']){if(!auth?.uid)fail('unauthenticated','Sign in to Nakama Management.');const value=auth.token?.nakamaRole;if(member?.enabled!==true||member.role!==value||!allowed.includes(value))fail('permission-denied','Your account does not have access to this action.');return {uid:auth.uid,role:value};}
function uuid(value){if(typeof value!=='string'||! /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(value))fail('invalid-argument','Invalid import or revision ID.');return value;}
function manifest(input){if(!Array.isArray(input)||!input.length||input.length>LIMITS.files)fail('invalid-argument','Select 1–40 XLSX or CSV files.');let total=0;const names=new Set();return input.map((f,index)=>{if(!f||typeof f.name!=='string'||f.name.length>200||/[\x00-\x1f/\\]/.test(f.name)||! /\.(xlsx|csv)$/i.test(f.name)||names.has(f.name))fail('invalid-argument','Select uniquely named XLSX/CSV files.');names.add(f.name);if(!Number.isSafeInteger(f.size)||f.size<1||f.size>LIMITS.fileBytes)fail('invalid-argument','Each file must be between 1 byte and 32 MiB.');total+=f.size;if(total>LIMITS.totalBytes)fail('invalid-argument','One batch may contain at most 128 MiB.');return {index:String(index),name:f.name,size:f.size,lastModified:Number.isSafeInteger(f.lastModified)?f.lastModified:0,contentType:/\.csv$/i.test(f.name)?'text/csv':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'};}).sort((a,b)=>a.lastModified-b.lastModified||Number(a.index)-Number(b.index));}
function parse(buffer,name){let w;try{w=XLSX.read(buffer,{type:'buffer',dense:true,raw:true,sheetRows:LIMITS.rows+2});}catch{fail('invalid-argument',`${name}: unreadable XLSX/CSV file.`);}if(w.Workbook?.WBProps?.date1904)fail('invalid-argument',`${name}: convert the 1904 date system first.`);if(w.Sheets['DATA Orders'])fail('invalid-argument','Upload raw orders, not previously calculated report workbooks.');const sheet=w.Sheets[w.SheetNames[0]],range=sheet?.['!fullref']||sheet?.['!ref'];if(!sheet)fail('invalid-argument',`${name}: no worksheet.`);if(range&&XLSX.utils.decode_range(range).e.r>LIMITS.rows)fail('resource-exhausted',`${name}: too many rows. Split the export.`);const rows=XLSX.utils.sheet_to_json(sheet,{header:1,raw:true,defval:null});if(rows.length<2)fail('invalid-argument',`${name}: no orders.`);const headers=rows[0],cols=E.columns(headers);for(const key of ['id','date','store','platform','status','sku','product','price','qty'])if(cols[key]<0)fail('invalid-argument',`${name}: missing ${key} header.`);for(let i=1;i<rows.length;i++)for(const col of [cols.id,cols.sku,cols.product,cols.store,cols.platform,cols.status,cols.marketplaceStore])if(col>=0&&typeof rows[i][col]==='string'&&rows[i][col].length>1000)fail('invalid-argument',`${name}, row ${i+1}: required text exceeds 1,000 characters.`);return {name,headers,rows:rows.slice(1)};}
function calculate(files,existing=[]){if(files.reduce((n,f)=>n+f.rows.length,0)>LIMITS.rows)fail('resource-exhausted','One import may contain at most 600,000 rows.');let data;try{data=E.raw(files,existing);}catch(e){fail('invalid-argument',e.message);}if(data.diagnostics.invalid)fail('invalid-argument','Invalid rows blocked this import.',data.diagnostics);if(!data.records.length)fail('invalid-argument','No valid order records.');if(data.records.length>LIMITS.orders)fail('resource-exhausted','Workspace exceeds one million orders.');for(const o of data.records)for(const l of o.lines)if(!Number.isFinite(l.price*l.qty)||l.price*l.qty>1e12)fail('invalid-argument','An order amount is out of range.');if(data.daily.some(r=>!Number.isFinite(r.gmv)||!Number.isSafeInteger(r.orders)||!Number.isSafeInteger(r.units)))fail('invalid-argument','Totals exceed supported numeric limits.');return data;}
function packRows(rows){const result=[];let chunk=[],bytes=2;for(const row of rows){const size=Buffer.byteLength(JSON.stringify(row))+1;if(size+512>LIMITS.pageBytes)fail('resource-exhausted','A summary row exceeds the report page limit.');if(chunk.length&&bytes+size>LIMITS.chunkBytes){result.push(chunk);chunk=[];bytes=2;}chunk.push(row);bytes+=size;}if(chunk.length)result.push(chunk);return result;}
function reports(data){const months=[...new Set(data.daily.map(r=>r.month))].sort();if(months.length>LIMITS.months)fail('resource-exhausted','Workspace exceeds 600 months.');return months.map(month=>{const d=data.daily.filter(r=>r.month===month).sort((a,b)=>a.date.localeCompare(b.date)||a.store.localeCompare(b.store)||a.platform.localeCompare(b.platform)||a.status.localeCompare(b.status)),s=data.skus.filter(r=>r.month===month).sort((a,b)=>b.gmv-a.gmv||a.sku.localeCompare(b.sku)||a.store.localeCompare(b.store)||a.status.localeCompare(b.status)),daily=packRows(d),skus=packRows(s);return {month,daily,skus,meta:{dailyRows:d.length,skuRows:s.length,dailyChunks:daily.length,skuChunks:skus.length,gmv:Math.round(d.reduce((n,r)=>n+r.gmv,0)*100)/100,orders:d.reduce((n,r)=>n+r.orders,0),units:d.reduce((n,r)=>n+r.units,0)}};});}
function snapshot(records){const bytes=Buffer.from(JSON.stringify(records));if(bytes.length>LIMITS.snapshotBytes)fail('resource-exhausted','Canonical data exceeds 256 MiB. Nothing was published.');return zlib.gzipSync(bytes,{level:6});}
function unpack(bytes){return JSON.parse(zlib.gunzipSync(bytes,{maxOutputLength:LIMITS.snapshotBytes}).toString());}
function pageArgs(value){uuid(value?.revision);if(! /^\d{4}-(0[1-9]|1[0-2])$/.test(value?.month||'')||!['daily','skus'].includes(value?.kind))fail('invalid-argument','Choose a valid month and report section.');let chunk=0,offset=0;if(value.cursor!=null){if(typeof value.cursor!=='string'||! /^\d{1,6}\.\d{1,6}$/.test(value.cursor))fail('invalid-argument','Invalid page cursor.');[chunk,offset]=value.cursor.split('.').map(Number);}return {...value,chunk,offset};}
async function page(getChunk,count,{chunk,offset}){const rows=[];let bytes=256;if(chunk>=count){if(count===0&&chunk===0&&offset===0)return {rows,nextCursor:null};fail('invalid-argument','Page cursor outside this report.');}while(chunk<count){const part=await getChunk(chunk);if(!Array.isArray(part))fail('data-loss','A report chunk is unavailable.');if(offset>part.length)fail('invalid-argument','Page cursor outside this chunk.');while(offset<part.length){const row=part[offset],size=Buffer.byteLength(JSON.stringify(row))+1;if(size+256>LIMITS.pageBytes)fail('resource-exhausted','A report row exceeds the page limit.');if(rows.length&&(bytes+size>LIMITS.pageBytes||rows.length>=LIMITS.pageRows))return {rows,nextCursor:chunk+'.'+offset};rows.push(row);bytes+=size;offset++;}chunk++;offset=0;}return {rows,nextCursor:null};}
function leaseValid(lease,token,base,active,now){return lease?.token===token&&lease.expires>now&&(active||null)===(base||null);}
module.exports={LIMITS,Problem,fail,project,role,uuid,manifest,parse,calculate,packRows,reports,snapshot,unpack,pageArgs,page,leaseValid,randomId:()=>crypto.randomUUID()};
