'use strict';
const crypto=require('node:crypto'),E=require('./engine');
const text=v=>String(v??'').trim(),ratio=(a,b)=>b?a/b:null;
const knownProvince=new Set(('กรุงเทพมหานคร กระบี่ กาญจนบุรี กาฬสินธุ์ กำแพงเพชร ขอนแก่น จันทบุรี ฉะเชิงเทรา ชลบุรี ชัยนาท ชัยภูมิ ชุมพร เชียงราย เชียงใหม่ ตรัง ตราด ตาก นครนายก นครปฐม นครพนม นครราชสีมา นครศรีธรรมราช นครสวรรค์ นนทบุรี นราธิวาส น่าน บึงกาฬ บุรีรัมย์ ปทุมธานี ประจวบคีรีขันธ์ ปราจีนบุรี ปัตตานี พระนครศรีอยุธยา พะเยา พังงา พัทลุง พิจิตร พิษณุโลก เพชรบุรี เพชรบูรณ์ แพร่ ภูเก็ต มหาสารคาม มุกดาหาร แม่ฮ่องสอน ยโสธร ยะลา ร้อยเอ็ด ระนอง ระยอง ราชบุรี ลพบุรี ลำปาง ลำพูน เลย ศรีสะเกษ สกลนคร สงขลา สตูล สมุทรปราการ สมุทรสงคราม สมุทรสาคร สระแก้ว สระบุรี สิงห์บุรี สุโขทัย สุพรรณบุรี สุราษฎร์ธานี สุรินทร์ หนองคาย หนองบัวลำภู อ่างทอง อำนาจเจริญ อุดรธานี อุตรดิตถ์ อุทัยธานี อุบลราชธานี').split(' '));
function province(v){let s=text(v).replace(/^(?:จังหวัด|จ\.)\s*/,'').trim();if(/^(?:กรุงเทพฯ|กรุงเทพ|กทม\.?|bangkok)$/i.test(s))s='กรุงเทพมหานคร';return knownProvince.has(s)?s:'';}
function buyer(v){if(typeof v==='number'&&!Number.isSafeInteger(v))return '';const s=text(v);return s&&s.length<=200&&!/[＊*•●]/.test(s)&&!/(?:\.{2,}|…)/.test(s)&&!/(?:^|[._ -])(?:masked|anonymous|unknown|null|n\/a)(?:$|[._ -])/i.test(s)&&!/^(?:-+|0+|x{3,}|\.{2,})$/i.test(s)?s:'';}
function enrichment(secret){return {
 order:(r,c,p,s)=>{if(c.buyer<0&&c.customerCode<0&&c.province<0&&c.country<0)return null;const username=c.buyer>=0?buyer(r[c.buyer]):'',code=c.customerCode>=0?buyer(r[c.customerCode]):'',id=username||code;return {version:1,buyerHash:id&&secret?crypto.createHmac('sha256',secret).update(JSON.stringify([p,s,username?'username':'code',id])).digest('hex'):'',province:province(c.province>=0?r[c.province]:''),country:/^(?:th|thailand|ไทย|ประเทศไทย)$/i.test(text(r[c.country]))?'Thailand':''};},
 line:(r,c)=>c.variation>=0?{variation:text(r[c.variation]).slice(0,500)}:{}
};}
// Exact model tokens in the selected variation/SKU only. Broad listing titles and blade sizes do not identify a car.
const models=[
 ['Isuzu','D-MAX','Pickup',/D[\s-]?MAX|ดีแม็ก|ดีแมก/i],['Isuzu','MU-X','SUV / crossover',/MU[\s-]?X/i],['Isuzu','TFR / Dragon Eye','Pickup',/\bTFR\b|DRAGON\s*EYE/i],
 ['Toyota','Vigo','Pickup',/VIGO|วีโก้/i],['Toyota','Revo','Pickup',/REVO|รีโว่/i],['Toyota','Tiger','Pickup',/TIGER|ไทเกอร์/i],['Toyota','Fortuner','SUV / crossover',/FORTUNER|ฟอร์จูนเนอร์/i],['Toyota','Altis','Passenger car',/ALTIS|อัลติส/i],['Toyota','Vios','Passenger car',/VIOS|วีออส/i],['Toyota','Yaris','Passenger car',/YARIS|ยาริส/i],['Toyota','Camry','Passenger car',/CAMRY|แคมรี่/i],['Toyota','Corolla Cross','SUV / crossover',/COROLLA[\s_-]*CROSS/i],['Toyota','C-HR','SUV / crossover',/C[\s-]?HR/i],['Toyota','Innova','MPV / van',/INNOVA/i],['Toyota','Alphard','MPV / van',/ALPHARD/i],['Toyota','Commuter','MPV / van',/COMMUTER/i],['Toyota','Avanza','MPV / van',/AVANZA/i],['Toyota','Veloz','MPV / van',/VELOZ/i],
 ['Honda','City','Passenger car',/CITY|ซิตี้/i],['Honda','Civic','Passenger car',/CIVIC|ซีวิค/i],['Honda','Jazz','Passenger car',/JAZZ|แจ๊ส/i],['Honda','Accord','Passenger car',/ACCORD|แอคคอร์ด/i],['Honda','Brio','Passenger car',/BRIO/i],['Honda','CR-V','SUV / crossover',/CR[\s-]?V/i],['Honda','HR-V','SUV / crossover',/HR[\s-]?V/i],['Honda','BR-V','SUV / crossover',/BR[\s-]?V/i],['Honda','Mobilio','MPV / van',/MOBILIO/i],['Honda','Freed','MPV / van',/FREED/i],
 ['Mitsubishi','Triton','Pickup',/TRITON|ไทรทัน/i],['Mitsubishi','Strada','Pickup',/STRADA/i],['Mitsubishi','Pajero Sport','SUV / crossover',/PAJERO/i],['Mitsubishi','Mirage','Passenger car',/MIRAGE/i],['Mitsubishi','Attrage','Passenger car',/ATTRAGE/i],['Mitsubishi','Lancer','Passenger car',/LANCER/i],['Mitsubishi','Xpander','MPV / van',/XPANDER/i],
 ['Nissan','Navara','Pickup',/NAVARA/i],['Nissan','Frontier','Pickup',/FRONTIER/i],['Nissan','Almera','Passenger car',/ALMERA/i],['Nissan','March','Passenger car',/MARCH/i],['Nissan','Note','Passenger car',/\bNOTE\b/i],['Nissan','Teana','Passenger car',/TEANA/i],['Nissan','Tiida','Passenger car',/TIIDA/i],['Nissan','Juke','SUV / crossover',/JUKE/i],['Nissan','X-Trail','SUV / crossover',/X[\s-]?TRAIL/i],
 ['Mazda','CX-3','SUV / crossover',/CX[\s-]?3(?!\d)/i],['Mazda','CX-30','SUV / crossover',/CX[\s-]?30/i],['Mazda','CX-5','SUV / crossover',/CX[\s-]?5/i],['Mazda','BT-50','Pickup',/BT[\s-]?50/i],['Mazda','Mazda 2','Passenger car',/MAZDA[\s_-]*2|มาสด้า\s*2/i],['Mazda','Mazda 3','Passenger car',/MAZDA[\s_-]*3|มาสด้า\s*3/i],
 ['Suzuki','Swift','Passenger car',/SWIFT/i],['Suzuki','Ciaz','Passenger car',/CIAZ/i],['Suzuki','Celerio','Passenger car',/CELERIO/i],['Suzuki','Ertiga','MPV / van',/ERTIGA/i],['MG','Extender','Pickup',/EXTENDER/i],['MG','ZS','SUV / crossover',/\bZS\b/i],['MG','HS','SUV / crossover',/\bHS\b/i],['MG','MG3','Passenger car',/\bMG[\s-]?3\b/i]
];
function category(l){const s=l.product+' '+l.sku;return /wiper|ใบปัด|ที่ปัด|ก้านปัด/i.test(s)?'Wipers':/clean|spray|foam|shine|restore|lubric|สเปรย์|โฟม|ทำความสะอาด|เคลือบ|ขจัด|ล้าง|หล่อลื่น/i.test(s)?'Car care':'Other';}
function fitment(l){if(category(l)!=='Wipers')return null;const s=text(l.variation)||text(l.sku),found=models.filter(x=>x[3].test(s));return found.length===1?{brand:found[0][0],model:found[0][1],type:found[0][2]}:null;}
function validate(args={}){const from=E.date(args.from),to=E.date(args.to);if(from!==args.from||to!==args.to||!from||from>to)throw Error('Choose valid From and To dates.');if(!['completed','active','all'].includes(args.basis||'completed'))throw Error('Choose a valid sales basis.');for(const key of ['store','platform'])if(args[key]!=null&&(typeof args[key]!=='string'||args[key].length>120))throw Error('Invalid customer filter.');return {from,to,basis:args.basis||'completed',store:args.store||'nakama',platform:args.platform||''};}
function summary(records,args){const f=validate(args),eligible=o=>!o.excluded&&o.status!=='Platform Processing'&&o.date>=f.from&&o.date<=f.to&&(f.store==='all'||(f.store==='nakama'?/^NKM_/.test(o.store):o.store===f.store))&&(!f.platform||o.platform===f.platform)&&(f.basis==='all'||(f.basis==='completed'?o.status==='Completed':['Completed','To Ship','Shipped','Unpaid'].includes(o.status)));
 const buyers=new Map(),locations=new Map(),cars=new Map(),types=new Map(),categories=new Map(),channels=new Map();let orders=0,gmv=0,units=0,enriched=0,identified=0,located=0,wiperUnits=0,fitmentUnits=0,fitmentOrders=0,bulkOrders=0,firstDate=null,lastDate=null;
 const add=(map,label,value,qty,orderKey)=>{if(!map.has(label))map.set(label,{label,gmv:0,units:0,ids:new Set()});const r=map.get(label);r.gmv+=value;r.units+=qty;r.ids.add(orderKey);};
 for(const o of records){if(!eligible(o))continue;orders++;firstDate=!firstDate||o.date<firstDate?o.date:firstDate;lastDate=!lastDate||o.date>lastDate?o.date:lastDate;let value=0,quantity=0;const cats=new Set();let hasFitment=false;
  for(const l of o.lines){const v=l.qty*l.price,c=category(l);value+=v;quantity+=l.qty;cats.add(c);add(categories,c,v,l.qty,o.key);if(c==='Wipers'){wiperUnits+=l.qty;const car=fitment(l);if(car){fitmentUnits+=l.qty;hasFitment=true;add(cars,car.brand+' '+car.model,v,l.qty,o.key);cars.get(car.brand+' '+car.model).brand=car.brand;cars.get(car.brand+' '+car.model).model=car.model;cars.get(car.brand+' '+car.model).type=car.type;add(types,car.type,v,l.qty,o.key);}}}
  gmv+=value;units+=quantity;if(hasFitment)fitmentOrders++;if(quantity>=10)bulkOrders++;add(channels,o.platform,value,quantity,o.key);
  if(o.customer?.version===1)enriched++;
  if(o.customer?.province){located++;add(locations,o.customer.province,value,quantity,o.key);}
  if(o.customer?.buyerHash){identified++;const b=buyers.get(o.customer.buyerHash)||{orders:0,gmv:0,units:0,cats:new Set(),bulk:false};b.orders++;b.gmv+=value;b.units+=quantity;for(const c of cats)b.cats.add(c);b.bulk||=quantity>=10;buyers.set(o.customer.buyerHash,b);}
 }
 const groups=new Map(),frequency=new Map();let repeat=0;
 for(const [id,b] of buyers){if(b.orders>1)repeat++;const mission=b.bulk?'Bulk purchase signal':b.cats.has('Wipers')&&b.cats.has('Car care')?'Wipers + car care':b.cats.size===1&&b.cats.has('Wipers')?'Wiper replacement':b.cats.size===1&&b.cats.has('Car care')?'Car care buyers':'Other / mixed purchases';add(groups,mission,b.gmv,b.units,id);add(frequency,b.orders===1?'One observed order':b.orders<5?'2–4 observed orders':'5+ observed orders',b.gmv,b.units,id);}
 const finish=(map,by='orders')=>[...map.values()].map(({ids,...r})=>({...r,gmv:Math.round(r.gmv*100)/100,orders:ids.size})).sort((a,b)=>b[by]-a[by]||a.label.localeCompare(b.label));
 const carRows=finish(cars,'units').map(r=>({...r,share:ratio(r.units,fitmentUnits),marketType:r.units/fitmentUnits>=.1?'Core demand':r.units/fitmentUnits<.01?'Niche demand':'Supporting demand'}));
 const stores=[...new Set(records.filter(o=>!o.excluded&&o.status!=='Platform Processing').map(o=>o.store))].sort(),platforms=[...new Set(records.filter(o=>!o.excluded&&o.status!=='Platform Processing').map(o=>o.platform))].sort();
 return {version:1,filters:f,options:{stores:stores.slice(0,500),platforms:platforms.slice(0,100)},coverage:{enrichedOrders:enriched,identifiedOrders:identified,locatedOrders:located,fitmentOrders,wiperUnits,fitmentUnits,buyerCoverage:ratio(identified,orders),locationCoverage:ratio(located,orders),fitmentCoverage:ratio(fitmentUnits,wiperUnits),firstDate,lastDate},totals:{orders,gmv:Math.round(gmv*100)/100,units,aov:ratio(gmv,orders),buyers:buyers.size,repeatBuyers:repeat,repeatRate:ratio(repeat,buyers.size),identifiedGmv:Math.round([...buyers.values()].reduce((n,b)=>n+b.gmv,0)*100)/100,bulkOrders},personas:finish(groups),frequency:finish(frequency),provinces:finish(locations).slice(0,15),cars:carRows,vehicleTypes:finish(types,'units'),categories:finish(categories,'gmv'),channels:finish(channels,'gmv')};
}
module.exports={enrichment,summary,validate,province,buyer,fitment,category};
