'use strict';
const {onCall,HttpsError}=require('firebase-functions/v2/https'),{initializeApp}=require('firebase-admin/app'),{getFirestore,Timestamp,FieldValue}=require('firebase-admin/firestore'),{getAuth}=require('firebase-admin/auth'),{getStorage}=require('firebase-admin/storage'),C=require('./lib/core');
initializeApp();const db=getFirestore(),bucket=getStorage().bucket(),auth=getAuth();
const Customer=require('./lib/customer'),crypto=require('node:crypto');
async function customerIdentityKey(){const object=bucket.file('private/internal/customer-identity-key');try{const [bytes]=await object.download({validation:'crc32c'});if(bytes.length!==32)C.fail('data-loss','Customer identity key is invalid.');return bytes;}catch(e){if(e.code!==404)throw e;}const bytes=crypto.randomBytes(32);try{await object.save(bytes,{resumable:false,preconditionOpts:{ifGenerationMatch:0},metadata:{contentType:'application/octet-stream',cacheControl:'no-store'}});return bytes;}catch(e){if(e.code!==412)throw e;const [saved]=await object.download({validation:'crc32c'});if(saved.length!==32)C.fail('data-loss','Customer identity key is invalid.');return saved;}}
async function member(request,allowed){C.project(process.env.GCLOUD_PROJECT||process.env.GOOGLE_CLOUD_PROJECT);if(!request.auth?.uid)C.fail('unauthenticated','Sign in to Nakama Management.');const [u,m]=await Promise.all([auth.getUser(request.auth.uid),db.doc('members/'+request.auth.uid).get()]);if(u.disabled)C.fail('permission-denied','Account disabled.');return C.role(request.auth,m.data(),allowed);}
function endpoint(options,handler){return onCall({region:'asia-southeast1',timeoutSeconds:60,memory:'512MiB',maxInstances:3,invoker:'public',cors:true,...options},async request=>{try{return await handler(request);}catch(e){if(e instanceof HttpsError)throw e;if(e instanceof C.Problem)throw new HttpsError(e.code,e.message,e.details);console.error('Nakama cloud failure',{code:e.code,message:e.message});throw new HttpsError('internal','The cloud operation failed. Previously published reports are unchanged. Retry or contact the administrator.');}});}
const Accounts=require('./lib/accounts')({db,auth,fail:C.fail,member,apiKey:require('./auth-config.json').apiKey});
for(const [name,method] of Object.entries({nkmRegister:'register',nkmUserLogin:'login',nkmAccountProfile:'profile',nkmLinkUserId:'link',nkmAccounts:'list',nkmReviewAccount:'review'}))exports[name]=endpoint({},request=>{C.project(process.env.GCLOUD_PROJECT||process.env.GOOGLE_CLOUD_PROJECT);return Accounts[method](request);});
const revisionRef=id=>db.doc('reports/'+id),monthRef=(id,month)=>db.doc(`reports/${id}/months/${month}`),chunkRef=(id,month,kind,index)=>db.doc(`reports/${id}/months/${month}/sections/${kind}/chunks/${String(index).padStart(6,'0')}`);
function result(id,j){return {id,state:j.state,revision:j.revision||null,completedAt:j.completedAt?.toMillis?.()||null,error:j.error||null,diagnostics:j.diagnostics||null};}
const readOrders=path=>C.readSnapshot(path,async objectPath=>(await bucket.file(objectPath).download({validation:'crc32c'}))[0]);
// Callable transport allows invocation; all data access requires verified Firebase authentication and an enabled membership.
exports.nkmWorkspace=endpoint({},async request=>{const user=await member(request),s=await db.doc('workspace/main').get(),d=s.data();return {revision:d?.revision||null,months:d?.months||[],updatedAt:d?.updatedAt?.toMillis?.()||null,role:user.role};});
exports.nkmBeginImport=endpoint({},async request=>{const user=await member(request,['importer','admin']),files=C.manifest(request.data?.files),id=C.randomId(),now=Date.now(),job=db.doc('imports/'+id),rate=db.doc('limits/'+user.uid);await db.runTransaction(async tx=>{const s=await tx.get(rate),d=s.data()||{},recent=d.windowStart>now-60000,attempts=recent?(d.attempts||0)+1:1;if(attempts>5)C.fail('resource-exhausted','Too many new imports. Wait one minute.');tx.set(rate,{windowStart:recent?d.windowStart:now,attempts});tx.create(job,{owner:user.uid,state:'uploading',files:Object.fromEntries(files.map(f=>[f.index,f])),createdAt:Timestamp.fromMillis(now),expiresAt:Timestamp.fromMillis(now+86400000)});});return {id,files:files.map(f=>({...f,path:`uploads/${user.uid}/${id}/${f.index}`}))};});
exports.nkmImportStatus=endpoint({},async request=>{const u=await member(request,['importer','admin']),id=C.uuid(request.data?.id),s=await db.doc('imports/'+id).get(),j=s.data();if(!j||(j.owner!==u.uid&&u.role!=='admin'))C.fail('permission-denied','Import unavailable.');return result(id,j);});
exports.nkmProcessImport=endpoint({timeoutSeconds:540,memory:'4GiB',cpu:2,concurrency:1,maxInstances:2},async request=>{
 const user=await member(request,['importer','admin']),id=C.uuid(request.data?.id),jobRef=db.doc('imports/'+id),workspace=db.doc('workspace/main'),lock=db.doc('internal/importLease'),token=C.randomId();let job,base;
 const done=await db.runTransaction(async tx=>{const [j,l,w]=await Promise.all([tx.get(jobRef),tx.get(lock),tx.get(workspace)]);job=j.data();const now=Date.now();if(!job||(job.owner!==user.uid&&user.role!=='admin'))C.fail('permission-denied','Import unavailable.');if(job.state==='complete')return result(id,job);if(job.state==='failed')C.fail('failed-precondition',job.error?.message||'Upload corrected files as a new import.');if(job.expiresAt.toMillis()<now)C.fail('failed-precondition','Upload expired. Start a new import.');if(l.data()?.expires>now)C.fail('aborted','Another import is processing. Wait, then retry this import.');base=w.data()?.revision||null;tx.set(lock,{token,job:id,baseRevision:base,expires:now+600000});tx.update(jobRef,{state:'processing',startedAt:Timestamp.fromMillis(now),error:FieldValue.delete()});return null;});if(done)return done;
 try{const files=[];for(const f of Object.values(job.files).sort((a,b)=>a.lastModified-b.lastModified||Number(a.index)-Number(b.index))){const object=bucket.file(`uploads/${job.owner}/${id}/${f.index}`);let meta;try{[meta]=await object.getMetadata();}catch(e){if(e.code===404)C.fail('failed-precondition',`${f.name}: upload is missing. Upload every part first.`);throw e;}if(Number(meta.size)!==f.size||meta.contentType!==f.contentType)C.fail('invalid-argument',`${f.name}: stored file differs from the manifest.`);const [bytes]=await bucket.file(object.name,{generation:meta.generation}).download({validation:'crc32c'});if(meta.metadata?.firebaseStorageDownloadTokens)await object.setMetadata({metadata:{firebaseStorageDownloadTokens:null}});files.push(C.parse(bytes,f.name));}
 let existing=[];if(base){const s=await revisionRef(base).get();if(!s.data()?.snapshot)C.fail('data-loss','Active order snapshot unavailable. Contact the administrator.');existing=await readOrders(s.data().snapshot);}
 const data=C.calculate(files,existing,await customerIdentityKey()),next=C.randomId(),parts=C.reports(data),snapshotPath=`private/revisions/${next}/orders.manifest.json`;
 await C.saveSnapshot(data.records,snapshotPath,(objectPath,bytes,contentType)=>bucket.file(objectPath).save(bytes,{resumable:false,preconditionOpts:{ifGenerationMatch:0},metadata:{contentType,cacheControl:'no-store'}}));
 await revisionRef(next).create({state:'draft',snapshot:snapshotPath,createdAt:Timestamp.now(),import:id,files:Object.values(job.files).map(f=>f.name),orders:data.orderCount,diagnostics:data.diagnostics});
 let writes=[];const flush=async()=>{if(!writes.length)return;const b=db.batch();for(const [r,d] of writes)b.set(r,d);await b.commit();writes=[];};for(const p of parts){writes.push([monthRef(next,p.month),p.meta]);for(const kind of ['daily','skus'])for(let i=0;i<p[kind].length;i++){writes.push([chunkRef(next,p.month,kind,i),{rows:p[kind][i]}]);if(writes.length>=20)await flush();}}await flush();
 await member(request,['importer','admin']);await db.runTransaction(async tx=>{const [l,w,m]=await Promise.all([tx.get(lock),tx.get(workspace),tx.get(db.doc('members/'+user.uid))]);C.role(request.auth,m.data(),['importer','admin']);if(!C.leaseValid(l.data(),token,base,w.data()?.revision,Date.now()))C.fail('aborted','Workspace changed. Retry this import.');const now=Timestamp.now();tx.set(workspace,{revision:next,months:parts.map(p=>p.month),updatedAt:now});tx.update(revisionRef(next),{state:'published',publishedAt:now});tx.update(jobRef,{state:'complete',revision:next,completedAt:now,error:FieldValue.delete(),diagnostics:data.diagnostics});tx.delete(lock);});return {id,state:'complete',revision:next,diagnostics:data.diagnostics};
 }catch(e){const retryable=!(e instanceof C.Problem)||['aborted','failed-precondition'].includes(e.code);await db.runTransaction(async tx=>{const l=await tx.get(lock);if(l.data()?.token!==token)return;tx.update(jobRef,{state:retryable?'uploading':'failed',error:{code:e.code||'internal',message:e instanceof C.Problem?e.message:'Processing failed. Retry this import.'}});tx.delete(lock);}).catch(e=>console.error('Import recovery failed',{code:e.code}));throw e;}
});
exports.nkmReportPage=endpoint({},async request=>{await member(request);const args=C.pageArgs(request.data),[r,m]=await Promise.all([revisionRef(args.revision).get(),monthRef(args.revision,args.month).get()]);if(r.data()?.state!=='published'||!m.exists)C.fail('not-found','Published month unavailable.');const meta=m.data(),count=args.kind==='daily'?meta.dailyChunks:meta.skuChunks;return {revision:args.revision,month:args.month,kind:args.kind,total:args.kind==='daily'?meta.dailyRows:meta.skuRows,...await C.page(async n=>(await chunkRef(args.revision,args.month,args.kind,n).get()).data()?.rows,count,args)};});
exports.nkmHistory=endpoint({},async request=>{await member(request);const s=await db.collection('reports').orderBy('publishedAt','desc').limit(30).get();return {history:s.docs.map(s=>{const d=s.data();return {revision:s.id,time:d.publishedAt.toMillis(),label:'Cloud orders imported',files:d.files,orders:d.orders};})};});
// Customer hashes remain in the private canonical snapshot. Only aggregate findings leave this endpoint.
exports.nkmCustomerInsights=endpoint({timeoutSeconds:540,memory:'4GiB',cpu:2,concurrency:1,maxInstances:2},async request=>{
 await member(request);let args;try{args=Customer.validate(request.data);}catch(e){C.fail('invalid-argument',e.message);}const workspace=(await db.doc('workspace/main').get()).data(),revision=workspace?.revision||null;
 let records=[];if(revision){const published=(await revisionRef(revision).get()).data();if(published?.state!=='published'||!published.snapshot)C.fail('data-loss','Published orders unavailable.');records=await readOrders(published.snapshot);}
 const report=Customer.summary(records,args);await member(request);return {...report,revision,months:workspace?.months||[],updatedAt:workspace?.updatedAt?.toMillis?.()||null};
});

// Stock documents remain private; only enabled members may read or mutate them.
const Stock=require('./lib/stock-engine');
exports.nkmStockForecast=endpoint({},async request=>{
 const op=request.data?.op||'load';
 if(op==='load'){await member(request);const saved=(await db.doc('stockForecast/main').get()).data();await member(request);return {revision:saved?.revision||null,state:saved?.state||Stock.empty(),updatedAt:saved?.updatedAt?.toMillis?.()||null};}
 if(op!=='save')C.fail('invalid-argument','Unknown stock operation.');
 const user=await member(request,['importer','admin']);let state;try{state=Stock.validate(request.data?.state);}catch(e){C.fail('invalid-argument',e.message);}
 if(Buffer.byteLength(JSON.stringify(state))>650000)C.fail('resource-exhausted','Forecast workspace exceeds 650 KB. Archive old POs before adding more.');
 const expected=request.data?.revision||null;if(expected!==null)C.uuid(expected);const ref=db.doc('stockForecast/main'),revision=C.randomId(),now=Timestamp.now();
 await db.runTransaction(async tx=>{const [saved,m]=await Promise.all([tx.get(ref),tx.get(db.doc('members/'+user.uid))]);C.role(request.auth,m.data(),['importer','admin']);if((saved.data()?.revision||null)!==expected)C.fail('aborted','Another user changed the stock forecast. Export your draft, then Refresh before saving.');tx.set(ref,{state,revision,updatedAt:now,updatedBy:user.uid});});
 return {state,revision,updatedAt:now.toMillis()};
});
exports.nkmStockDemand=endpoint({timeoutSeconds:540,memory:'4GiB',cpu:2,concurrency:1,maxInstances:2},async request=>{
 await member(request);const end=request.data?.end||null;if(end!==null&&!Stock.validDate(end))C.fail('invalid-argument','Choose a valid sales end date.');
 const workspace=(await db.doc('workspace/main').get()).data();let records=[];
 if(workspace?.revision){const r=(await revisionRef(workspace.revision).get()).data();if(r?.state!=='published'||!r.snapshot)C.fail('data-loss','Published orders unavailable.');records=await readOrders(r.snapshot);}
 const report=Stock.demand(records,end,workspace?.months||[]);await member(request);return {...report,revision:workspace?.revision||null};
});
